### ISSUE TITLE
Missing nodes/edges

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#1000]
## Current (buggy) behaviour

When viewing an interaction network, moving the slider all the way to 'more' and leaving all the filters off, there are still a number of hidden nodes/edges, the amount of which is different on each page load of the network.

## Desired behaviour

Should see the whole network.

## Minimum steps to reproduce
![image](https://user-images.githubusercontent.com/4706307/43975988-4da5d3a0-9cad-11e8-9120-a1190b630e03.png)

![image](https://user-images.githubusercontent.com/4706307/43976057-6d2f56c4-9cad-11e8-8800-46640154f791.png)

**Comment by jvwong** [comment]
depends on slider rate:
![bug](https://user-images.githubusercontent.com/4706307/43977572-8f9a76b2-9cb2-11e8-81ac-51b4393710d7.gif)

**Comment by IgorRodchenkov** [comment]
I noticed that too, [here](http://appsbeta.pathwaycommons.org/interactions?source=SMAD1).
We should not probably merge PRs before such issues (easy to see) get fixed.

E.g.
![image](https://user-images.githubusercontent.com/991169/43977835-43b02228-9cb3-11e8-8609-e64453618816.png)

**Comment by d2fong** [comment]
Can you see if the branch “slider-click-bug” fixes this issue

**Comment by jvwong** [comment]
Yeah this seems to solve these sets of issues.
