### ISSUE TITLE
Link to pathway and interaction database providers

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#1018]
## Description of new feature

Provide, when available, a link to the pathway or interaction database provider's site.

Specifically, in the pathway title bar. Not sure if there are other instances.

![image](https://user-images.githubusercontent.com/4706307/44212091-6c2e1500-a138-11e8-8ed2-0c2b19a16ab0.png)

## Motivation for new feature

Enhance the navigation to and from data provider sites.

**Comment by jvwong** [comment]
URI's [here](http://www.pathwaycommons.org/pc2/datasources)

**Comment by MichaelWrana** [comment]
Do we store a map for each data provider's website (ex "Reactome" => "https://reactome.org") somewhere or does that needs to be created as well?

**Comment by MichaelWrana** [comment]
Related: #86 #745 #489

**Comment by jvwong** [comment]
see http://localhost:3000/pc-client/datasources
src/client/services/server-api/index.js

**Comment by jvwong** [comment]
Sorry to tack this on, but does it make sense to 


1. swap the order to `datasource | title`? 
  - Reasons:  there is always a datasource, but not necessarily title (pathways and especially interactions), also datasources are generally short, but titles can be long.
2. If no title, show nothing, rather than `Unknown title`
  - `Unknown title` is not useful

**Comment by jvwong** [comment]
related to #930

**Comment by MichaelWrana** [comment]
Should be a relatively easy change.  Not sure about how it would affect #930 though

**Comment by jvwong** [comment]
@MichaelWrana - @gbader is suggesting we go with `title: datasource` instead. Can we do this?

**Comment by MichaelWrana** [comment]
See #1036

**Comment by jvwong** [comment]
Sorry I see that thanks.
