### ISSUE TITLE
Disable tooltips for glyphs with no metadata

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#1041]
Some glyphs typically have no associated metadata of any use (e.g. tooltips for compartments were previously removed). Generally, we should not display an empty tooltip. 

In this particular, case, source and sink nodes as a class could have their tooltips disabled.

[TP53 protein binds to GDF15 promoter results in increased expression of GDF15 | CTD ](http://appsbeta.pathwaycommons.org/pathways?uri=http://pathwaycommons.org/pc2/TemplateReactionRegulation_4e6106235cb0ce6eb9dbb234433b4d95)

![sink](https://user-images.githubusercontent.com/4706307/44430686-6f2a6a80-a569-11e8-932f-4fe3bf6f429d.png)

**Comment by jvwong** [comment]
Also: 'Logical operators'

[arginine degradation VI (arginase 2 pathway) | HumanCyc](http://appsbeta.pathwaycommons.org/pathways?uri=http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FPathway_43e05bd36bd327829396cb8f2ae87429)

![image](https://user-images.githubusercontent.com/4706307/44431056-af3e1d00-a56a-11e8-8023-16054d9a1cda.png)

**Comment by jvwong** [comment]
For now, could blacklist following, already done for 'compartments' in cy/events:

- Source and Sink
- Logical Operators
  - NOT, AND, OR
- Compartment

**Comment by maxkfranz** [comment]
I'd prefer a small message like 'No information available', because it can look like the app is broken if nothing pops up at all.

**Comment by d2fong** [comment]
is there any value in displaying information about what source and sink, compartments, and logical operators represent in sbgn?

**Comment by jvwong** [comment]
maybe just put in the class name/label and that should be enough so they all have tooltips.
