### ISSUE TITLE
Multiple tooltips, cannot dismiss  

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#1042]
## Environment info

- Browser version (client) :
- Node.js version (server) :

## Current (buggy) behaviour

//TODO 

## Minimum steps to reproduce

//TODO 
Hard to reproduce, but observed many times.

**Comment by jvwong** [comment]
Will close until I can reproduce.

**Comment by d2fong** [comment]
I think I found a way to reproduce an issue where tooltips get bugged and stay on the screen.

1. open any network with tooltips
2. do any of these events at the same/near the same time: click/drag/pan/zoom 
3. the tooltip will be frozen

potential solutions:
1.  debounce/throttle the tooltip show/hide functions?

**Comment by d2fong** [comment]
Actually it doesn't work all the time.
