### ISSUE TITLE
Disconnected nodes displayed

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#1067]
## Current (buggy) behaviour

 Displays one or more nodes without an edge.

## Desired behaviour

All nodes should be connected to something else.

## Minimum steps to reproduce

see [CDKN1A](http://appsbeta.pathwaycommons.org/interactions?source=CDKN1A), set slider to max.

![image](https://user-images.githubusercontent.com/4706307/45446713-9ae9cd80-b69b-11e8-8609-c5d5eddf61d9.png)

**Comment by d2fong** [comment]
I think this might be the case where nodes like DAPP1 are in the top 50 in terms of degree but all of the nodes that it connects to are not in the top 50 so it has no edges.  Still investigating to confirm if this is the case.

**Comment by jvwong** [comment]
Got it. I can only think of heavy handed solutions: 1) hide them 2) brute force paths-between.

**Comment by d2fong** [comment]
I think hiding them would be the quickest solution. What do you mean by brute force paths-between?

**Comment by jvwong** [comment]
I'll agree with 'hide' for now. By 'brute force' i mean for each node in 'connected' group, see if 1-neighbours overlap with the 1-neighbours of orphan (e.g. DAPP1) etc.

**Comment by jvwong** [comment]
Re #1068 - slider still thinks there's 50 nodes

**Comment by jvwong** [comment]
The disconnected nodes are still appearing:
http://appsbeta.pathwaycommons.org/interactions?source=GDF15
![image](https://user-images.githubusercontent.com/4706307/45558020-e7084f80-b80c-11e8-9f35-d3647f055826.png)
