### ISSUE TITLE
Format long database id chains and set max tooltip height

### ISSUE THREAD

**Issue by hmtinc** [PathwayCommons/app-ui#107]
Long chains such as the one the screenshot should be wrapped and broken up into multiple lines. 
The spacing between the ids should also be wider. 

![screen shot 2017-11-01 at 10 43 05 am](https://user-images.githubusercontent.com/1313810/32280220-82c5519a-bef1-11e7-8290-1d90e883e93c.png)

**Comment by gbader** [comment]
We shouldn't be showing database identifiers because they are not human readable. Sufficient to just provide a link to e.g. reactome. Also, reduce redundancy and improve use of space. Use English instead of user unfriendly biopax field names. Ask me for more details in person.

**Comment by hmtinc** [comment]
Should the database id fields just be replace with database names for the purpose of the tooltip? 
Also, hows 'Approved Name' instead of 'Standard Name'? 

![screen shot 2017-11-03 at 2 01 57 pm](https://user-images.githubusercontent.com/1313810/32388930-a200f398-c09f-11e7-9f8b-5628af8bd99b.png)
