### ISSUE TITLE
For some interactions queries, the queried node is erroneously filtered

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#1071]
http://appsbeta.pathwaycommons.org/interactions?source=PCNA

PCNA is not found in the network

## Initial guess why
PCNA probably doesn't have a degree that allows it make the top 50 nodes.

**Comment by d2fong** [comment]
PCNA degree: 527
top 50th degree: 583

**Comment by jvwong** [comment]
related to #1054.

Is it reasonable to give the query an infinite degree?

**Comment by d2fong** [comment]
Yeah I think so.

**Comment by maxkfranz** [comment]
Give it MAX_INT, not Infinity
