### ISSUE TITLE
interactions queried node detection is not case sensitive

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#1074]
go to: appsbeta.pathwaycommons.org/interactions?source=tp53
- tp53 is not recognized as the query node

go to: appsbeta.pathwaycommons.org/interactions?source=TP53
- TP53 is recognized as the query node

This might also have implications for caching

**Comment by maxkfranz** [comment]
Yes, the search terms should always be case-normalised internally.
