### ISSUE TITLE
Sometimes popovers don't open on graph elements

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/app-ui#1075]
## Environment info

- Browser version (client) : Tested on Safari 11.1.2 (12605.3.8.1), Chrome 69.0.3497.81 
- Node.js version (server) : N/A

## Current (buggy) behaviour

Sometimes clicking a node or edge doesn't open it's info popover.  I noticed this during testing, but a real user probably isn't as likely to reproduce this issue.

## Desired behaviour

Open on click.

## Minimum steps to reproduce

Quickly click between different elements in the graph.

**Comment by maxkfranz** [comment]
Not as noticeable anymore

**Comment by jvwong** [comment]
Let's close unless this comes up again.
