### ISSUE TITLE
mediator linkouts from interaction tooltips - downloads don't work

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#1091]
## Environment info

- Browser version (client) : Chrome 68.0.3440.106
- Node.js version (server) : 8.12.0

## Current (buggy) behaviour

downloads from the sbgn view following interactions links are empty
## Desired behaviour

if the files simply don't exist I am not sure if we can do anything.  If there is a bug in the app preventing the files from downloading properly, it should be fixed.

## Minimum steps to reproduce

1. go to any interactions view
2. click on any interaction
3. click on any of the 'Pathways Links'
4. in this new view click on any of the downloads except png
5. all the results are empty

**Comment by d2fong** [comment]
example: http://localhost:3000/pathways?uri=http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FTemplateReaction_5fc66c200246fd04fb2d44f95132aae4

**Comment by jvwong** [comment]
I can get downloads for BioPAX, JSON-LD, SBGN-M. The other ones (GMT, (x)SIF) are probably trivial/useless since there is but one gene.

I think's its fine personally.

**Comment by d2fong** [comment]
ok.

**Comment by maxkfranz** [comment]
We could add a warning if a particular file type is more or less empty.
