### ISSUE TITLE
evaluate whether we need external-service-data

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#1108]
In /src/client/common/external-service-data.js is a list of databases like CHEBI, KEGG, Gene Cards, etc.

It is currently only used in one place in /src/models/pathway-node-metadata.js to generate urls linkouts to databases that appear in the pathway node metadata.

Requirements:
- find out if we even need all of these databases in this file or if we only need a select few
- move this file to the models folder if we still need it

**Comment by jvwong** [comment]
Let's support link out to the following xref db:
  - 'chebi'
  - 'hgnc symbol'
  - 'uniprot knowledgebase'
  - 'reactome'
  - 'ensembl'
  - 'ncbi gene'

Merge the relevant entries in `common/external-service-data.js` into `models/datasources.js` by adding a 'meta resolver' value, upon which we can append the local identifier. 

Everything will be hardcoded in a file but at least its all in once place.

**Comment by jvwong** [comment]
Also merge `src/models/entity/summary.js` `DATASOURCES`.

**Comment by d2fong** [comment]
To be replaced by the identifers url service
