### ISSUE TITLE
interactions network result is different depending on how the 'sources' param is specified

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#1117]
In the client, a interactions network is requested.  The client uses the 'query-string' package, and the result of running ```qs.stringify(sources)``` is: ```sources=MDM2&sources=TP53```, resulting in a url that looks like this: ```/api/interactions?sources=MDM2&sources=TP53```

This gives the following result:
![screen shot 2018-10-23 at 12 33 17 pm](https://user-images.githubusercontent.com/2328291/47376146-dc6c9000-d6bf-11e8-9851-411d36d5502a.png)

When playing around with the API, I accidentally queried this url instead:
```/api/interactions?sources=MDM2,TP53```

This gives a 'full' result that we would usually expect:
![screen shot 2018-10-23 at 12 35 13 pm](https://user-images.githubusercontent.com/2328291/47376235-1b9ae100-d6c0-11e8-8ae3-57783f4d105f.png)

I suspect that the way we input the arguments to sifgraph has an effect on the output.  I also assume that we would like the 'full' version of the graph.

@jvwong, @IgorRodchenkov @maxkfranz

**Comment by d2fong** [comment]
In the ```server/external-services/pathway-commons``` sifGraph function:
When source is specified as a comma separated string, the full graph is returned.
Example params string: ```source=MDM2%2CTP53```


When source is specified as a array, only two nodes (MDM2 and TP53) are returned.
Example params string: ```source=MDM2&source=TP53```

**Comment by IgorRodchenkov** [comment]
I am pretty sure this has nothing to do with the sifgraph service but has rather with how it's inconsistently called from app-ui.

Could you please specify what sifgraph query is formed from "/api/interactions?sources=MDM2,TP53" and "sources=MDM2&sources=TP53" exactly? It might be 'neighborhood' in one case, and 'pathsbetween' in the other; also direction parameters matters ('bothstream' vs 'undirected').

Sifgraph service does expect comma-separated values (unlike PC2/get or /graph), and it's 'source' not 'sources' there.

See:

https://github.com/PathwayCommons/sifgraph-server/blob/master/src/main/java/org/pathwaycommons/sif/server/Controller.java

http://www.pathwaycommons.org/sifgraph/swagger-ui.html

**Comment by d2fong** [comment]
The swagger docs suggest that the request should be ```http://www.pathwaycommons.org/sifgraph/v1/pathsbetween?directed=false&limit=1&source=TP53&source=MDM2```

Does this mean that ```http://www.pathwaycommons.org/sifgraph/v1/pathsbetween?directed=false&limit=1&source=TP53%2CMDM2``` is unsupported?  Because it still gives a 200 response code back and the result corresponding to the second picture in the first comment.

**Comment by d2fong** [comment]
<img width="970" alt="screen shot 2018-10-23 at 1 18 44 pm" src="https://user-images.githubusercontent.com/2328291/47378485-45ef9d00-d6c6-11e8-97e0-07f16297bd23.png">
![Uploading Screen Shot 2018-10-23 at 1.18.29 PM.png…]()

**Comment by d2fong** [comment]
@IgorRodchenkov here are the two urls:

## Only gives back MDM2, TP53:
http://www.pathwaycommons.org/sifgraph/v1/pathsbetween?directed=false&limit=1&pattern=CONTROLS_STATE_CHANGE_OF&pattern=CONTROLS_TRANSPORT_OF&pattern=CONTROLS_EXPRESSION_OF&pattern=CATALYSIS_PRECEDES&pattern=INTERACTS_WITH&source=MDM2&source=TP53

## Gives back MDM2, TP53 and other genes:
http://www.pathwaycommons.org/sifgraph/v1/neighborhood?direction=UNDIRECTED&limit=1&pattern=CONTROLS_STATE_CHANGE_OF&pattern=CONTROLS_TRANSPORT_OF&pattern=CONTROLS_EXPRESSION_OF&pattern=CATALYSIS_PRECEDES&pattern=INTERACTS_WITH&source=MDM2%2CTP53

**Comment by IgorRodchenkov** [comment]
Thanks @d2fong.

Common, you're comparing apples with oranges and at the same time different ways to list gene names above... Should be 'neighborhood' vs. 'neighborhood' and 'pathsbetween' vs. 'pathsbetween' :))

No, source=a,b,c - comma-separated are not supposed to work (the controller that I implemented does not support this and simply treats 'a,b,c' as one value). Do not use this hack.

Anyway, I will debug the sifgraph java library to see what's going on there (perhaps, it's a feature or bug I wasn't aware of if it splits a comma-separated text internally and runs a graph query anyway).

**Comment by IgorRodchenkov** [comment]
http://www.pathwaycommons.org/sifgraph/v1/neighborhood?direction=UNDIRECTED&limit=1&pattern=CONTROLS_STATE_CHANGE_OF&pattern=CONTROLS_TRANSPORT_OF&pattern=CONTROLS_EXPRESSION_OF&pattern=CATALYSIS_PRECEDES&pattern=INTERACTS_WITH&source=MDM2&source=TP53 
gets exactly the same result as if (hack) -
...&source=MDM2,TP53 
(no need to encode comma as %2C in a URL query)
