### ISSUE TITLE
Pathway: click doesn't launch tooltip but rather results in persistent select/drag

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#1118]
## Environment info

- Browser version (client) : Firefox 62.0.3 (64-bit); Chrome Version 70.0.3538.67 (Official Build) (64-bit)

## Current (buggy) behaviour

When I view a pathway and click a node, the node follows the mouse, as if it were being dragged.

## Desired behaviour

Should display tooltip.

## Minimum steps to reproduce

View pathway [Transcriptional activation of cell cycle inhibitor p21 | Reactome](http://appsbeta.pathwaycommons.org/pathways?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-69895). Click and release on 'TP53' complex and move mouse around.

**Comment by d2fong** [comment]
Should be fixed now.
