### ISSUE TITLE
add linux instructions for setting up chrome automation on the server

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#1123]
cytosnap has to use either puppeteer or phantomjs.  Both of these require extra packages on VM that the app runs on (production, development, etc).  

1. update the documentation related for these extra build steps
2. if there is a docker image, it needs to be updated to get these build packages
3. setting up this app on other vms needs to include build instructions to get these packages

ubuntu steps for phantomjs:
https://gist.github.com/d2fong/8b7b48dd2c853034e5785bedf992e6aa

ubuntu steps for puppeteer:
https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker

**Comment by IgorRodchenkov** [comment]
Could someone please add some more information here (why is this an issue, which part or feature of app-ui)?

**Comment by maxkfranz** [comment]
It's for the graph screenshots.  It requires headless Chrome to work, and that requires several packages that don't come installed by default on the Ubuntu server ISO.

**Comment by d2fong** [comment]
@IgorRodchenkov You only need to run the following commands to install puppeteer:

```sh
apt-get update && apt-get install -y wget --no-install-recommends \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get purge --auto-remove -y curl \
    && rm -rf /src/*.deb

```

**Comment by d2fong** [comment]
```sh
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont \
      --no-install-recommends \
```
