### ISSUE TITLE
Use p-memoize() with LRU caches for fetches

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/app-ui#1139]
## Description of new feature

Use p-memoize to cache fetch() calls: https://github.com/sindresorhus/p-memoize

## Motivation for new feature

- Avoids duplicate code for using LRU caches with fetch().
- Already handles promise rejection.
- Can just pass in LRUCache to memoize()

**Comment by jvwong** [comment]
> cache
> - Type: Object
>  - Default: new Map()
>  - Use a different cache storage. Must implement the following methods: .has(key), .get(key), .set(key, value), .delete(key), and optionally .clear(). You could for example use a WeakMap instead or quick-lru for a LRU cache.

In the app we use lru-cache which defines a `del(key)` rather than `delete(key)` - use this [quick-lru](https://www.npmjs.com/package/quick-lru) instead?

**Comment by maxkfranz** [comment]
quick-lru should be fine for what we're doing.

**Comment by maxkfranz** [comment]
May as well ditch lru-cache then

**Comment by jvwong** [comment]
Small update required to `src/server/external-services/pathway-commons.js` to accomodate quick-lru pacakge API.
