### ISSUE TITLE
Entity Summary search is not interpreting tab character as token-separator

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#1157]
## Current (buggy) behaviour

Doesn't appear that  tabs are being interpreted as token separators in user queries. Consequently,  gene identifiers aren't being recognized (no summary displayed).  

## Desired behaviour

It should recognize or parse strings for common separators: spaces, tabs, newlines etc. 
 
## Minimum steps to reproduce

Copy pasted in gene list from excel row.

**Comment by maxkfranz** [comment]
```js
string.split(/\s+/)
```

**Comment by jvwong** [comment]
Very strange, the query.q string is leaving the client intact (e.g.q=`CAPNS1	CAPNS2`), but arriving at the /summary/entity/search service endpoint with the 'horizontal tab' character removed (e.g.`CAPNS1CAPNS2`):

https://github.com/PathwayCommons/app-ui/blob/development/src/server/routes/summary/index.js#L5

**Comment by jvwong** [comment]
I'm folding this into #1156
