### ISSUE TITLE
Entity summary box: small width - link styling

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#1165]
On small width, the gene linkouts are crunched together. 
![image](https://user-images.githubusercontent.com/4706307/48631837-72c56600-e98d-11e8-950c-33fbabe1e34d.png).

This is exacerbated by long gene titles.

**Comment by maxkfranz** [comment]
On small screens, they should be on a second line.

**Comment by jvwong** [comment]
This is moot because of upcoming #1191.
