### ISSUE TITLE
Update Reactome logo

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/app-ui#1167]
## Description of new feature

Update the Reactome logo: https://reactome.org/about/logo

## Motivation for new feature

Our copy is out of date

**Comment by d2fong** [comment]
The way we use logos is that we just load them from links that pathway commons gives us.  I think @IgorRodchenkov will have to update the logos.

**Comment by IgorRodchenkov** [comment]
Current logo comes from PC10 metadata. 
In PC11 we will use the new Reactome release and logo.
