### ISSUE TITLE
configure logging for production to reduce logging file bloat

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#1179]
@IgorRodchenkov has issues on the prod machine related to having large debug/error/info log files.  
He would like to have it so that logging output is organized properly and also minimized so that the log files leave a small file footprint.

**Comment by maxkfranz** [comment]
Shouldn't this be the responsibility of a log rotator?

**Comment by IgorRodchenkov** [comment]
But we don’t want 3-4 different log files created and used by the app in production... Log rotation is anyway configured manually,  separately, if at all, and perhaps separately for the Docker use case. If apps write to no more than one stream, at least in production, it helps a lot.

IR

**Comment by maxkfranz** [comment]
If you combine the files, it may make manually reading the files more difficult (esp. for the main one we'd care about --- errors).  I don't have a strong preference either way.
