### ISSUE TITLE
determine if the enrichment tooltip 'gene list' is sufficient or if it can be improved

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#1192]

**Comment by jvwong** [comment]
I suspect that users (including myself), intuitively, would be interested in:
1. the proportion of query genes in each pathway 'hit' 
2. how 'hits' are related 

You can sort of see how g:Profiler has attempted to display this in a table form, with the right-side showing 'overlap' and left-side showing some 'relatedness':

![image](https://user-images.githubusercontent.com/4706307/49523226-52474800-f877-11e8-93d5-0bd887be3905.png)

**Comment by jvwong** [comment]
A related subtlety of `analysis`/g:GOSt is that only the intersection of each pathway and the background is used in the enrichment. Basically, that means that the algorithm only tests the query against a subset of the genes in each pathway.

**Comment by d2fong** [comment]
Enrichment edge E between pathways P1 and P2 contains the intersection of P1 and P2.  Does it make sense to show this in an edge tooltip?

**Comment by d2fong** [comment]
I can try to pull out the 'relatedness' data from gprofiler

**Comment by jvwong** [comment]
I think the edge width is enough information personally. I don't think we need a tooltip.

**Comment by jvwong** [comment]
Addressed in #1207
