### ISSUE TITLE
When it shows a Factoid document by id, download feature is broken

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/app-ui#1196]
E.g., http://appsbeta.pathwaycommons.org/factoids/86f7fc9b-2a91-4cbb-9320-1a3e98a3abc5
- cannot download as BioPAX, SIF, SBGN, etc. I think, this is broken due to re-using the menu components and buttons that were originally made for network views/data generated from PC search (i.e., "normal" app-ui use case); then, we connected this and factoid apps and should apparently call different services (factoid api/biopax/{id}, api/sbgn/{id}) to get the downloads work.

**Comment by IgorRodchenkov** [comment]
@d2fong honestly, i am not sure how to do this. 
Basically, the links what show up once you click in the left-top menu button, in the case of BioPAX and SBGN-ML downloads, should use the Factoid api/document/biopax/{docId} or ../sbgn/{docId} api instead of what/where they currently do/go. However, this change should not break the download actions for the normal use case; i.e., when we go from app-ui search to viewing a pathway or interactions (with no factoid involved)... Could you look into this, please?

**Comment by jvwong** [comment]
Two options:
1. Remove or filter out those non-functional
2. Disable
