### ISSUE TITLE
Enrichment visualization: Unrecognized pathways from analysis 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#1200]
In short, the `visualization` is complaining about unrecognized pathways from the `analysis` which arises because the gmt file `src/server/routes/enrichment/visualization/hsapiens.pathways.NAME.gmt` is out-of-date.  Short fix is to update with new GMT file.

Longer: the trade-off of using the 'live' rather than sometimes-offline archived version of g:Profiler services (g:Convert, g:GOSt) is we gotta check-in for GMT file updates. Unfortunately, the file we need is buried in a zip file.

**Comment by maxkfranz** [comment]
If the overall zip file isn't too big, it wouldn't be unreasonable for the server to pull the file on startup.

It could unzip the file in memory and keep the gmt file cached in memory for enrichment queries.  We could use the checked-in gmt file as a fallback.

**Comment by jvwong** [comment]
`gprofiler_hsapiens.NAME.gmt.zip` is 84.4 MB. The file that we use inside this, `hsapiens.pathways.NAME.gmt` is 10.9 MB.

**Comment by maxkfranz** [comment]
How about using a periodic update (e.g. with [node-cron](https://www.npmjs.com/package/node-cron)?  We could update automatically on server startup and automatically once per week thereafter?

We depend on gprofiler for all the enrichment services anyway, so I think it's fine to depend on this file more dynamically.

**Comment by maxkfranz** [comment]
Basically the flow would be:

- Get an input stream, `f`, for the HTTP request to download the zip
- Pipe `f` to unzip: https://www.npmjs.com/package/unzip
- Once the stream has ended, pick out the human gmt file
- Cache the gmt file
