### ISSUE TITLE
Enrichment: Node/pathway tooltip linkout bug

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#1202]
## Current (buggy) behaviour

Node tooltip link for Reactome has local ID that repeats the 'R-HSA' prefix.

## Desired behaviour

Should be a valid local ID and uri

## Minimum steps to reproduce

- [Launch sample enrichment](http://localhost:3000/enrichment?source=DOT1L,AFF4,NAP1L3,BRPF1,TCF20,HLTF,SIRT1,TDG,SUV39H2,CBX7)
- Click node for `Epigenetic regulation of gene expression`
- Hover over link 'Reactome'

![image](https://user-images.githubusercontent.com/4706307/49477036-95f37080-f7e9-11e8-91ca-50ac5c356104.png)

**Comment by d2fong** [comment]
related piece of code:

```js
    else if( id.includes('REAC') ) dbInfo = {name: 'Reactome', url:'http://identifiers.org/reactome/' + id.replace("REAC:", "R-HSA-") };
```

**Comment by jvwong** [comment]
FYI, [October release](https://biit.cs.ut.ee/gprofiler_archive2/r1760_e93_eg40/web/) resulted in change from ID string format `REAC:123456` to `REAC:R-HSA-123456`

**Comment by d2fong** [comment]
So this code should be changed to just remove the 'REAC:' substring?

**Comment by jvwong** [comment]
I want to try to clean this up to reuse our services/constants...I'll try a PR.
