### ISSUE TITLE
unified search service bugs

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#1208]
1. I dont get any genes back from the unified search service
example query:
'TP53 MDM2 PCNA XRCC2' returns { genes: [], pathways: [...] }
2. the search code passes query (object) to functions like 'tokenize' and 'sanitize' which expects strings.  these functions should be passed query.q instead.

**Comment by d2fong** [comment]
see cc8d70dc1c1a7b7e4d6ab7c4499973941bd56963

**Comment by jvwong** [comment]
I tracked this down to the cache wrapping `validatorGconvert` that is, `geneSearch` works when i remove the cache.
https://github.com/PathwayCommons/app-ui/blob/7de140c604daa656a28b7c33992fd03a23817e7d/src/server/external-services/gprofiler/gconvert/index.js#L115

**Comment by jvwong** [comment]
just saw that there's a new `cachePromise` function wrapping `validatorGconvert`.

**Comment by d2fong** [comment]
I have noticed that problem before too.  I just don’t understand why it keeps happening...

**Comment by jvwong** [comment]
My observation is that the validator is returning cached responses even though the parameters (target) are different.

**Comment by jvwong** [comment]
My guess is that the following: 

https://github.com/PathwayCommons/app-ui/blob/b688470bcd18708f34ac3405a27e08ff1732357e/src/server/cache.js#L5

is the offender - the `arguments` formal parameter overwrites the function `arguments` object.
