### ISSUE TITLE
Separate sidebar metadata view from the tooltip metadata view. 

### ISSUE THREAD

**Issue by hmtinc** [PathwayCommons/app-ui#121]
Currently, the sidebar metadata view is generated by the same functions that generates the tooltip. This helps avoid code duplication, but prevents the tooltip and sidebar metadata views from being styled differently. 

The sidebar code generation function should append on a sidebar class to all elements to allow for more in-depth styling.

**Comment by maxkfranz** [comment]
Why is it that they can't share the same style?
