### ISSUE TITLE
Error handling and user notification 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#1210]
## Description of new feature

Rather than the dreaded infinite spinner, there should be some information provided to the user in the case of TimeoutError or any other error for that matter. 

## Motivation for new feature

This would encourage users to try again at a later time, reduces frustration or the notion that the app is 'broken'.  

![bug_timeout](https://user-images.githubusercontent.com/4706307/49653110-fbba4500-fa01-11e8-8dc7-36d6c9f94f1b.gif)

**Comment by jvwong** [comment]
As a start, manually go through and disable each external service (including PC WS) individually, to assess major point of failures.

**Comment by maxkfranz** [comment]
This could be handled more generally as error notifications -- not all errors will be timeouts and we should probably have some feedback in either case.

**Comment by jvwong** [comment]
- Search
  - service: `/api/search`
    - dependency: `validatorGconvert`
      - swallow caught errors 
    - dependency: `validatorGconvert` 
      - re-throw errors and notify client

**Comment by jvwong** [comment]
Could port the notifications system from Factoid?

**Comment by jvwong** [comment]
One more PR - handle errors / Timeouts for enrichment and interactions app.
