### ISSUE TITLE
Timeouts: Client can never recover from an Error swallowed on server

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#1211]
## Current (buggy) behaviour

Sometimes we have made a decision to swallow errors on the server-side (e.g. `search` Timeouts for external services like g:profiler/g:Convert). However, the client shares an identical fetch Timeout threshold (5 sec) and thus will throw its own Timeout, never 'seeing' the fallback server response. 

## Desired behaviour

Guessing we could use some more granularity in Timeouts, especially in  analysis apps like enrichment, which users will accept  taking longer than a 'search'.

## Minimum steps to reproduce

Throw Timeout on server for call to pc.X at  `FETCH_TIMEOUT` and run the X app etc.

**Comment by maxkfranz** [comment]
A simple approach is to have more lenient timeout values on the client (e.g. twice the server value), but we'll probably have to evaluate case-by-case.

**Comment by jvwong** [comment]
#1217 adds a fetch api for custom `timeout`. Will leave handling on case-by-case basis as described in #1210.
