### ISSUE TITLE
Paint - clearer colour mapping

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#123]
Nodes seem to be mapped to all colours of the rainbow.  It is hard to tell whether a value is low or high.  Also, users will not know what colour is on the low or high scale.

- [ ] rework the mapping function so that the spectrum of colours is more reasonable.
- [ ] add colour legend to show which values are low and which are high

**Comment by jvwong** [comment]
Enrichment Map has a good example of this for showing enrichment in either phenotype or class:

![screenshot at nov 02 23-47-12](https://user-images.githubusercontent.com/4706307/32359990-4b084b6c-c028-11e7-990d-69693c8c312c.png)

**Comment by d2fong** [comment]
What mapping functions makes the values fall in that range?  All of the raw values in Ruth's data are positive.

**Comment by d2fong** [comment]
TODO:
- [ ] for each row, determine n fn(expression values), where fn is the currently selected function to apply.  One of (max, min, count, mean, etc)
- [ ] find the global max and min for each of these values (across all rows)
- [ ] compute the midpoint of max and min
- [ ] for each value compute the colour based on the distance between value and the midpoint
       and the distance between the value and max/min

**Comment by d2fong** [comment]
Probably need Ruth's input here in terms of using global max/min or local (per row) max/min

**Comment by d2fong** [comment]
https://stackoverflow.com/questions/10981324/ggplot2-heatmap-with-colors-for-ranged-values
