### ISSUE TITLE
Enrichment: Alternative way to display input gene list

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#1232]
## Description of new feature

The requirement is that the user be presented with the list of genes used for the pathway enrichment analysis. 

## Motivation for new feature

Currently we just jam the list into the title but I'm not sure this plays well with [long query lists](http://appsbeta.pathwaycommons.org/enrichment?source=DOT1L,AFF4,NAP1L3,BRPF1,TCF20,HLTF,SIRT1,TDG,SUV39H2,CBX7,DNMT1,DPY30,ING5,MLLT6,CHD1L,USP27X,BRPF3,ELP4,HCFC1,MARCH5,SCML2,PRDM10,SUPT16H,TRIM24,GTF2H1,KDM3A,PAF1,PCGF5,BAZ1B,NCOA1,UBE2B,SGF29,KDM5B,MTA3,PCMT1,GTF3C4,MTA2,RBBP4,RNF20,SETD2,SSRP1,MBD1,POLR2B,TP53BP1,UBR7,ARID4B,ASH1L,BRD4,HAT1,HDAC1,KAT2A,MBD3,MSL3,RPA3,BAZ2A,JMJD6,PHF7,SIN3B,SP100,ZMYND11):

![image](https://user-images.githubusercontent.com/4706307/49886240-1bd57400-fe07-11e8-843a-c7f649769d74.png)

**Comment by d2fong** [comment]
![screen shot 2018-12-13 at 10 48 53 am](https://user-images.githubusercontent.com/2328291/49949888-bf388e80-fec4-11e8-9b4c-c785f4b6b81b.png)
![screen shot 2018-12-13 at 10 48 47 am](https://user-images.githubusercontent.com/2328291/49949889-bf388e80-fec4-11e8-826a-36e11aee68a6.png)
how about something like this

**Comment by jvwong** [comment]
Maybe  more descriptive like `Pathways enriched for A, B and N other genes`.
