### ISSUE TITLE
enrichment layout bug

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#1233]
1. open the enrichment app http://localhost:3000/enrichment?source=DOT1L,AFF4,NAP1L3,BRPF1,TCF20,HLTF,SIRT1,TDG,SUV39H2,CBX7,DNMT1,DPY30,ING5,MLLT6,CHD1L,USP27X,BRPF3,ELP4,HCFC1,MARCH5,SCML2,PRDM10,SUPT16H,TRIM24,GTF2H1,KDM3A,PAF1,PCGF5,BAZ1B,NCOA1,UBE2B,SGF29,KDM5B,MTA3,PCMT1,GTF3C4,MTA2,RBBP4,RNF20,SETD2,SSRP1,MBD1,POLR2B,TP53BP1,UBR7,ARID4B,ASH1L,BRD4,HAT1,HDAC1,KAT2A,MBD3,MSL3,RPA3,BAZ2A,JMJD6,PHF7,SIN3B,SP100,ZMYND11
2. run a layout
3. zoom in on any node
4. edges seem to disappear

**Comment by d2fong** [comment]
note:  I was unable to reproduce this on Chrome Version 69.0.3497.100

**Comment by d2fong** [comment]
I was unable to reproduce this on Firefox 64.0

**Comment by jvwong** [comment]
Observations:

- @d2fong unable to reproduce on OSX High Sierra, Chrome Version 71.0.3578.98 (Official Build) (64-bit) or Firefox Firefox 64.0  
- @jvwong able to reproduce on OSX Mojave Version 71.0.3578.98 (Official Build) (64-bit)  and Firefox 63.03

**Comment by maxkfranz** [comment]
I didn't notice this issue and made a duplicate: https://github.com/PathwayCommons/app-ui/issues/1236
