### ISSUE TITLE
Paint - make the painted pie take up the whole node background

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#124]
Right now the painted pie takes up only a sub circular region of the node and not the whole node. 

Make it take up the whole node outerwidth/outerheight

- [ ] Probably involves a cytoscape.js change to how the pie is drawn

**Comment by d2fong** [comment]
Here is how the painted nodes currently look:
![screen shot 2017-11-02 at 5 00 53 pm](https://user-images.githubusercontent.com/2328291/32350097-a26fdb1a-bfef-11e7-93f0-e6227984d24d.png)

**Comment by maxkfranz** [comment]
What about putting the pie as a smaller circle in the bottom-right corner of the node.  That would require only a offset properties (x, y) for the pie.

It might be useful to have each  pie have the same total number of possible slices.  That way, a colour always has the same position.  You can just look at the same place on each node to see whether it has a particular colour.

**Comment by d2fong** [comment]
I think that is a good idea.  Right now the colours obscure the label, so it is harder to read.

**Comment by d2fong** [comment]
Ruth/Jeff decided that there should only be one colour painted on the background for now.
