### ISSUE TITLE
Paint - Filter nodes that do not have enrichment data associated with them

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#125]
A good portion of nodes usually don't have any enrichment data associated with them and they are just floating in a tiled format along with all the other nodes, nested in a complex parent node.

Maybe it makes sense for these nodes that do not have any data associated with them to be removed

**Comment by d2fong** [comment]
![screen shot 2017-11-02 at 5 07 26 pm](https://user-images.githubusercontent.com/2328291/32350290-57eb8c00-bff0-11e7-8172-ffe1c384a1e2.png)


All the macromolecule nodes that do not have enrichment data might just be causing noise.

**Comment by jvwong** [comment]
Could this be a 'hide/show' feature with a sane default?

**Comment by d2fong** [comment]
Maybe a better idea would be to collapse complex nodes that do not have a single painted child node.
