### ISSUE TITLE
Show interactions card only if there is data

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#1251]
1. enter the following query in the search app:
ADAM10	ADAM17	AGXT	ANGPT4	ANXA4	APH1A
2. click the interactions app linkout
3. see that there are no interactions to display
4. this should not happen

**Comment by d2fong** [comment]
Solution:
- prefetch the interactions/enrichment networks and check if they are empty

Two approaches:
1. the server can do this to reduce complexity of the front end, the front end then checks the server response to see which app linkouts to display
2. the front end can fetch both networks and decide itself which one to display, absolving the server of that responsibility

Current thinking: let the frontend handle it

**Comment by jvwong** [comment]
Relates to case when there are only a few genes and enrichment analysis might not be sensible.

- Alternatives
  - always show (current)
  - hide card
  - disable card

**Comment by jvwong** [comment]
e.g. TMCC2 FUT10 GPR65 STPG2 PIRC91 PRDX5 (TP53)
