### ISSUE TITLE
Paint - Determine if duplicate painted nodes is correct or not

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#127]
Enrichments are mapped to nodes based on the label of the enrichment and the label of the node. 

e.g p53 -> p53

In many cases, labels are not unique to a single node.  There may be multiple nodes that have the label p53.  This causes both of these nodes to be painted with the same colours.  

Jeff mentioned that this might not be correct because while two nodes may have the same label, they might have different ids and one might be the real p53 that is to be painted, while the other might not.

**Comment by d2fong** [comment]
![screen shot 2017-11-02 at 5 19 24 pm](https://user-images.githubusercontent.com/2328291/32350876-ff8780bc-bff1-11e7-934c-fc913320c601.png)

In this case, the node RPS15A appears in two places, and they share the same prefix id:
"Protein_75464134e778150a8257c19ebb99b4a7_Complex_6a85fd42b4afa35969013385ce61b5bc"
and the id of the other:
"Protein_75464134e778150a8257c19ebb99b4a7_Complex_7111ba9479a5778e6a8e79a2bf343650"

The difference appears to be their parent nodes which make the second part of their id different

**Comment by jvwong** [comment]
This 'ambiguity' is fine. The Painter data will typically arise from large scale experimental measurements of gene expression (mRNA, protein) that does not contain any information about where in the cell the entity is or it's 'state'. 

In BioPAX terms, I think this 'generic' term for an entity is an 'EntityReference' like 'p53'.

**Comment by d2fong** [comment]
Ok.
