### ISSUE TITLE
Datasource filter disappears if no results / Remove datasource filter

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#1272]
The 'datasource' drop-down gets replaced with 'Your search didn't match any pathways' if no results for that datasource are available. I'd expect the filter to still be there. Also, the filter gets 'stuck' on the existing datasource.

 In any case, the Google Analytics say that filter hasn't really ever been touched more than 1 or 2 times in 6 months. Let's just drop it.

**Comment by jvwong** [comment]
While we're at it let's drop the `gt` and `lt` params as they are never respected on server side.

**Comment by maxkfranz** [comment]
The filter may be important to certain data providers.  Maybe @gbader could weigh in.

A compromise could be to remove the dropdown from the UI but allow a special query string (e.g. `source:reactome pcna`) in the search box to set a data source filter.

**Comment by jvwong** [comment]
OK I'm keeping the filtering and trying to address the various use cases: 

Case 1: Your initial search returned nothing:

![image](https://user-images.githubusercontent.com/4706307/51494967-ad31f180-1d88-11e9-8840-1665ac9738dd.png)

Case 2: Your search returned results, but not after filtering:

![image](https://user-images.githubusercontent.com/4706307/51495027-db173600-1d88-11e9-9136-a49961726744.png)

Case 3: You set the filter previously. Now you typed another search and nothing came back:

![image](https://user-images.githubusercontent.com/4706307/51495069-08fc7a80-1d89-11e9-97cd-e657dce53695.png)
