### ISSUE TITLE
Expand-collapse results in incorrect rendering

### ISSUE THREAD

**Issue by ugurdogrusoz** [PathwayCommons/app-ui#1280]
## Environment info
Browser version (client) : latest Chrome on Windows 10

## Current (buggy) behaviour
When you collapse and expand complexes, you get incorrectly drawn edges/nodes.

## Minimum steps to reproduce
- http://apps.pathwaycommons.org/pathways?uri=http%3A%2F%2Fidentifiers.org%2Fwikipathways%2FWP254
- click Expand/Collapse twice
- you get the following:
![image](https://user-images.githubusercontent.com/3874988/51657112-86580300-1fb4-11e9-8802-3138cd5d56d3.png)

**Comment by jvwong** [comment]
I believe this related to #1236 and should be addressed in #1265 which can be seen: http://appsbeta.pathwaycommons.org/pathways?uri=http%3A%2F%2Fidentifiers.org%2Fwikipathways%2FWP254.
