### ISSUE TITLE
Remove CSSnext @apply dependency

### ISSUE THREAD

**Issue by jonahdlin** [PathwayCommons/app-ui#13]
This may lose support at any time so it should be replaced by just copying the styles to each element.

**Comment by d2fong** [comment]
@jonahdlin Max fixed this yesterday.  We are using css-extend now.  I think it is similar to apply, it just uses % instead of@.

https://github.com/PathwayCommons/app-ui/commit/f585d8a6b79b224bb5ebfaca45ba23eec8d9f48c

**Comment by d2fong** [comment]
css-extend styles not being applied.

**Comment by jonahdlin** [comment]
The styles can't be applied if declared in root for some reason. I'll look into a fix.
![screen shot 2017-10-25 at 11 38 45 am](https://user-images.githubusercontent.com/15696989/32008016-27a45392-b979-11e7-96c1-ab25121bddbb.png)
