### ISSUE TITLE
Paint - How to present 300 columns and 300 values for each gene

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#131]
Ruth's test data had 300 columns and therefore 300 values for each gene.

I am assuming that we don't want to display 300 columns which implies some sort of value folding/averaging.  

It might make sense to fold these columns into a control column and an experiment column.  

However, this means that each column needs to be associated with one of experiment/column, and it probably needs to come from the Enrichment Map.

**Comment by jvwong** [comment]
The software that analyzes the raw data to find enriched genes called GSEA has, as input, a ['phenotype' or 'class' file (.cls)](http://software.broadinstitute.org/cancer/software/gsea/wiki/index.php/Data_formats#CLS:_Categorical_.28e.g_tumor_vs_normal.29_class_file_format_.28.2A.cls.29). This .cls file essentially assigns each column in an [expression file](http://software.broadinstitute.org/cancer/software/gsea/wiki/index.php/Data_formats#TXT:_Text_file_format_for_expression_dataset_.28.2A.txt.29) to a class (typically 2 classes).

In Cytoscape Enrichment Map, users can load in this .cls file:

![screenshot at nov 02 22-47-26](https://user-images.githubusercontent.com/4706307/32359250-fb8f28ee-c022-11e7-9ee9-88d945a8476a.png)

The result is that in each heat map for a gene set,  the samples are color coded according to phenotype:

![screenshot at nov 02 23-07-46 2](https://user-images.githubusercontent.com/4706307/32359278-55be7162-c023-11e7-8d46-84c79f356e99.png)

This .cls data should be available in Cytoscape (Mike)?...

**Comment by d2fong** [comment]
Do these classes have labels or is it just class = 1 / class = 2?

**Comment by d2fong** [comment]
Do classes have both an id and a label or is it only one or the other?

**Comment by d2fong** [comment]
Ok.
