### ISSUE TITLE
App bar title text: Missing mentions of gene(s)   

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#1335]
## Current (buggy) behaviour

When launching the interactions or enrichment apps, the genes reported in title bar do not match those in the original query. Some are missing.

## Desired behaviour

Should report all the gene names/sources.

## Minimum steps to reproduce

Search for 5 genes [pcna xrcc2 xrcc3 rad50 rad51](http://apps.pathwaycommons.org/search?q=pcna%20xrcc2%20xrcc3%20rad50%20rad51&type=Pathway)

View either app toolbar, has only `pcna xrcc2 rad50 rad51`

**Comment by maxkfranz** [comment]
It's probably just an off-by-one for the index.
