### ISSUE TITLE
Search for valid HGNC symbol comes back empty,  no gene panel 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#1346]
## Current (buggy) behaviour

In case of entering a valid HGNC symbol, no information is returned, in particular, the token is not recognized as a gene.

## Desired behaviour

Should at least display information about the gene and app panels.

## Minimum steps to reproduce

- Enter `MALAT1` into search

**Comment by gbader** [comment]
MALAT1 is not a protein coding gene - it is a lncRNA - maybe that is why?

**Comment by jvwong** [comment]
Yes - Our service attempts to get a UniProt accession for the client to display. Its likely that if that query to UniProt 'fails' the whole response comes back empty. .

**Comment by maxkfranz** [comment]
I noticed Uniprot being kind of slow today, so another possibility is that the query just timed out.

**Comment by jvwong** [comment]
It seems the problem lies with g:Convert.

1. The current g:Convert endpoint we are using `https://biit.cs.ut.ee/gprofiler/gconvert.cgi` does NOT return information for `MALAT1` from 'target' database `ENTREZGENE`  
2. The new endpoint `https://biit.cs.ut.ee/gprofiler/api/convert/convert` does return correct information from  'target' database `ENTREZGENE` for `MALAT1`

The reason I didn't immediately switch over to the new endpoint is detailed in #1327.

**Comment by gbader** [comment]
Could we follow up with the g:Profiler team?

**Comment by jvwong** [comment]
Support says, the endpoint that app-ui is currently using points to an archive (r1760_e93_eg40) that isn't up-to-date and won't be updated.

> So we suggest to move to the new API that relies (and will rely) on the newest data sources.
