### ISSUE TITLE
A bug or wrong description?

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/app-ui#1365]
https://github.com/PathwayCommons/app-ui/blob/d71810e4da42ae7db7057f00416c99da51d9f722/src/server/routes/search/search.js#L106

@maxkfranz @jvwong 
If 'query' parameter is a raw query String, how it can be used then as query.q inside the function?
I bet it's just a misleading comment - should be:
```
* @param query the query object
* @param {String} query.q raw query string
```

**Comment by jvwong** [comment]
yeah that's right.

**Comment by maxkfranz** [comment]
`query` is the object from express, which contains all query parameters in the http request.
