### ISSUE TITLE
Why we replaced org/reactome/ an alike with org/name/ in many files?

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/app-ui#1367]
@jvwong did you in February accidentally find/replaced all the identifiers.org strings and some JSON fields in the test sources with "name" or like :

```
 "name": [
               "http://identifiers.org/name/20817677",
```

I don't understand... This does not seem necessary, not related to the new Xref suggester web service at biopax.baderlab.org... or did I miss/forget everything?

**Comment by jvwong** [comment]
Those are only in mocked out test files.
