### ISSUE TITLE
Funny search and results (matches all?)

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/app-ui#1368]
![image](https://user-images.githubusercontent.com/991169/59568111-369dd500-9044-11e9-8145-6c1ef846bdd8.png)

The issue could be fixed in this app, but likely should also be addressed on PC2's (cPath2 s/w) side.

**Comment by jvwong** [comment]
We chose not to do any processing in the app for pathways. Doesn't lucene do stopwords etc?

**Comment by maxkfranz** [comment]
Though it would be nice to fix, no user would type that.

**Comment by IgorRodchenkov** [comment]
They do type that.

**Comment by IgorRodchenkov** [comment]
Ok, as you wish - won’t fix.
