### ISSUE TITLE
Automate creation/update of generic-physical-entity-map.json

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#1373]
Automate the update of `generic-physical-entity-map.json` using a node module. The implementation is currently a bash script in `src/scripts/generic-entity-mapping/update.sh`

Refs https://github.com/PathwayCommons/app-ui/pull/1371

**Comment by jvwong** [comment]
> Seeing if there is a simple way to add a webhook in the cPATH2 remote to trigger rebuild of app-ui image in DockerHub upon new cPATH2 release.
See #1372 

Should also run the app via Docker(-compose) in production.

**Comment by IgorRodchenkov** [comment]
I think we'd make one Docker Compose stack for all core PC apps: cpath2 (PC2 db/service), PCViz, app-ui, sifgraph-server and build/run it both for test/beta and production. This is feasible, despite tons of data, if we separate building PC data  (i.e, prepare, generate PC v12 db, Lucene index, upload data archives to the PC archives site, etc., which takes several days) from building the cPath2/PC2 Docker image (which would include wget/curl commands to download previously prepared data and index from pathwaycommons.og/archives to the Docker image...)

**Comment by jvwong** [comment]
Will be putting several bite-size PRs out of a working branch:

1.  `enrichment` module: pull in data before server start
2. `pathways` module: test updates
3. `pathways` module: pull in source data before server start
