### ISSUE TITLE
Add loading icon to downloads

### ISSUE THREAD

**Issue by jonahdlin** [PathwayCommons/app-ui#142]
PNG specifically. It takes a while to download and there is no visual indication that it's working until it's downloaded

**Comment by maxkfranz** [comment]
There's a loading icon in base.css

**Comment by d2fong** [comment]
I also use react-loader for the search feature.  You could use that but maybe the loading icon is sufficient.

**Comment by jonahdlin** [comment]
My next PR has it implemented with react-loader already. It can be switched over to the base.css one if necessary.

**Comment by maxkfranz** [comment]
react-loader is good

**Comment by jonahdlin** [comment]
Done in #155
