### ISSUE TITLE
Find an alternate way to display extra metadata. 

### ISSUE THREAD

**Issue by hmtinc** [PathwayCommons/app-ui#151]
Extra metadata is currently displayed when the user clicks show in sidebar. Gary mentioned that this could be problematic, as there is potential for relevant data to be duplicated. 

It would be great if there would only be one location to display extra data.

**Comment by hmtinc** [comment]
@gbader @jvwong 

Instead of a sidebar, how about a expandable tooltip? 

![3o6fj7yaopiqgieey4](https://user-images.githubusercontent.com/1313810/32554760-d4aadc7e-c468-11e7-8c74-0df55aed3592.gif)

**Comment by jvwong** [comment]
Yes the 'see more' option is pretty intuitive these days.

**Comment by maxkfranz** [comment]
Or you could show the important info at the top and just let the user scroll if they want to see more

**Comment by hmtinc** [comment]
@maxkfranz The main issue is that some important fields such as 'Synonyms' can have multiple entries which could require the user to scroll to view important details as well. 

Currently, the minimized view trims the data. With the show more button, all the data is displayed and nothing is trimmed. So, there is a possibility that important information could be pushed out of view due to another important field having too many entries.
