### ISSUE TITLE
Spinner code should not go in the cytoscapeJson module

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#16]
See : https://github.com/PathwayCommons/app-ui/blob/master/src/server/graph-generation/cytoscapeJson.js

E.g. This function, as are all functions in the file, is a service:

https://github.com/PathwayCommons/app-ui/blob/202e7685e41ae43f7150e36dd4b3f13b5c622f24/src/server/graph-generation/cytoscapeJson.js#L76-L95

It should not have UI-related things in service code.  That should be higher-up in the code that calls it (e.g. the batch load code).

**Comment by hmtinc** [comment]
Removed in PR #42
