### ISSUE TITLE
Reconsider usefulness of help menu

### ISSUE THREAD

**Issue by jonahdlin** [PathwayCommons/app-ui#161]
@gbader pointed out that there may be no need for the help menu. It's definitely important to have some guide somewhere, but after a user knows how to use the view there is little reason for it to be there except for quick reference. It may help to leave it around for now and track clicks on it with a Google Analytics event.

**Comment by jonahdlin** [comment]
Another thing to consider is whether or not to get rid of the sidebar entirely. It was originally useful because it can be opened and closed (or resized? #132) while not obscuring the view, like the old modals did, allowing the user to see node metadata side-by-side with the network. But with metadata being included entirely in tooltips, maybe we should relocate the other sidebar items. Just a thought.

**Comment by jvwong** [comment]
I could be open to dropping the 'help', but I'll caution everyone that SBGN-PD is a completely foreign concept to 99% of biologists. 'What is the square box?'

I suppose that we could move the remaining tabs. What is the alternative? Up to the toolbar? Wouldn't this essentially recapitulate the sidebar, just changing the orientation?

**Comment by jonahdlin** [comment]
Perhaps the help menu could be repurposed mainly to be a guide to SBGN, that users could keep open in the sidebar until they're comfortable with the notation? Essentially a verticalization of 
![image](https://user-images.githubusercontent.com/15696989/32906641-80c685f4-cacb-11e7-952c-807f7926d844.png)

**Comment by jonahdlin** [comment]
Then below that, there could be other view-related tips, on layouts, node search and/or tooltips.

**Comment by jvwong** [comment]
Logging the discussion we had about moving the sidebar tab buttons to the top; integrating the info tab into the title and removing from sidebar.

**Comment by jvwong** [comment]
Remove help.
