### ISSUE TITLE
Consider setting png scale value lower

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#162]
e.g

http://beta.pathwaycommons.org/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-6803211

Setting scale from 5 to 3 cuts image size roughly in half 1.9mb to 900kb.  Probably improves responsiveness because it is faster to download to.

The tradeoff is what quality level do we want the image to be at.

**Comment by jonahdlin** [comment]
How about letting the user choose? A simple slider with a few options for quality?

**Comment by d2fong** [comment]
https://github.com/PathwayCommons/app-ui/blob/master/src/client/features/view/components/sidebar/menus/components/downloadOption.js#L39

@jvwong do you think people need really high quality pngs or do moderate quality pics make sense?

**Comment by d2fong** [comment]
![tp53 regulates transcription of death receptors and ligands 1](https://user-images.githubusercontent.com/2328291/32673958-259ab9b2-c61f-11e7-8cbe-0be781813b02.png)
![tp53 regulates transcription of death receptors and ligands](https://user-images.githubusercontent.com/2328291/32673959-25a74894-c61f-11e7-8353-daa5025eed8e.png)

**Comment by d2fong** [comment]
scale quality 3 at the top, scale quality 5 at the bottom.

**Comment by d2fong** [comment]
In my opinion I don't notice any difference at all.

**Comment by d2fong** [comment]
You can click them both to see that the large one allows you to zoom in much further but I don't think that is useful.

**Comment by d2fong** [comment]
Also slightly unrelated but scale: 2 produces a blank image.

**Comment by maxkfranz** [comment]
Try embedding the images into a document, like you would have a figure in a paper.  Does the image look clearer with one version?  How do they look when printed?

That's the main usecase for exporting the image.

**Comment by d2fong** [comment]
Max width/height values need to be set too along with scale to have consistent sizing among images
- needs to be tested with each browser

**Comment by jvwong** [comment]
I would suspect the major use case is popping this in a powerpoint or word/google doc so low zoom conditions are target.
