### ISSUE TITLE
view/components/graph/index.js

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#165]
Delete this and use lodash isEmpty.
https://lodash.com/docs/4.17.4#isEmpty

https://github.com/PathwayCommons/app-ui/blob/master/src/client/features/view/components/graph/index.js#L39-L46

**Comment by d2fong** [comment]
Explain the motivation for using refs in view/components/graph/index.js and common/dropdown/index.js

**Comment by jonahdlin** [comment]
I'm using refs in graph/index.js to dynamically set the container in the cy object without worrying about getting it by ID or by classname.

In dropdown it's a little sketchier. I want to refer to the parent container of the list of items that drop down so I can know when one has been clicked. I'm currently doing this by checking if the clicked item is a direct descendant of the parent (which has the ref). I want to make the dropdown as similar as possible to the standard `select` and `option` model, and I'm not sure how to cleanly transfer information between components.
