### ISSUE TITLE
IP of RethinkDB 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#174]
The default database ip is harcoded in [config.js](https://github.com/PathwayCommons/app-ui/blob/aa079f4636f7a4b69a3b28bf6b66f39c95d4f832/src/server/database/config.js#L6)

```js
...
let defaults = {
  databaseName:  'metadataTestMk2',
  ip:  '192.168.81.233',
  tables:  ['version', 'graph', 'layout'],
  port: '28015'
};
...
```  

This default should be loopback. Ideally it should set based on the value in NODE_ENV.

**Comment by gaelder** [comment]
@jvwong It is based on the NODE_ENV (see line 13 of this file). Also, my hotfix changes I just made changed the defaul ip to 127.0.0.1 so I am going to close this issue.
