### ISSUE TITLE
Tooltip does not work in Firefox Quantum 

### ISSUE THREAD

**Issue by hmtinc** [PathwayCommons/app-ui#176]
The metadata tooltip is not displayed when the right click event is triggered in the latest version of Firefox. 

Right clicking properly triggers the tooltip generation function, but does not result in a visible tooltip being displayed.

**Comment by hmtinc** [comment]
It seems that in Firefox 56 the tool-tip is displayed, but immediately disappear.

This seems to be caused by the fact that tool-tips are meant to disappear when any other event is triggered (i.e click outside the tool-tip). The right click event in Firefox 56, seems to trigger multiple events causing the tool-tip to appear and immediately    tooltip.show(tooltip.store[0].popper); disappear

**Comment by maxkfranz** [comment]
You can test this issue with Firefox dev edition: https://www.mozilla.org/en-US/firefox/developer/

It includes beta-type commits (like Chrome canary).  If it works OK in dev edition, then it's a bug in Firefox 56 and will be soon resolved without our intervention.

**Comment by hmtinc** [comment]
@maxkfranz  Doesn't seem to work in the developer version. I tried the previous version of firefox as well, and it doesn't work either. 

So, this seems more like an issue with the way the tooltip works instead. Not sure what could be causing the tooltip to immediately disappear though.

**Comment by maxkfranz** [comment]
If you're handling events yourself, you may need to set the tippy to manual events mode.
