### ISSUE TITLE
Entry page visual overhaul

### ISSUE THREAD

**Issue by jonahdlin** [PathwayCommons/app-ui#178]
Entry page should:

1. Indicate Pathway Commons
2. Indicate app function
3. Example search queries
4. Describe search contents

Inspiration : https://www.ebi.ac.uk/QuickGO/

**Comment by d2fong** [comment]
Based on initial feedback it seems that people want it changed to look like a hybrid of your inspiration page and the previous search page:
![screen shot 2017-11-16 at 12 17 27 pm](https://user-images.githubusercontent.com/2328291/32905507-2639f70e-cac8-11e7-8dec-a136f4b9104a.png)
