### ISSUE TITLE
Publication info via ID

### ISSUE THREAD

**Issue by jonahdlin** [PathwayCommons/app-ui#180]
Using BioPAX metadata, we can get the title and abstract for publications from this service that allows you to fetch publication info via ID (https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&retmode=xml&rettype=abstract&id=), for nodes or for whole pathways. Would be neat to include abstracts and titles of publications somewhere in the view.

**Comment by hmtinc** [comment]
@jvwong  Is PubMed the only source for publications?

**Comment by jvwong** [comment]
From the BioPAX spec: "PublicationXref....Comment: Publication xrefs should make use of PubMed IDs wherever possible. The db property of an xref to an entry in PubMed should use the string “PubMed” and not “MEDLINE”."

If it wasn't indexed by Pubmed I wouldn't cite it.

**Comment by hmtinc** [comment]
@jvwong @jonahdlin 
So, I have implemented basic parsing functionality for database id's into the Metadata Mapper. The graph-generation module will now cache the title of publications and authors of publications. 

Is there any other fields that might be needed for publications?
