### ISSUE TITLE
Expand-collapse behaviour 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#193]

**Comment by ugurdogrusoz** [comment]
If expand-collapse extension is used properly, nodes around the expanded node is pushed away before the node is expanded followed by an incremental layout to "polish" the layout. Similarly, after collapse, an incremental layout is performed to get rid of unnecessary space around a collapsed (now smaller node). Please see [here](https://rawgit.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/master/demo-undoable.html). 
After both operations, application of an incremental layout should not result in nodes overlapping. However, with the current implementation, both operations do result in overlaps and non-uniform distribution of layout. As you perform multiple expand-collapses, layout gets worse and worse.
