### ISSUE TITLE
Upgrade cose-bilkent (3.0.2)

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#194]

**Comment by ugurdogrusoz** [comment]
Version 3 is much faster due to several different optimizations including algorithmic ones.

**Comment by jvwong** [comment]
Duplicated in #215

**Comment by ugurdogrusoz** [comment]
I think you guys should update to this version since @maxkfranz identified and helped us fix some important issues:
https://github.com/cytoscape/cytoscape.js-cose-bilkent/releases/tag/v4.0.0
