### ISSUE TITLE
Help Information on Search Results Page

### ISSUE THREAD

**Issue by cannin** [PathwayCommons/app-ui#199]
I searched for glycolysis. There was one result under Molecular Interactions and it didn't seem to point to a glycolysis pathway. Not sure what I should expect to appear for anything, but Pathways. Can some help information be added?

**Comment by jvwong** [comment]
Maybe instead drop the filtering for `numParticipants` to >= 1?

e.g. http://beta.pathwaycommons.org/search?gt=1&lt=250&q=glycolysis&type=MolecularInteraction

**Comment by jvwong** [comment]
This is better addressed by #296
