### ISSUE TITLE
Don't include `.js` in `require()`s

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#20]
E.g. 

https://github.com/PathwayCommons/app-ui/blob/202e7685e41ae43f7150e36dd4b3f13b5c622f24/src/server/graph-generation/cytoscapeJson.js#L3

Should be

```js
const fileDownloader = require('./fileDownloader');
```

**Comment by jonahdlin** [comment]
There's no more remaining instances of this.
