### ISSUE TITLE
Sort (or Specify) Search Results by Database

### ISSUE THREAD

**Issue by cannin** [PathwayCommons/app-ui#200]
Can you specify give me Glycolysis from Reactome? Or in the Search results can the results be filtered/sorted by database? Low priority if others do not see value in this.

**Comment by d2fong** [comment]
In the search page:
1. Click the 'Tools' button under the search bar icon.  A drop down should right before the first search result
2. Click on the dropdown
3. Click whatever data source you want.

**Comment by cannin** [comment]
Thanks. Found it. Actually clicked on it before and didn't notice the change on the page. Why not just put that functionality always on the page floated to the right of where it shows up now (covering the results count)?
