### ISSUE TITLE
The favicon has a light border around it

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/app-ui#204]
<img width="230" alt="screen shot 2017-11-17 at 1 19 45 pm" src="https://user-images.githubusercontent.com/989043/32962322-05b12480-cb9a-11e7-88b5-8a74d1296b83.png">

**Comment by jvwong** [comment]
Probably want one of these: https://github.com/PathwayCommons/about/tree/master/images/brand

**Comment by maxkfranz** [comment]
This one is good: https://github.com/PathwayCommons/about/blob/master/images/brand/pc_logo_background.svg

The bg makes it so if the browser tabs are dark you can still see the logo
