### ISSUE TITLE
Use ES6 implicit values where the object keys match the variable name

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#21]
E.g. 

https://github.com/PathwayCommons/app-ui/blob/202e7685e41ae43f7150e36dd4b3f13b5c622f24/src/server/graph-generation/cytoscapeJson.js#L36-L42

Where you do `{ foo: foo }`, you can just type `{ foo }`.  It makes it easier to read.

**Comment by jonahdlin** [comment]
Last of this issue resolved in #60
