### ISSUE TITLE
View - Node Event binding changes

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#215]
1.  set every complex node to be expanded by default
2. bind the double click gesture/event to collapse
3. bind the single click gesture to open a tooltip for a node 
    - don't make a tooltip appear when someone clicks and drags a node 
    - probably needs more fine tuned event management

**Comment by d2fong** [comment]
Add button for expand/collapse all

**Comment by d2fong** [comment]
upgrade cose-bilkent 3.0.2

**Comment by d2fong** [comment]
also remove node restriction from the layout picker i.e always default to cose-bilkent regardless of network size.
https://github.com/PathwayCommons/app-ui/blob/8fac76f97fd797ac5cb292169ca777772b3146dd/src/client/common/cy/layout/index.js#L28

https://github.com/PathwayCommons/app-ui/blob/8fac76f97fd797ac5cb292169ca777772b3146dd/src/client/common/cy/layout/index.js#L42

**Comment by jvwong** [comment]
Closing related issue #79.

**Comment by jvwong** [comment]
'upgrade cose-bilkent 3.0.2' duplicate of #194
