### ISSUE TITLE
Nodes have a dark grey background after being unmatched when searching in the view

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#230]
![screen shot 2017-11-21 at 6 27 06 pm](https://user-images.githubusercontent.com/2328291/33102211-b53287e4-cee9-11e7-8ae3-6b4f384a64b2.png)

**Comment by d2fong** [comment]
https://github.com/PathwayCommons/app-ui/blob/development/src/client/common/cy/stylesheet.js#L27

This code block is suspicious, try deleting this and seeing if it makes a difference.

Also I suspect that this might not be entirely related to the node search, it might be due to other events.

**Comment by d2fong** [comment]
I just pushed a commit that deleted a bunch of event stuff I think that was the cause can you verify that it has changed on your computer after running git pull and testing it here:
http://localhost:3000/view?uri=http%3A%2F%2Fidentifiers.org%2Fpanther.pathway%2FP04397

**Comment by hmtinc** [comment]
@d2fong I can verify that it seems that the colour does not change anymore.

**Comment by d2fong** [comment]
Okay great thanks for verifying it.

**Comment by d2fong** [comment]
I think I am running into a issue related to the double click events

Steps to reproduce:
- double click complex node, double click it again
- it stays permanently selected
