### ISSUE TITLE
cose-bilkent 3.0.2 options tuning

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#233]
Before 3.0.2:
![tp53 regulates transcription of caspase activators and caspases](https://user-images.githubusercontent.com/2328291/33137925-3812a080-cf77-11e7-91a6-470b1fe4dd80.png)

3.0.2:

![screen shot 2017-11-22 at 11 29 36 am](https://user-images.githubusercontent.com/2328291/33138422-74c198b4-cf78-11e7-9e4a-6a4c3bc9317e.png)

Notes:

- Bridge nodes seem to be aligned nicer in 3.0.2
- nodes seem to a bit too close in 3.0.2.  I think I notice some label overlap even though I set nodeDimensionsIncludeLabels to true
- there is a lot more empty space in compartments
![screen shot 2017-11-22 at 11 31 34 am](https://user-images.githubusercontent.com/2328291/33138524-b6017420-cf78-11e7-8164-fb8a25bfd43e.png)

**Comment by d2fong** [comment]
![tp53 regulates transcription of death receptors and ligands 4](https://user-images.githubusercontent.com/2328291/33140289-8710eb78-cf7d-11e7-893b-92b16eebdb64.png)
Heres another example

**Comment by d2fong** [comment]
Turning off complex labels makes it look better like Ugur suggested.  Now that we have tooltips that show node label it might make sense to just not show complex labels. 
![tp53 regulates transcription of death receptors and ligands 5](https://user-images.githubusercontent.com/2328291/33140617-830dbd98-cf7e-11e7-9bad-6cf7f767c0c2.png)

**Comment by d2fong** [comment]
Added benefit that cytoscape doesnt have to render as much text.  Complex labels were also somewhat redundant; in most cases I found that it just consisted of the child labels concatenated together.

**Comment by d2fong** [comment]
Sometimes you still get messes like this though:
![screen shot 2017-11-22 at 4 52 21 pm](https://user-images.githubusercontent.com/2328291/33151336-af831720-cfa5-11e7-9f53-a25d79a40a1c.png)

**Comment by d2fong** [comment]
This graph seems to not look that great independent of cose-bilkent version:

![screen shot 2017-11-22 at 5 02 09 pm](https://user-images.githubusercontent.com/2328291/33151670-01206f46-cfa7-11e7-95d4-a07ad15e6c8b.png)

**Comment by d2fong** [comment]
node repulsion set to 50000 seems to help

![screen shot 2017-11-23 at 5 23 40 pm](https://user-images.githubusercontent.com/2328291/33189675-213a9b2c-d073-11e7-8664-5ec19177957d.png)

**Comment by maxkfranz** [comment]
You may need to set some layout options to be variable, based on some graph metrics (e.g. number of nodes, number of edges, average degree).

**Comment by d2fong** [comment]
Yeah the example I posted is a larger graph. Smaller graphs probably don’t
need that much node repulsion

**Comment by d2fong** [comment]
todo:

- [ ] refactor common/cy/layout.js again to return a function for cose-bilkent that takes in some parameters such as num nodes, num edges, etc.  the possibilities are numerous, configure cose-bilkent to use those parameters.  e.g num nodes -> set node repulsion to 5000* num nodes
