### ISSUE TITLE
tagging layouts to distinguish between human created and alogrithmic

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#247]
Is it possible when submitting a layout to the server to 'tag' it with a category.  

use case:
- someone runs any algorithmic layout in /edit for any ```uri```
- when it is submitted to the server, it is tagged 'algorithm' or something that denotes that it was computed by an algorithm
- when someone loads that same ```uri```, query the db for all layouts for that uri that have a tag name of algorithm, or get the latest algorithm layout

Another idea is adding query params to layout requests:

e.g /getLayout&uri=...&name=Force Directed

**Comment by gbader** [comment]
This may be good because we may want to import manually created layouts from multiple sources e.g. Reactome, KEGG.
