### ISSUE TITLE
Application browser compatibility

### ISSUE THREAD

**Issue by jonahdlin** [PathwayCommons/app-ui#249]
The menu bar works as intended in Chrome, but in Firefox, the padding on the node search box is broken, and in Safari the whole toolbar is centered under the top bar, where it should be left aligned, like in Chrome.

**Comment by hmtinc** [comment]
The entire app-ui revision has been developed with Chrome in mind, we should test the revised app-ui in the other major browsers.

**Comment by hmtinc** [comment]
Safari still has styling issues. The menu bar icons are center aligned instead of being left aligned. 
![screen shot 2017-12-07 at 8 14 39 am](https://user-images.githubusercontent.com/1313810/33717141-d7d8a6d6-db26-11e7-9e34-ac85f60edef0.png)
