### ISSUE TITLE
Reusable react components

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#250]
Factor out common components
- need define reasonable interfaces
- might need to modify css

**Comment by jonahdlin** [comment]
Modules to make common and reusable:

- [ ] Text button like the one in the downloads menu, with option for icon on left or right
- [ ] Asynchronous button with a built in loader, to be used for toggling asynchronous processes
- [ ] Search bars, both
  - [ ] Big, like the one in search and
  - [ ] Small, like the node search box
- [ ] Icon button, like in the view toolbar and the sidebar close button
- [ ] Drawer component, i.e. the sidebar
- [ ] Dropdown component should be tweaked a little
- [ ] Tooltip component to wrap tippy.js for regular tooltips (**not** the graph tooltips)
- [ ] Informational bar, like the menu bar in view

**Comment by d2fong** [comment]
@jonahdlin can you do some research on how other people create reusable components and link some articles / your findings in this issue if you find any.

**Comment by jonahdlin** [comment]
## Articles
I found an article on [high and low level react components](https://medium.com/the-ideal-system/react-meta-ui-components-23839fdcd8d9), which had some links to two other useful articles, one on [presentational vs. container components](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0) and one on [atomic web design](http://bradfrost.com/blog/post/atomic-web-design/). Here's another article with a better [example on presentational vs. container components](http://krasimirtsonev.com/blog/article/react-js-presentational-container-components).

## Findings
### Overall Idea
From reading these and talking to developers I would say the main takeaway is that a reusable React component is

1. Simple
    - It has a specific function in mind and does it well
    - It's customizable only within it's intended function
    - For example, a standard button component should perform a user-specified function on click and contain user-specified text, and could possibly be further customized, but strictly optionally
2. Customizable
    - It's flexible, within reason, to suit a user's need for it
    - If some part of the component may change in some use cases, make it an optional prop with a sane default
    - It's not so customizable that it forces the user to specify every little detail about it, although specific customizability could be offered to the user optionally
    - For example, a button component could offer the user the ability to change its colour, but it should then have a default colour so the user isn't forced to care about the colour
3. Pure
    - It doesn't depend on any global application state
    - Because it isn't tied to any one part of the application for its functionality, it can be easily picked up and plugged in where needed

### Containers vs. Presentational Components
React components can be divided into two categories, **containers** and **presentational**. 

**Presentational** components 

- Are concerned with how things look, i.e. present their props in a certain way
- Don't mutate or load data
- Don't have their own state unless it's a specifically UI related state (and so can often be written functionally) 
- Are styled

**Container** components

- Are concerned with how things work, i.e. load and mutate data, and make use of presentational components for displaying that data
- Often have their own state
- Are not styled
- Often are wrapped in functions that accept presentational components as parameters

There is no rule saying that a presentational can't contain both containers and other presentational components and vice versa.

#### Example
An abbreviated version of an example from one of the articles. Say we want a `Clock` component that takes in an initial time as a JavaScript `Date()`, and counts from that time up.

It would be good design to have

1. A **presentational** component `DigitalClock`
    - Takes in seconds, minutes and hours as props and displays them
2. A **container** component `ClockContainer`
    - Accepts a `Date()` as props, stores it in its state and increments it every second
    - Uses `DigitalClock` to display the time
    - Takes in `DigitalClock` (or some other presentational clock component) as a parameter

In the end you'd end up with something like
```js
module.exports = Clock => {
  return class ClockContainer extends React.Component {
    constructor(props){
      // state control
    }
    // other logic
    render() {
      return h(Clock, {seconds: x, minutes: y, hours: z});
    }
  }
}
```
And it's used by the app with `ClockContainer(DigitalClock)`. This way the digital clock can be reused anywhere for displaying a time, and doesn't need to interpret the `Date()` object. The `ClockContainer` is easily customizable to use a different presentational component, say an analog clock.

### Atomic Design
An app should be built up from elementary pieces, like how an atom builds a molecule, builds an organism. In atomic design, **atoms** are base level presentational components like inputs, buttons, titles, etc. From atoms, build **molecules**, relatively simply combinations of those base components like a labeled search field with a button. From molecules, build **organisms**, complex and distinct sections of the interface, like a menu bar or a page footer. From these, build a container component, a **template** for the page. The final product, the **page**, is an instance of the template that's populated with information.

**Comment by jonahdlin** [comment]
@d2fong, @maxkfranz I wrote this mainly for myself as a guide for refactoring. Can you quickly skim it to make sure I didn't glaringly misinterpret something?

**Comment by d2fong** [comment]
Hey Jonah.  Yes this is a great start, thanks for taking the time to put this together.

Based on the discussions Max and I had yesterday, we think the three most important components  would be the:
- dropdown component
- non-graph tippy component
- a reusable base view template that encompasses all of the stuff common to view/paint/admin functionality, while also allowing the view/paint/admin to inject their differences (possibly hyperscript elements, functions, etc) via props. 

The first two components should be reasonably straight forward and useful.  The view template component would involve more work but probably also be the most useful.

You are welcome to work on any of them as you want, if you want to work on the view template, come talk to me.  You might also want to talk to Max and I at the same time on Tuesday for the template component.

**Comment by jonahdlin** [comment]
Okay, great. I think I'll start with the dropdown and tippy components, since I've meant to do those for a while. I'll start on the view component on Monday or later today, but I'll discuss it with one or both of you guys before starting it.
