### ISSUE TITLE
Search App Feedback Round 2 

### ISSUE THREAD

**Issue by hmtinc** [PathwayCommons/app-ui#260]
@jvwong @gbader 
Search Page 
- [x] Consider adding a splash page to describe the purpose of the page
- [x] Remove ethanol from the examples list
- [x] Remove tabs bar 
- [ ] Better search results information display (datasource image is redundant, datasource name is redundant, no one cares about them,  see BioGrid for better example of search results)

Tooltip 
- [x] Remove type field from tooltip, but keep the type name
- [x] Change approved name to name
- [x] Change Database References to links
- [x] Fix positioning to be on the button
- [x] Assign a max height to tooltip
- [x] Reduce size of the button 
- [x] Style button to match new ui
- [x] Consider replacing the expand button with plain text 
- [x] Consider adding a dynamic expand button
- [x] Consider adding additional info button to each field in the tooltip

Menu
- [x] Change ‘Rearrange Entities’ to ‘Arrange Display’
- [x] Update display descriptions to be more descriptive
- [x] Make smart recommendations on the correct layout.
- [x] Make layouts option available in edit mode only
- [x] Add a reset button to the menu bar with the default being human created layouts

**Comment by jvwong** [comment]
Search Page
- [ ] Hide all tabs (display pathways only)  

Tooltip
- Type value can be presented as 'tag' or using alternative font
- Remove any alphanumeric IDs from 'Links'

Menu
- Layout alternatives: 'Reset display'

**Comment by maxkfranz** [comment]
@hmtinc @jonahdlin @gaelder Would you please create separate issues for each of the tick boxes?  Each point should have its own issue, PR, etc.  It's probably easiest to just create each issue when you start working on it or need to discuss it.  Thanks
