### ISSUE TITLE
CoSE-Bilkent Production Bug

### ISSUE THREAD

**Issue by jonahdlin** [PathwayCommons/app-ui#264]
That bug that @maxkfranz and @d2fong fixed seems to have come back on pathways like

http://beta.pathwaycommons.org/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-389948
http://beta.pathwaycommons.org/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-6804756

**Comment by d2fong** [comment]
Do you know if the dependency is still 3.0.3 or 3.0.2?

**Comment by jonahdlin** [comment]
It doesn't have a version, but links to git+https://github.com/d2fong/cytoscape.js-cose-bilkent#simple-label-dimensions

**Comment by jonahdlin** [comment]
It's `^3.0.2` in the package.json.

**Comment by jonahdlin** [comment]
On Jenkins 3.0.4 was installed.

**Comment by jonahdlin** [comment]
Should I just change it to the exact version 3.0.2 in the package.json?

**Comment by maxkfranz** [comment]
This is a separate issue, which looks to be caused by incorrect minification.  You should not be using a beta minifier.  It operates on your sourcecode, like a compiler.  When you use unstable software that operates on your source code, you risk that what you put in prod is not what your code intends.

**Comment by maxkfranz** [comment]
![screen shot 2017-11-29 at 11 33 39 am](https://user-images.githubusercontent.com/989043/33386558-33e91cbe-d4f9-11e7-977d-d0a2cd791d23.png)

You can see that the code is clearly not minified properly:

https://github.com/cytoscape/cytoscape.js/blob/v3.2.6/src/math.js#L77-L98

**Comment by jonahdlin** [comment]
Right, I see that. Made those changes in new PR #265.
