### ISSUE TITLE
`server/database` files should not have `db` or `database` in the name

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#27]
They're in the `database` folder already.  It's pretty clear that they all should pertain to the db.

- [x] Remove "db" etc. from the filenames
- [ ] More descriptive/accurate names for what they pertain to (e.g. `buildDb.js` really just creates *tables*)
- [x] Test files should be Mocha tests in the `/test` dir

**Comment by gaelder** [comment]
The only part of this not completed is renaming batch scripts which has it's own issue #44. Closing this issue.
