### ISSUE TITLE
Paint - search tab

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#275]
- query returns 1 result -> display the result
- query returns > 1 result -> do something smart
- query returns 0 results -> gene search

**Comment by d2fong** [comment]
## Painter search cases

### Happy Case - given enrichment map node is a pathway in pathway commons
- if the title of the enrichment map node given in the enrichment uri has an exact match to a pathway in pathway commons with the exact same title, return that pathway

### Unhappy Case - given enrichment map node is not found exactly, but there are search results returned 
- if there is no exact match, then the search results should be ordered by the number of genes that appear in the result. 
- results that do not have any genes in common with the expression data (0 genes appear in the result) should be filtered
- the gene labels that appear in the result should also be discoverable by some sort of button/control

### Worst Case - given enrichment map node is not in pathway commons (does not match any pathway title exactly, and does not return _any_ search results when you query pathway commons
- perform a gene search in pathway commons

**Comment by d2fong** [comment]
### Gene Search Problems
- number of given genes may be up to 500
- current pc/querysearch  is really slow for gene queries more than 15-20

### Ideas
- let user pick and choose up to 15 genes to query

**Comment by jvwong** [comment]
Some food for thought.

### Baderlab GMT file

- GMT file: [Human_GOBP_AllPathways_no_GO_iea_January_03_2018_symbol.gmt](http://download.baderlab.org/EM_Genesets/current_release/Human/symbol/)
- Quantiles for gene set sizes

```
    25%     50%     75%     85%     90%     95%     99%    Min.    Max. 
   2.00    7.00   27.00   56.00   89.00  197.00 1080.94    0.0     14570.0 
```

### Baderlab GMT file

- GMT file: [PathwayCommons9.All.hgnc.gmt](http://www.pathwaycommons.org/archives/PC2/v9/)
- Quantiles for gene set sizes

```
    25%     50%     75%     85%     90%     95%     99%    Min.    Max.  
   2.00    7.00   27.00   56.00   89.00  197.00 1080.94    1.0     569.0  
```

### Distributions for sizes below 95% percentile

![image](https://user-images.githubusercontent.com/4706307/34623929-3a15631e-f221-11e7-8f42-69e5259d4ed9.png)

**Comment by d2fong** [comment]
## search results algorithm

When search results from pc returns no hits:
- given expression list with n expresssions, create  n / c queries where c is < 15 each query of the form: 'g0  g1  gC-1 gC'
- send to pathway commons
- populate search results as unique set of pc ids returned over all n / c queries

**Comment by d2fong** [comment]
Implemented as well as it could be for the initial version
