### ISSUE TITLE
Using HashRouter instead of BrowserRouter?

### ISSUE THREAD

**Issue by hmtinc** [PathwayCommons/app-ui#276]
@d2fong  @maxkfranz @IgorRodchenkov 

Igor wants to host the application in a virtual directory, so he is able to have multiple PC apps/services on one domain. i.e `http://pathwaycommons.org/apps/search' for search . 

This causes issues with BrowserRouter though, as the full path is used by the router to determine the correct page. i.e `/apps/search/view`  should be `/view`.  This issue can easily be mitigated by defining a **basename** `{ basename: '/apps/search' }`, but this would require a future user to change the **basename** if they want to deploy the site anywhere else (locally, another folder, or another server). 

Using HashRouter fixes this issue as it separates the actual server path from the react route with a hash (#), thus the app can be moved anywhere without having to define a base directory name.  

I know hashrouter typically shouldn't be used for a dynamic site and that it complicates the URL,  but it seems alot more ideal than having to go into the code and manually define the base directory whenever you want to host the application elsewhere. 

Given this, should we change BrowserRouter to HashRouter, or is there a more ideal solution?

**Comment by d2fong** [comment]
Yeah I think using a hash router makes it easier for Igor.  

You can definitely try to replace browser router with hash router but it might work a bit differently.  You might have to change the client side router code if it does behave differently.

**Comment by IgorRodchenkov** [comment]
Wait... it works now (with a special simple NGINX config; try 192...153/apps/ when Harsh's computer is on; we tried this yesterday) - I can now proxy the app-ui at any path, e.g., beta.pathwaycommons.org/apps/ (currently it's not configured), etc..

(I do not need to separate search, view, edit routs/apps under different parent path... )
So, what's the problem? ;)

**Comment by d2fong** [comment]
Oh, if it is fine with you Igor I guess it can be left as is..

**Comment by hmtinc** [comment]
@IgorRodchenkov @d2fong  It works off my local server because I defined the base directory in the code to get the example working. Defining a base directory isn't ideal though

@d2fong  Had to make some minor modifications to the API caller, but HashRouter works,

**Comment by d2fong** [comment]
Does the analytics component still get hit for each route?  to test, you could just console.log in the analytics component and visit the various routes in searc/view/edit/ etc.

**Comment by maxkfranz** [comment]
It's preferable to keep the `BrowserRouter`, I think.  Harold should be able to setup the Apache config so that something like `pathwaycommons.org/app-dir` points to `vmhostname:3000`.

If you're worried about the base name, you can allow it to be set by an environment variable.  Just read it from the config file and allow a value from [`process.env`](https://nodejs.org/dist/latest-v8.x/docs/api/process.html#process_process_env).  You probably want a default config value that makes sense for the root case (e.g. debug, local instances) so that only the prod server need to config the env var.
