### ISSUE TITLE
How to differentiate between a node who has an expression that falls in the mean range vs a node that doesn't have associated expression data in the pathway

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#277]
A node that has expression data in between the 25th and 75th percentile will have a white background. 

Nodes that don't have any associated expression data will also have a white background.  

Ideas: 
- differentiate by assigning a slightly different white/neutral colour.

**Comment by d2fong** [comment]
![screen shot 2017-12-01 at 4 51 28 pm](https://user-images.githubusercontent.com/2328291/33505171-54fc8f1a-d6b8-11e7-9861-b60afc2c2ea0.png)
e.g rpl19 has expression data but the currently selected value falls into the white range

**Comment by jvwong** [comment]
i was thinking node with no associated data should be marked as 'disabled' somehow - like darkish greyed out or something

**Comment by d2fong** [comment]
Could make the node background a shade of grey, make the node label again
dark grey or something like that.

**Comment by jvwong** [comment]
Yeah that should be made clear to the user - dunno if there are other examples out there of what they do.

**Comment by d2fong** [comment]
Applied disabled node style for nodes that do not have expression data:

![screen shot 2017-12-02 at 6 09 26 pm](https://user-images.githubusercontent.com/2328291/33520586-f6cae94e-d78b-11e7-9f4e-fca7ca3abf87.png)

This ticket can be reopened when we inevitably get feedback on whether this clearly describes nodes without expression data or not.

**Comment by d2fong** [comment]
It would be nice to sort these nodes by their value e.g low to high, disabled nodes all last, but cose-bilkent doesn't seem to support tiling options.
