### ISSUE TITLE
Paint - generalized paint

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#283]
use case, user wants to paint a few nodes without going through cytoscape

same table view as the current paint app, instead of expression data, each node in the cy.js graph has a row
- user clicks on the row to enter value, value is the painted onto the node
- configurable legend (min, max) to determine colour/opacity

**Comment by jvwong** [comment]
i had this tasked for a coop as well. maybe sketch it out like the search.

**Comment by d2fong** [comment]
Yeah thats the reason why I made this ticket; because you mentioned it.
