### ISSUE TITLE
Pathway Commons search service - prefix IDs

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#3]
Prefix with 'xrefid' field if the token matches an ID pattern ([here](https://github.com/PathwayCommons/app-ui/blob/f3ddb1735cb16033118d753a00f837237449e5fc/src/client/services/pathway-commons/search/index.js#L26)):
 
```js
const processPhrase = (phrase, collection) => {
  ...
      return tokenRecognized ? ('xrefid:' + luceneToken) : ( 'name:' + '*' + luceneToken + '*' );
  ...  
};
```

**Comment by d2fong** [comment]
4a2f8f92916f6fc0caa2038795c6c8fbbb9a2bce
