### ISSUE TITLE
Pathway view search - node matches do not contain text

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#327]
When I search for a node by a gene synonym, the tooltip text does not contain the text, although it is highlighting the correct nodes.

Example: search for 'p21' within 'CDKN1A - 

![screenshot at dec 11 12-25-09](https://user-images.githubusercontent.com/4706307/33844543-93512182-de6e-11e7-830e-1732fb5f43e4.png)

**Comment by hmtinc** [comment]
@jvwong The search function searches through Display Name, Synonyms, Approved Name, and Label for potential matches, but the tooltip only shows Approved Name and Synonyms . 

In the case of this pathway, p21 is actually not listed as a synonym, but instead as a display name. 

![screen shot 2017-12-11 at 12 39 07 pm](https://user-images.githubusercontent.com/1313810/33845231-c30389a4-de70-11e7-80de-7bee2eb8c00a.png)

I wasn't sure if the display name should be display in the tooltip as most of time it seemed to just be a duplicated of the label. This seems to be a case where it isn't. 

I'll just re-add display name to the tooltip.

**Comment by hmtinc** [comment]
@jvwong  #328 should resolve this issue.
