### ISSUE TITLE
Replace all uses of `async` with `bluebird`

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#33]
E.g. 

https://github.com/PathwayCommons/app-ui/blob/202e7685e41ae43f7150e36dd4b3f13b5c622f24/src/server/database/updateDatabase.js?utf8=%E2%9C%93#L74

The above won't work properly.  You're mixing promises with callbacks.  And your top-level `.catch()` won't work, because any problem in the `whilst` isn't promise-aware.

Use `bluebird`.  Remove all uses of `async`.

`async.whilst()` is analogous to `bluebird.map()`.

**Comment by jonahdlin** [comment]
Fixed in #58
