### ISSUE TITLE
svg images not being rendered on node bodies

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#333]
Could be from using latest cytoscape unstable build.

**Comment by d2fong** [comment]
Confirmed that the bug does not appear in 520c608 -- the commit before switching to unstable cytoscape.js

**Comment by d2fong** [comment]
https://github.com/PathwayCommons/app-ui/issues/319

**Comment by d2fong** [comment]
It probably didn't happen on Harsh/Geoff/Jonah(s) computers because they still had the old unstable build branch in their node modules.

**Comment by d2fong** [comment]
I have been able to reproduce this bug:

1.  Load any network in beta.pathwaycommons
2. Press the reset network button
3. All state/units of information disappear on nodes

**Comment by d2fong** [comment]
On beta.pathwaycommons, state/units of infos dont appear at all, regardless of whether a layout is run or not.

**Comment by d2fong** [comment]
Another bug locally:

zooming in and out periodically removes units of info/state variables

**Comment by d2fong** [comment]
For the bugs I am experiencing locally, it seems likely that this is a cytoscape.js issue.

**Comment by d2fong** [comment]
![screen shot 2017-12-14 at 2 31 14 pm](https://user-images.githubusercontent.com/2328291/34010660-8e0f8f8c-e0db-11e7-98de-b1e48c9fd03f.png)

**Comment by maxkfranz** [comment]
Resolved by https://github.com/cytoscape/cytoscape.js/commit/17b2a8df61ae06d088fc3b0ace17227717af1ea7
