### ISSUE TITLE
svg images still not being rendered properly

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#339]
![screen shot 2017-12-18 at 2 07 31 pm](https://user-images.githubusercontent.com/2328291/34123231-dd619106-e3fc-11e7-8c2e-f16b901f8d36.png)

**Comment by d2fong** [comment]
http://localhost:3000/view?uri=http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FPathway_eb9be568a2c75cb8fad9e5c47f250f20

**Comment by maxkfranz** [comment]
I'll look into this
