### ISSUE TITLE
Pathway view - Hide tooltip comments

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#360]

**Comment by logmosier** [comment]
@jvwong are you referring to these tooltips?
![screen shot 2018-01-11 at 3 28 34 pm](https://user-images.githubusercontent.com/10948303/34845821-3644e36e-f6e4-11e7-89e7-8038c056c2c0.png)

**Comment by jvwong** [comment]
I am referring to those associated with the network nodes.

![image](https://user-images.githubusercontent.com/4706307/34846353-e1e9f80c-f6e5-11e7-8dc4-28c2b322bc7b.png)

**Comment by jvwong** [comment]
Noting that in a minority of cases there is interesting information in comments...

e.g. [Cdc20:Phospho-APC/C mediated degradation of Cyclin A](http://beta.pathwaycommons.org/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-174184)

![image](https://user-images.githubusercontent.com/4706307/34892719-4f1fd8fc-f7a8-11e7-935f-9a58b4b02f4d.png)
