### ISSUE TITLE
view does not work for uris of the form :"http://pathwaycommons.org/pc2/Pathway/:id"

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#363]
I created a script to generate all pathway uris from the sbgn dump and I find for sample size n = 10 that none of these uris work for view in beta.pathwaycommons.org.  They also don't work in pathwaycommons.org/#/pathways.

The question is why do these uris have sbgn files but when you access these uris it says that these arent valid.
```
"http://pathwaycommons.org/pc2/Pathway/82fbb4665e5562d7ae2d68a76eb5893d", "http://pathwaycommons.org/pc2/Pathway/83074e50f2b1b4afc6b8f3d546f2ad0d", "http://pathwaycommons.org/pc2/Pathway/832e385f18972438172d7006f1a96627", "http://pathwaycommons.org/pc2/Pathway/834b855480240c5c2d3a75a7728776ce", "http://pathwaycommons.org/pc2/Pathway/8b83c203f28f88d8496b62b4720ddf9a", "http://pathwaycommons.org/pc2/Pathway/8bcc17414d3bc11e78c22d3fb8c06e7e", "http://pathwaycommons.org/pc2/Pathway/8be3dd208e07eec3239a956b54e580cf", "http://pathwaycommons.org/pc2/Pathway/8c0d307f1ca511257cad9d033777a3df", "http://pathwaycommons.org/pc2/Pathway/8c2600f1ffba5fb9fcd04003a6e7ad57", "http://pathwaycommons.org/pc2/Pathway/8c3c59d306d2c9c6cff6656be5d57bd6", "http://pathwaycommons.org/pc2/Pathway/8c88d1f0fc7bdb171943757120c25099", 
```

**Comment by IgorRodchenkov** [comment]
@d2fong  there are no such URIs as e.g., `http://pathwaycommons.org/pc2/Pathway/82fbb4665e5562d7ae2d68a76eb5893d` in PC2!

How/where did you get those?

PC2 in fact contains URIs like `http://pathwaycommons.org/pc2/Pathway_82fbb4665e5562d7ae2d68a76eb5893d` (- there is '_' after Pathway, nor '/'...)

**Comment by d2fong** [comment]
I guess I mistranslated the ids from the sbgn file archive.
