### ISSUE TITLE
Paint - Sidebar text and presentation

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#388]
### Tab "Expression Data"
- Table 
  - Header
    - label: Use "Expression ratio (Log2)" rather than "log2 Fold-Change"  
    - cells:  Somehow indicate that columns are clickable to sort (mini triangles?)
  - Body
    - Row ordering: Initially, this should default to decreasing expression 
    - Do not allow to scroll into extra, blank rows
    - Format numbers to have equal decimal places/aligned decimal point
    - Search box could have placeholder text like "Filter"
  
### Tab "Search Results"
  - Tab label: More meaningful label is "Select pathway"
  - List item
    - Hide gene list  
    - Matching genes: Goal here is enable user to decide on the closest match. I would want to know the count of genes in my query gene set (i.e. from Enrichment Map) that match a pathway search hit (e.g. 'X out of Y' where 'X' is the number of matches, 'Y' is the query gene set size).  Could be a stacked bar for percentage?

**Comment by d2fong** [comment]
Made most of these changes.  Higher fidelity visuals/ui elements will have to go into the next version of the paint app.

**Comment by jvwong** [comment]
Noting here the rationale for searching based on expressed genes. 

1. GSEA filters candidate gene sets by expression
2. Cytoscape sends expressed genes to app
