### ISSUE TITLE
Paint - it is confusing to have expressions mapped onto generic nodes

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#390]
![screen shot 2018-01-17 at 3 56 54 pm](https://user-images.githubusercontent.com/2328291/35066590-13c8afcc-fb9f-11e7-9bc3-1a71ccee71f8.png)

Users will see that JNK or MKK4/7 is coloured deep purple but the will be unable to find any of them in their expression data list.

**Comment by jvwong** [comment]
This seems to be an ongoing issue that could be addressed at the BioPAX-SBGN conversion.
From a user-standpoint, I doubt this is a huge problem - Most users would probably more concerned with the how the pathways relate to their disease or biological behaviour as a whole rather than individual genes. Are we showing what SBGN nodes / actual genes in menu bar as described in #357?

**Comment by d2fong** [comment]
Oh right I forgot to add generics to the menu

**Comment by d2fong** [comment]
expression list intersection in menu
-  cyJson nodes and the expressionList -> intersection(cyJson.nodes, expressionList) 
- intersection defined for a given node is whether the node label matches any expression gene name or if a node has any generics that map onto a gene expression name
- instead of displaying the expression list in the paint menu, display the intersection(cyJson.node, expressionList).  
- fold genes related to the generic under the generic itself

full network list merged with expression list:
- instead of only displaying expression data, let the menu contain an expression entry for every node in the network based off of label/generics 
- nodes in network without expression data and expressions not in the network will be a blank row
- nodes related to generic will be folded

heuristic for choosing n genes that map to a generic
- choose the gene with the highest magnitude expression ratio

**Comment by d2fong** [comment]
menu now contains entries for generics mapped to existing expressions.
