### ISSUE TITLE
3. Mapping:

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#399]
(1) design test cases
(2) write the function
(3) testing

**Comment by wxli0** [comment]
convert .xlsx to .json, traverse .json to find the mapping

**Comment by wxli0** [comment]
@jvwong Hi Jeff, I want the complete HGNC data set in .xlsx form. How did you get the test data set (https://docs.google.com/spreadsheets/d/1knhtWf8j_j9RCAx3xJVXWou9xcP7TGHbDhwltTB1tEE/edit#gid=0) in excel?

**Comment by jvwong** [comment]
I think you can try this: https://www.genenames.org/cgi-bin/download

e.g. https://www.genenames.org/cgi-bin/download?col=gd_hgnc_id&col=gd_app_sym&col=gd_app_name&col=gd_aliases&col=gd_pub_acc_ids&status=Approved&status=Entry+Withdrawn&status_opt=2&where=&order_by=gd_app_sym_sort&format=text&limit=&hgnc_dbtag=on&submit=submit

**Comment by wxli0** [comment]
That works. Thanks!

**Comment by wxli0** [comment]
[HGNC_dataset.xlsx](https://github.com/PathwayCommons/app-ui/files/1674027/HGNC_dataset.xlsx)
@jvwong Hi Jeff. There're some weird rows (row 18997 - 19009). For example, MARCH5 exists in the test data set (row 19) but doesn't exist in the complete dataset. Should I manually change column B (row 18997 - 19009) from X-Mar to MARCHX?

**Comment by jvwong** [comment]
Let's not use .xlsx from now on. I think Excel tries to be smart and turn entries in to dates. Go back to the source and stick with plain text/delimited.

**Comment by wxli0** [comment]
[HGNC_data.txt](https://github.com/PathwayCommons/app-ui/files/1674234/HGNC_data.txt)
[Validation_ test_data_ set.xlsx](https://github.com/PathwayCommons/app-ui/files/1674235/Validation_.test_data_.set.xlsx)

There're some inconsistencies between the test dataset and the complete dataset. NCOA1, SETD2, UBR7, TDG... don't exist in HGNC_data.txt. Which one should I refer to?

**Comment by jvwong** [comment]
I'm not sure you have the most comprehensive 'HGNC_data.txt' file. 
I tried this: 
```bash
$ curl "https://www.genenames.org/cgi-bin/download?col=gd_hgnc_id&col=gd_app_sym&col=gd_app_name&col=gd_status&col=gd_prev_sym&col=gd_aliases&col=gd_pub_acc_ids&status=Approved&status_opt=2&where=&order_by=gd_hgnc_id&format=text&limit=&hgnc_dbtag=on&submit=submit" -o HGNC_download.txt
```
