### ISSUE TITLE
4. Validating gene identifiers:

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#400]
(1) design test cases
(2) check for invalid tokens
(3) check for duplicate tokes
(4) check for duplicate mappings
(5) return 'YES' or 'NO'
(6) testing

**Comment by wxli0** [comment]
@d2fong Hi Dylan, as it comes to this step, I feel treating each symbol identifier as a string is not enough for future features such as highlighting duplicates. I'm thinking about creating a structure for each symbol and refactoring previous code:

struct token {
 name: string
 duplicate: bool
 legal: bool
}

Is that better?

**Comment by d2fong** [comment]
I think the structure you have proposed is reasonable. 

Here is how to use classes in javascript https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes
http://exploringjs.com/es6/ch_classes.html

Just remember to keep it simple as we still need to understand how to feed this input into the next stage of the request pipeline.
