### ISSUE TITLE
5. Encapsulating previous three operations

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#401]

**Comment by wxli0** [comment]
A user sends a list of gene identifiers to the validator
If valid, return each gene info including HgncSymbol, HgncID, approvedName, Synonyms, accessionNumbers;

otherwise, return relevant error messages containing: 
- duplicates
- unrecognized symbols

JSON response to be added

**Comment by jvwong** [comment]
Consider for an input gene list ["g1", "g2", ..., "gi", ..., "gn"] the response
 
```js
{
  duplicate: [ "g1", "g2", ..., "gn"],
  unrecognized: ["g5", "g6", ..., "gn"]
}

```

**Comment by wxli0** [comment]
done.
See latest version in branch validator_info.
