### ISSUE TITLE
Create an example input/output response for the following cases

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#403]
After you have followed the previous tutorial, look at this tutorial:

https://medium.com/@shazow/how-i-design-json-api-responses-71900f00f2db

Then, design a input/output response for your service.

Here is a base response that you should modify to start:

```
// potential example of good input
{
  geneList: ['BMP', 'P53']
}

// potential example of bad input
{
  random_garbage: 'dglkdsldf'
}

{
  random_garbage: {
    b: 1
  }
}
```

For both good inputs and bad inputs you should come up with sensible responses to each, but for now just respond with good or bad in your response:

```
// response to good input
{
  msg: 'input is good'
}

// response to bad input
{
  msg: 'input is bad'
}
```

**Comment by d2fong** [comment]
comment on your initial ideas for your responses in this issue

**Comment by d2fong** [comment]
Also don't worry about it being totally correct right now.  Just focus on getting basic input/output cases on paper so we can get an initial version.  As we go along we can build on this work make and make changes to it.

**Comment by wxli0** [comment]
I'd classify inputs into the following categories.
1. good input
- single human gene name
- multiple human gene names
    - delimited by whitespaces
    - delimited by commas
    - delimited by tabs
    - delimited by semicolons
    - delimited by newlines
    - delimited by different delimiters 

2. bad input
- single non-human gene name
- multiple non-human gene names
    - delimited by valid delimiters 
    - delimited by invalid delimiters
    - delimited by valid and invalid delimiters
- multiple human gene names
    - delimited by invalid delimiters
    - delimited by valid and invalid delimiters
- unrecognized gene names
    - delimited by valid delimiters 
    - delimited by invalid delimiters
    - delimited by valid and invalid delimiters
- combination of non-human and human gene names
- combination of unrecognized and human gene names
- combination of non-human and unrecognized gene names

**Comment by wxli0** [comment]
@d2fong Hi Dylan, could you please give me an example of how to modify the base response you gave me?

**Comment by wxli0** [comment]
Should I design test cases for duplicate inputs in this step?

**Comment by wxli0** [comment]
@d2fong Hi Dylan, I made a new pull request "third commit" for this issue containing all the tests I've written. Can I move on to the next task?
