### ISSUE TITLE
Interactions app mockup

### ISSUE THREAD

**Issue by logmosier** [PathwayCommons/app-ui#422]
The user would use a tab from the search app to access the app
![screen shot 2018-02-06 at 2 15 06 pm](https://user-images.githubusercontent.com/10948303/35879473-4d04b4ca-0b49-11e8-986e-10658ff3ff43.png)

The app would reuse basic-network-view.js to display the network. 
A menu like the extra information or download menus would be used for the settings. Different edge colours could be used for different interactions: 
![screen shot 2018-02-06 at 2 38 58 pm](https://user-images.githubusercontent.com/10948303/35880288-85592ebc-0b4b-11e8-874e-37eb8e6c0e2a.png)

When a user selects a node they would get the same information they would get from the view app:
![screen shot 2018-02-06 at 2 14 31 pm](https://user-images.githubusercontent.com/10948303/35879555-7e8ea992-0b49-11e8-9003-ca39cd65d274.png)

When a user selects a edge they would be told what nodes the interaction is between and what type of interaction it is. They would also be provided links to view the pathway and to different references about the interaction.
![screen shot 2018-02-06 at 2 14 24 pm](https://user-images.githubusercontent.com/10948303/35879667-ca7c06d8-0b49-11e8-8007-b3810a3dd23c.png)

**Comment by maxkfranz** [comment]
This looks good.  

One suggestion: It would be good to include node labels.

Tools like these can help to generate colours that contrast well: http://paletton.com/

**Comment by d2fong** [comment]
Also make the node labels have white/black outline depending on the colour of the node body.  It makes it easier to read them.

![screen shot 2018-02-06 at 3 18 41 pm](https://user-images.githubusercontent.com/2328291/35882120-17cb780e-0b51-11e8-8e47-9c2bacd76b09.png)
![screen shot 2018-02-06 at 3 18 26 pm](https://user-images.githubusercontent.com/2328291/35882121-17daacd4-0b51-11e8-8549-27a520d1b2d6.png)

**Comment by jvwong** [comment]
Looks good - a couple of notes

1. Using an 'interactions' tab would mean that it should only appear if this is a 'landing page' and hidden otherwise
2. Users won't know what those interaction type labels mean. Probably need to make them more biologist-friendly
3. Tooltip link label for " View pathway" could be "View detailed interaction" 
4. Toolbar button for collapse compartments won't make much sense etc.

**Comment by maxkfranz** [comment]
> Users won't know what those interaction type labels mean. Probably need to make them more biologist-friendly

Re. (2), we could probably join a bunch of groups together to shorten the list of colours.
