### ISSUE TITLE
6. enrichment:

### ISSUE THREAD

**Issue by wxli0** [PathwayCommons/app-ui#427]
(1) Design test cases
(2) Implement enrichment function (gprofiler service call)
(3) testing

- hardcode all attributes except query

**Comment by wxli0** [comment]
use Linux commend to process the output file
- remove 2nd line
- remove all lines beginning with # except the first line
- convert to json
- extract "term id"

**Comment by jvwong** [comment]
FYI 
https://github.com/tambeta/biojs-vis-gprofiler/blob/4c97ad3f453a05dba6bab7c3f750517e7cee2fa6/lib/gprofiler.js#L284-L289

**Comment by maxkfranz** [comment]
But don't use jquery functions like that example.  Use the native functions or lodash.

**Comment by wxli0** [comment]
Is it okay to embed linux commands in node js to process the file?

**Comment by maxkfranz** [comment]
> Is it okay to embed linux commands in node js to process the file?

No, use js.
