### ISSUE TITLE
Hide landing page contents for >1 recognized gene 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#428]
Landing page doesn't make sense for >1 recognized gene. Also it's not clear how the tokens are being parsed:

(Dev branch) 

EG 1 - [searching 'p53 MDM2'](http://localhost:3000/search?gt=0&lt=250&q=p53%20MDM2&type=Pathway) catches the last token (MDM2)
![image](https://user-images.githubusercontent.com/4706307/35941890-d6f334f8-0c21-11e8-9ca3-38b34c12f2e2.png)

EG 2 - [searching 'p53 MDM2 Ras'](http://localhost:3000/search?gt=0&lt=250&q=p53%20MDM2&type=Pathway) catches middle token (MDM2)

![image](https://user-images.githubusercontent.com/4706307/35941973-1e774eb8-0c22-11e8-8757-3ae5fc7d63c7.png)

EG 3 -  [searching 'p53 MDM2 ATM'](http://localhost:3000/search?gt=0&lt=250&q=p53%20MDM2%20ATM&type=Pathway) catches last token (ATM)

![image](https://user-images.githubusercontent.com/4706307/35942962-811a1ffc-0c25-11e8-95ef-f122557c6f6e.png)

**Comment by logmosier** [comment]
What should we do for searches that only include a single word but not a gene? Right now they are accepted if there is also pathways that are returned with the results and a uniprot ID is found.

**Comment by maxkfranz** [comment]
I would expect the normal search results to show up in that case, but the special gene data box wouldn't be there.

**Comment by jvwong** [comment]
Just logging this here for now: Make sure that the query forwarded to the server [pathway-commons search](https://github.com/PathwayCommons/app-ui/blob/27912c979bbbe796890028ecfb6eaf6c13afa141/src/server/pathway-commons/search/index.js#L11-L43) is efficient and accurate for this goal

**Comment by jvwong** [comment]
addressed in 4fcde7169ec4618383146a0d764307853370a26f
