### ISSUE TITLE
Caching landing page info box data

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#429]
Is there a case for lazy-fetching and caching this data? At least it'll be fast and reduce calls to sources.

**Comment by maxkfranz** [comment]
@jvwong I have a [Uniprot service in Factoid](https://github.com/PathwayCommons/factoid/blob/master/src/server/routes/api/element-association/uniprot.js) that allows you to query Uniprot.  It includes caching and allows for both search and single protein lookups.  Maybe we should just convert the service to a reusable npm module that both Factoid and the PC apps could consume.

It probably makes sense to do the same for all the entity services: Uniprot, Pubchem, Chebi.
