### ISSUE TITLE
Debug UI

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#435]
Add simple debug UI for gene ID validator service

**Comment by wxli0** [comment]
available at branch validator_info
http://localhost:3000/gq

**Comment by wxli0** [comment]
enrichment at 
http://localhost:3000/enrich
supports optional user settings

**Comment by jvwong** [comment]
Can we just combine this?

![screenshot at feb 14 16-29-53](https://user-images.githubusercontent.com/4706307/36229145-51a1ac0c-11a4-11e8-93e2-98846ed215b2.png)

**Comment by wxli0** [comment]
http://localhost:3000/gqenrich

**Comment by wxli0** [comment]
![screen shot 2018-02-16 at 4 24 48 pm](https://user-images.githubusercontent.com/24982880/36330024-134ebee8-1336-11e8-81bd-e39faa03411e.png)

Separated user settings.
