### ISSUE TITLE
Homepage search integration broken

### ISSUE THREAD

**Issue by mj3cheun** [PathwayCommons/app-ui#436]
Hi guys, Manfred here, long time no see.

Was just dropping by to see what you are up to. I have noticed that from the home page (`www.pathwaycommons.org/`), if you try searching from the search box integrated into the home page, it will always link out to an empty search page.

Example:
1. Go to home page
2. Search `tp53`
3. A new tab is opened with the URL `http://apps.pathwaycommons.org/#/search?gt=0&lt=250&type=Pathway&q=tp53`
4. The new search page opened has 0 results regardless of search string entered

The reason why this is happening is that the link out URL has the `/#/` which is no longer recognized by the search app.

Example:
`http://apps.pathwaycommons.org/search?gt=0&lt=250&q=tp53&type=Pathway` works
`http://apps.pathwaycommons.org/#/search?gt=0&lt=250&type=Pathway&q=tp53` doesn't

Don't know if this is already fixed but FYI.

**Comment by jvwong** [comment]
Thanks for the tip!

Addressed in https://github.com/PathwayCommons/about/commit/b6cfaa1d24e97a50d6b271b3a1697b9b51af7141
