### ISSUE TITLE
Display neighborhood

### ISSUE THREAD

**Issue by logmosier** [PathwayCommons/app-ui#438]
Right now the neighborhood graph that is being fetched, are so large the graph is unreadable. The smallest I have found is 295 nodes and 856 edges. 
![screen shot 2018-02-15 at 11 32 27 am](https://user-images.githubusercontent.com/10948303/36268732-4e13e446-1245-11e8-8411-2600260c693d.png)
But they can get much larger (1572 nodes 15752 edges) to the point of taking 3+ min to display. 
![screen shot 2018-02-15 at 11 40 06 am](https://user-images.githubusercontent.com/10948303/36268742-5458b7c8-1245-11e8-9177-00f955ad40b3.png)
(both of these are limited to 4 interaction types)
Would the best way to handle this be by modifying the data that is fetched (cut away nodes before displaying) or is there a better way?

**Comment by jvwong** [comment]
I assume this is a client-side bottleneck. Is it possible to spend time finding an example query that returns fewer interactions?

**Comment by logmosier** [comment]
I was able to find some much smaller graphs, Q8IWf7 and Q9BQY4 are good.

**Comment by maxkfranz** [comment]
You can load and render 20k elements in about a second (maybe 2s on a slower machine).

Here's some tests done back on `cytoscape@2.7.0`: https://github.com/cytoscape/cyjs2.6-cyjs2.7-desktop-comparison  And 3.2 is faster than 2.7.

Try using the Chrome profiler to see what's going on.  Or use `console.time()` to track how long different parts of the code are taking.

I suspect you have a slow layout and/or the PC query is taking a while.  You can also try using the grid layout or the random layout to see how much of a difference layout expense makes -- those are cheap layouts.

**Comment by maxkfranz** [comment]
What layout are you using now?

**Comment by logmosier** [comment]
I was using the cose-bilkent as I was reusing baseNetworkView, I switched over to grid layout and saw a drop form 26512.44ms to 1279.80ms for the layout.run() call.

**Comment by IgorRodchenkov** [comment]
Or try PATHSBETWEEN graph query instead of neighborhood (with one ID is ok)...

**Comment by IgorRodchenkov** [comment]
I bet this (that a PC neighborhood query produces a large "hairball") has to do with 
PathwayCommons/cpath2#284 and BioPAX/Paxtools#34 - both will be fixed in the next PC db release (PC10).
