### ISSUE TITLE
Tooltips for the interaction app

### ISSUE THREAD

**Issue by logmosier** [PathwayCommons/app-ui#439]

**Comment by maxkfranz** [comment]
Take a look at cytoscape-popper and tippy.js: https://github.com/cytoscape/cytoscape.js-popper

**Comment by logmosier** [comment]
@maxkfranz, is it possible that the tooltips were already changed to use cytoscape-popper and tippy.js, because in cytoscape-extensions.js there is
```
const popper = require('cytoscape-popper');`
module.exports = () => {
   ....
  cytoscape.use(popper);
  // cytoscape.use(tippy);
}; 
``` 
and  the tool tips are created in tool /tooltips/index.js with 
```
let refObject = this.cyElement.popperRef();
tooltip = tippy(refObject, { html: tooltipHTML, theme: 'light', interactive: true, 
     trigger: 'manual', hideOnClick: false, arrow: true, position: 'bottom' });
```
and shown with `tooltip.show(tooltip.store[0].popper)`? This appears to match up with what is shown in the 'Usage with Tippy.js' section of the cytoscape-popper README.

**Comment by maxkfranz** [comment]
Then probably Dylan cleaned it up already.

You should only need to do `tooltip.show()` without args if you use `tippy.js` v2.  I would recommend using v2 if possible.  It has several fixes and improvements, and it's cleaner to use things like 'show()`.

I wouldn't worry about upgrading to v2 right away, but maybe it makes sense to have another ticket for later in the queue.

**Comment by d2fong** [comment]
I didn't touch any of the network tooltip code.  Maybe Harsh was already using the tooltips as prescribed/

**Comment by jvwong** [comment]
I am noticing that in general, the tooltips are hidden by clicking on the same node or edge. Is this the intended behaviour?    

This seems foreign to me. I would expect 'clicking off' anywhere outside the node would hide tooltip.

**Comment by logmosier** [comment]
That was the behaviour in the tooltips in the regular viewer, though I do agree that it would make sense to hide the tooltip by 'clicking off'. I will add this behaviour if there are no objections.

**Comment by jvwong** [comment]
I think this should be the behaviour in general (viewer module). It feels like a bug right now.

**Comment by logmosier** [comment]
What about when the user clicks on the toolbar or a sidebar I could see arguments for either side?
Hiding the tooltip would match with the behaviour of clicking off of the element but I could possibly see people wanting to have the tooltip up while they also view one of the menus.

**Comment by jvwong** [comment]
How about this: Clicking anywhere in graph area (outside node with tooltip shown) to hide tooltip. Else, keep showing.
