### ISSUE TITLE
Organize database functions into their respective files

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#44]
This is a good start, and I think 'query' is a better name than 'accessDB', but now we will have to re-arrange some of the functions in query.

Generally, the name 'query' is associated with read only access, but there are some functions such as 'updateGraph', 'saveLayout', and 'setDatabase', that do more than query the db (i.e update/save).

It would be nice to create a new file like 'update.js' that contained the updateGraph and saveLayout functions.

I am not sure if 'updateVersion' is that descriptive. Can you elaborate on what the purpose of this file is? Is this code for a batch job, i.e run this code for each pathway?

**Comment by gaelder** [comment]
Sounds good. updateVersion is a batch script that adds all the new data for a version of PC2 to an existing database. Would batchUpdate.js be more suitable? Do you feel the word version should even be there?

**Comment by d2fong** [comment]
Ok everything should be organized a bit better now.  

Re: batch files yes I think it makes sense to rename updateVersion to batchUpdate, and also populateEmpty to batchPopulate.
