### ISSUE TITLE
Menus for the interaction app 

### ISSUE THREAD

**Issue by logmosier** [PathwayCommons/app-ui#440]
Build a settings menu similar to the one from PCViz and make sure the other menus available make sense and work.

**Comment by maxkfranz** [comment]
Maybe the settings menu could re-use the sidebar

**Comment by logmosier** [comment]
Changes to be made:
- Limit to just binding interactions upon loading
- Make the selected interactions more obvious
- Show the menu by default
- Change button and name

**Comment by jvwong** [comment]
Since the tooltips take care of showing metadata, can we call it 'Filters'?
