### ISSUE TITLE
Interactions: Simple layout ideas

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#448]
![layouts](https://user-images.githubusercontent.com/4706307/36554787-35f2e338-17ce-11e8-8ec4-62af29a52eb9.png)
![layouts2](https://user-images.githubusercontent.com/4706307/36554801-400c0e12-17ce-11e8-9899-f3809fdd4d83.png)

**Comment by maxkfranz** [comment]
The CoSE layout would need lots of tweaks to the parameters to work well.
