### ISSUE TITLE
Use fixed version of g:Profiler

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#449]
Should we use a consistent [version](https://biit.cs.ut.ee/gprofiler/archives/) of g:Profiler for our 'enrichment' wrapper/service?

 e.g. [Ensembl 90, Ensembl Genomes 37 (rev 1741, build date 2017-10-19)](https://biit.cs.ut.ee/gprofiler_archive3/r1741_e90_eg37/web/)

This might solve the GMT file versioning issue:

![image](https://user-images.githubusercontent.com/4706307/36557824-52be11dc-17d7-11e8-9a97-4f796123f797.png)

**Comment by wxli0** [comment]
Would it be better if we always use the latest version?
I'm thinking of downloading the gmt file from [https://biit.cs.ut.ee/gprofiler/gmt/gprofiler_hsapiens.NAME.gmt.zip](url) instead of keep a static file in the folder.

**Comment by jvwong** [comment]
Maybe see what Ruth thinks about this. I don't know all the gotchas like she might.

**Comment by wxli0** [comment]
Ruth suggested using a fixed version. I'm going to use the most recent one [https://biit.cs.ut.ee/gprofiler_archive3/r1741_e90_eg37/web/](url)
