### ISSUE TITLE
g:profiler data file is too big. JS can't convert txt to csv

### ISSUE THREAD

**Issue by wxli0** [PathwayCommons/app-ui#450]

**Comment by wxli0** [comment]
295.8MB txt

**Comment by wxli0** [comment]
JS can't parse it either since the string is too long.

**Comment by d2fong** [comment]
If that really is the case, then you probably have to look into streams or buffers.

https://nodejs.org/api/stream.html

What exactly are you using this string for?

**Comment by wxli0** [comment]
I'm using the file for looking up the set of gene names corresponding to a pathway ID. 
[https://biit.cs.ut.ee/gprofiler/gmt/gprofiler_hsapiens.NAME.gmt.zip]
The file doesn't have any newline chars and is of huge size.

**Comment by d2fong** [comment]
I can probably help you with this on Monday.

**Comment by wxli0** [comment]
Ok. thanks.

**Comment by wxli0** [comment]
Am I on the right track to look up some documentation on buffer?

**Comment by d2fong** [comment]
Yes.

**Comment by d2fong** [comment]
Also try looking up solutions for parsing large strings in node.js

**Comment by wxli0** [comment]
- use R to parse .gmt to an object (GSA.read.gmt)
- create "geneset_names.txt", "geneset_descriptions.txt", "genesets.txt" containing genesets, descriptions, names from the object
- construct 3 js arrays containing info from the 3 files
- construct a map {key: geneset_name, des: description, geneset: genesets}
- look up GO/REACTOME pathway ID in the map
