### ISSUE TITLE
3. Create cytoscape-formatted JSON containing info from step2

### ISSUE THREAD

**Issue by wxli0** [PathwayCommons/app-ui#454]

**Comment by jvwong** [comment]
Should we consider returning additional information? 

For example, we might return some additional keys, similar to the validator:

```js
{
	"unrecognized": [],
	"duplicate": [],
	"graph": [
		{
			"elements": { "nodes": 
                        ... 
		}, 
                ...
          ]
}
```

In the longer term, it would be nice to make 'emap' more standalone. Right now, we need to know that it supports GO and REACTOME IDs returned from g:Profiler...

**Comment by wxli0** [comment]
Yes. It would be better to report duplicate and unrecognized.
