### ISSUE TITLE
4. Provide an endpoint for emap service

### ISSUE THREAD

**Issue by wxli0** [PathwayCommons/app-ui#455]
- enter pathwayIds from the endpoint
- display network

**Comment by wxli0** [comment]
cytoscape object can not be displayed from the endpoint

**Comment by wxli0** [comment]
adding target: 'node' or node: {fs: 'empty'} to webpack.config,js (according to (https://github.com/webpack-contrib/css-loader/issues/447) resolved the current error but led to another one
![screen shot 2018-03-01 at 4 51 31 pm](https://user-images.githubusercontent.com/24982880/36871654-f367e592-1d70-11e8-9a8a-042a2550bb93.png)

**Comment by wxli0** [comment]
@d2fong 
Any ideas on how to fix 'can't resolve 'fs''? The error occurred yesterday and there was no error from the endpoint on Wednesday afternoon. I checked the computer history and there was no update on Wednesday night.

**Comment by wxli0** [comment]
The error occurs at 'npm run build'

**Comment by d2fong** [comment]
hm.. not sure exactly what problem you are having.  Can you provide any more info?

**Comment by wxli0** [comment]
The code at branch emap [https://github.com/wxli0/app-ui/commit/2639a5fd8f554644d5ec652d623cbcac2061b899](url) can't compile. reports can't resolve 'fs'

**Comment by d2fong** [comment]
why do you need fs?

**Comment by wxli0** [comment]
The code at /app-ui/src/server/emap/Routput/preprocess.js needs fs.readFileSync.

**Comment by wxli0** [comment]
[https://github.com/wxli0/app-ui/blob/emap/src/server/emap/Routput/preprocess.js#L6](url)

**Comment by jvwong** [comment]
The background: The service needs access to data in a large GMT file. We thought that using a temp file would be a temporary solution that would allow us to more quickly get on with actually using the data. So this GMT file, is processed in R, then read in from a file.

This is clearly not saving us time and adding more complexity. @wxlio - looks like you might have to solve the problem if reading in that data in a maintainable way for the service to use.

**Comment by d2fong** [comment]
Thats fine, I don't see how reading a file wouldn't work though.  Let me come help you in person.

**Comment by d2fong** [comment]
@jvwong do you know how the gmt file is generated?  does gProfiler generate it?  where does this file come from?

The next thing to try is to modify the code that generates that file so that it is easier to work with.

**Comment by wxli0** [comment]
@jvwong Yes. We'll have to solve the maintainability problem eventually, though I don't think that is related to 'can't resolve fs'. I tried commenting all the contents in preprocess.js except require('fs') and export table and the error still occurred.

**Comment by jvwong** [comment]
If you go to [g:Profiler](https://biit.cs.ut.ee/gprofiler/) and click the show advanced options, there is a link for 'name' that downloads it.

![image](https://user-images.githubusercontent.com/4706307/36909932-5ea70fd0-1e0d-11e8-8af2-d11dd7e2eaa4.png)

**Comment by jvwong** [comment]
> @jvwong Yes. We'll have to solve the maintainability problem eventually, though I don't think that is related to 'can't resolve fs'. 

@wxli0 I undertand what you mean. But how long do we go on solving the next bugs/issues related to a quick and dirty solution?

**Comment by d2fong** [comment]
Yes I know thats where it is from but does gProfiler generate that?

**Comment by jvwong** [comment]
Are you asking where g:profiler  formats the GMT data file? no clue.

**Comment by d2fong** [comment]
Yeah like who made that file in general?   Was it some guy just typing in a bunch of rows (I would assume no...)

**Comment by wxli0** [comment]
@jvwong I haven't come up with a rough idea to this problem. It'd be the next issue to solve after getting all related info (edges, nodes) done.

**Comment by jvwong** [comment]
I can only assume there is some C++ code dragging in data and formatting it from databases like Pathway Commons does. Is that what you are looking for?

[g:Profiler--a web-based toolset for functional profiling of gene lists from large-scale experiments. Reimand J et al](http://nar.oxfordjournals.org/lookup/doi/10.1093/nar/gkm226)
 >The data used in g:Profiler is derived from the Gene Ontology (5), KEGG (13), Reactome (14) and TRANSFAC (15) databases.

**Comment by wxli0** [comment]
Is it okay to use package 'r-script' [https://www.npmjs.com/package/r-script](url) to import R code in the service?

**Comment by jvwong** [comment]
You mean call R programmatically? Let's not do that.

**Comment by wxli0** [comment]
ok. resolved by js expressions. see #450

**Comment by d2fong** [comment]
Ok we should still go with the quick and dirty approach.  wxli0 just had to learn that you can't require server code in client side react components you have to expose it as an API call.

**Comment by wxli0** [comment]
@d2fong Is this the right way to call make_cytoscape and define a ref? it reports "Uncaught TypeError: undefined does not have a default width / height".
