### ISSUE TITLE
Extended SIF, section 2: Some entries have multiple entity references?

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#459]
In the extended SIF, the second section is [described](http://www.pathwaycommons.org/pc2/formats):

> The second section contains participant (molecule or gene) name followed by several node attributes. 

In one case for a neighbourhood [(e.g. MYC)](http://www.pathwaycommons.org/pc2/graph?source=http://identifiers.org/uniprot/P01106&kind=neighborhood&format=TXT), the second section has entries with multiple entity reference subtypes? 

```
...
CEPT1	interacts-with	MYC	BIND;IntAct;BioGRID	12808131;17314511
...
PARTICIPANT	PARTICIPANT_TYPE	PARTICIPANT_NAME	UNIFICATION_XREF	RELATIONSHIP_XREF
...
CEPT1	DnaReference;ProteinReference	CEPT1 promoter;CEPT1_HUMAN	ncbi gene:10390;uniprot knowledgebase:Q9Y6K0	hgnc symbol:CEPT1;uniprot knowledgebase:Q9Y6K0
```

@IgorRodchenkov is this because the second section is summarizing types involved in interactions in the first section?

**Comment by IgorRodchenkov** [comment]
That's correct. What's the issue?

SIF is a simple view/summary of the BioPAX model; and because we (normally) use HGNC Symbols, some participants merge into things like 'CEPT1' (unlike if we'd used URIs).

Ask @ozgunbabur for more info.

**Comment by jvwong** [comment]
no problem.
