### ISSUE TITLE
Only include relevant toolbar buttons/options 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#461]
We should review which of the 'view' UI toolbar buttons/options make sense for a SIF-like view.

- 'Extra Information'
  - Should have something here so interaction view is 'standalone'. Could we simply reproduce some of the info box?  

- 'Download options'
  - Hide sidebar options: 'GMT', 'Extended SIF', 'BioPAX', 'JSON-LD',  'SBGN-ML'

- 'Expand/Collapse all complex nodes'
  - Hide toolbar button

...other?

**Comment by jvwong** [comment]
menu bar title should show HGNC symbol rather than UniProtID. 
![image](https://user-images.githubusercontent.com/4706307/36981914-683d5d46-205c-11e8-8b0b-c452825d0d29.png)

**Comment by logmosier** [comment]
I have made the changes to the menu bar and hide the 'Expand/Collapse all complex nodes' button in the branch interactionsViewCombined. 
Reproducing the info should be pretty straight forward. 
For the download options I am wondering why we should hide these options they are available options to fetch from PC , are they simply not that useful? Also when you download the data should it download the full set of interactions or only the ones that are currently being shown?

**Comment by jvwong** [comment]
>For the download options I am wondering why we should hide these options they are available options to fetch from PC , are they simply not that useful? Also when you download the data should it download the full set of interactions or only the ones that are currently being shown?

Let me try: right now these are hairballs. In the future, when we start to prune these interactions, the network will become 'unlinked' from any results that could be directly returned from PC web services. If someone really wants these formats, they can follow the edge 'Links' you provide to the SBGN-PD viewer, which has the object as represented by PC.

**Comment by jvwong** [comment]
>Also when you download the data should it download the full set of interactions or only the ones that are currently being shown?

So following with my rationale above, I would want the data for the interactions shown in the UI.
