### ISSUE TITLE
Code quality issues

### ISSUE THREAD

**Issue by wxli0** [PathwayCommons/app-ui#462]
- move g:convert validator to gene-query folder
- change all foreach, filter, map to lodash functions
- blank lines consistency
  - function blocks: 2 blank lines
  - within the function: 1 line
- change all double quotes to single quotes
- change all delimiters to whitespace (endpoints and functions)
- uniform function name, parameter name, endpoint name
  - 'gene-query' to 'validator'
  - 'validatorGp' to 'validatorGconvert'
  - 'enrich' to 'enrichment'
- remove unnecessary comments, add documentation if needed
- const vs let
  - const != immutable, can not be rebound
- function to =>

**Comment by jvwong** [comment]
IS there an argument to use just the g:Convert version and just call it 'validator'? To me it is more flexible than the HGNC-file based implementation.

**Comment by wxli0** [comment]
@jvwong Ok. will add an argument later.
After fixing all issues listed above, I'll start with a new copy of development branch, merge files one by one, and see if it solves the css, cytoscape version issues we encountered.

**Comment by jvwong** [comment]
can you remove 'app-ui/outputFile' creation?

**Comment by wxli0** [comment]
[https://github.com/wxli0/app-ui/blob/emap/src/server/enrichment/enrichment.js#L51-L72](url)
The output file is created inside enrichment folder. I need to keep the file because the json object is generated from it (line 56). And I removed the file at line 72. Is that ok?

**Comment by jvwong** [comment]
Let's me move parsing g:profiler output into a separate, single issue so it can be properly tracked.
