### ISSUE TITLE
Formatting: Edge tooltip information 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#466]
I think these tooltip 'Links' are really interesting, and show-off how the apps complement one another.
 
Consider an example for [ATM](http://localhost:3000/interactions?ID=Q13315) + p53, expression. 
From the user-point of view, it isn't obvious what the tooltip links are or where they will go. The user will know that the nodes are genes/proteins and that via the filter/edge colour, they are looking at 'expression', in fact, they know that 'ATM controls expression of TP53'!

So how best to format these links?    

![image](https://user-images.githubusercontent.com/4706307/37098679-7d5c4ad4-21ec-11e8-970e-a7f97503cfc6.png)

**Comment by jvwong** [comment]
FYI [PCViz](http://www.pathwaycommons.org/pcviz/#pathsbetween/ATM,TP53)

![image](https://user-images.githubusercontent.com/4706307/37100152-3edeae92-21f0-11e8-8fb3-68db9e1a2c5b.png)

**Comment by logmosier** [comment]
Would it be better to label them as pathways? For the individual links them self it would be possible to get the pathway name and display that. Though I think you would have to fetch that for every one and I know many of the links in the Phosphorylation interactions are named 'Unknown Network' or so I am not sure how well this would actually work out.

**Comment by jvwong** [comment]
I see these URIs pointing to 'parts of pathways', and indeed, many of them might not have useful names.
 Maybe tooltip something like:

### ATM controls expression of TP53
#### Detailed views
![button_interaction](https://user-images.githubusercontent.com/4706307/37119712-40b910aa-2226-11e8-982f-b50bd1bbf073.png)
![button_interaction 1](https://user-images.githubusercontent.com/4706307/37119727-4b8f4d28-2226-11e8-84ba-c9a902b0bd40.png)

Although I don't love the label 'interaction' but something human-readable...

**Comment by logmosier** [comment]
So you are thinking that the link styling should be switched out for more of a button type style? If this is the case were you thinking that all the links in the the tooltips should be this style or just the interaction ones?

**Comment by jvwong** [comment]
They can be left simply as text links. I was more concerned with the text itself.

**Comment by logmosier** [comment]
Ok that is simpler to do, instead of interaction we could use the first human readable part of the id so the tooltip in the first picture would be :
Template Reaction 
Control
Control
and then possibly do something to differentiate the 2 controls.

**Comment by jvwong** [comment]
But remember the work we did to 'dejargonify' the SIF relationship types.
We should provide a mapping that is less BioPAX for these. This is kinda why I stuck with 'Interaction' in my mockup above.

**Comment by jvwong** [comment]
Basically what it comes down to for the user is: Is there information here that I can use to make a more specific choice of link to follow? 

I don't think the BioPAX prefix term does this, at least for me. You pretty much gotta see what it is.

**Comment by logmosier** [comment]
That makes sense, was not sure if the BioPAX terms would hold enough meaning to help,  will stick to interaction for now.

**Comment by jvwong** [comment]
Also note, for some of the MEDIATOR_ID entries, I have seen things like this: 'http://identifiers.org/reactome/R-HSA-4647597' (e.g. [graph search with pathsbetween contains 'p53 controls expression of CDKN1A'](http://www.pathwaycommons.org/pc2/graph?source=http://identifiers.org/uniprot/P04637&source=http://identifiers.org/uniprot/P38936&kind=PATHSBETWEEN&format=txt) )

**Comment by logmosier** [comment]
Is this what you had in mind?
![screen shot 2018-03-13 at 9 43 14 am](https://user-images.githubusercontent.com/10948303/37346274-496870a0-26a5-11e8-9764-2a46d59e661d.png)
![screen shot 2018-03-13 at 9 43 22 am](https://user-images.githubusercontent.com/10948303/37346268-46ce2a56-26a5-11e8-9067-4dc5e408c574.png)

**Comment by jvwong** [comment]
The 'Pathway Commons' is redundant. 
A list bullet with 'less' is confusing.
I would only put a 'more>>' if there is a lot more. Why put an extra click in the way?

**Comment by jvwong** [comment]
Also, should we consider including useful information contained in the 'INTERACTION_PUBMED_ID' field?

NCBI has a capability to ['efetch'](https://www.ncbi.nlm.nih.gov/books/NBK25499/#chapter4.EFetch)  [fields](https://www.ncbi.nlm.nih.gov/books/NBK25499/table/chapter4.T._valid_values_of__retmode_and/?report=objectonly) of a publication.

e.g. for example above with [TP53 and CDKN1A](http://www.pathwaycommons.org/pc2/graph?source=http://identifiers.org/uniprot/P04637&source=http://identifiers.org/uniprot/P38936&kind=PATHSBETWEEN&format=txt) there is an interaction called 'TP53 (controls-expression-of) CDKN1A'

![image](https://user-images.githubusercontent.com/4706307/37352759-5aa9b22a-26b4-11e8-8936-9a1d2e6898c7.png)

And you can use the efetch on the pubmed ID  11080152 to [get](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?id=11080152&db=pubmed&retmode=abstract&rettype=text)


```
1. EMBO J. 2000 Nov 15;19(22):6051-64.

Negative cross-talk between p53 and the glucocorticoid receptor and its role in
neuroblastoma cells.

Sengupta S(1), Vonesch JL, Waltzinger C, Zheng H, Wasylyk B.

Author information: 
(1)Institut de Génétique et de Biologie Moléculaire et Cellulaire,
CNRS/INSERM/ULP, 1 Rue Laurent Fries, BP 163, 67404 Illkirch cedex, France.

The tumour suppressor p53 and the glucocorticoid receptor (GR) respond to
different types of stress. We found that dexamethasone-activated endogenous and
exogenous GR inhibit p53-dependent functions, including transactivation, up- (Bax
and p21(WAF1/CIP1)) and down- (Bcl2) regulation of endogenous genes, cell cycle
arrest and apoptosis. GR forms a complex with p53 in vivo, resulting in
cytoplasmic sequestration of both p53 and GR. In neuroblastoma (NB) cells,
cytoplasmic retention and inactivation of wild-type p53 involves GR. p53 and GR
form a complex that is dissociated by GR antagonists, resulting in accumulation
of p53 in the nucleus, activation of p53-responsive genes, growth arrest and
apoptosis. These results suggest that molecules that efficiently disrupt GR-p53
interactions would have a therapeutic potential for the treatment of
neuroblastoma and perhaps other diseases in which p53 is sequestered by GR.

DOI: 10.1093/emboj/19.22.6051 
PMCID: PMC305812
PMID: 11080152  [Indexed for MEDLINE]


```

**Comment by logmosier** [comment]
It looks like it could be quite useful information to include. I think we should either include just the start of the paragraph with a more button to show the rest (ie. 'The tumour suppressor p53 and the glucocorticoid receptor (GR) more >>' -> the main paragraph followed by what is above and below it as I am assuming we need to include that), or we could simply include a link to the information. I think the link may work better to include in a tooltip.

**Comment by jvwong** [comment]
Sure. I can see all of this work being cached in the future so keep it light and don’t fetch anything from Pubmed. Just create a link.
