### ISSUE TITLE
Automated conversion of jsx to hyperscript for src/client

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#47]
For each component in the client directory that uses jsx:
- paste the jsx code into http://html-to-hyperscript.paqmind.com/
- set syntax to 'h', tab size to '2'
- paste the result back into the render method for the component
- make sure it still works/doesn't throw any errors

Talk to me if you run into any problems

**Comment by d2fong** [comment]
@maxkfranz  The tool doesn't work that well.  Is there an alternative tool that might work better?

https://github.com/mlmorg/react-hyperscript#usage 

For normal html elements, you can do something like:
```js
h('div', {}, [])
```

For simple classnames or an id, you can write:
```js
// simple class
h('div.simple-classname', {}, [])
// id
h('div#div-id', {}, [])
```

For complex classnames that depend of state, you should use the 'className' property for the props object:

```js
const classNames = require('classnames');

const state = this.state;
h('div', {className: classNames('base-css-class', state.loading ? 'disabled' : '', ...) }, []);
```

**Comment by jonahdlin** [comment]
Fixed in #52

**Comment by maxkfranz** [comment]
@d2fong I don't think there are going to be many copy-paste UI tools out there.  

You could try something like https://github.com/jchook/babel-plugin-transform-h-jsx in future, but it's more setup.  Though you could organise it like a node script (separate package.json), i.e. `node jsx2hh.js fileToConvert.js`.  Probably not worth the time though.

**Comment by d2fong** [comment]
Its ok, Jonah was able to convert jsx to hyperscript w/o problems.
