### ISSUE TITLE
Create a function that parses the gconvert response

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#470]
in gene-validator/index.js, create a function that takes in a string of the form:

1	TP53	1.1	ENSG00000141510	TP53	tumor protein p53 [Source:HGNC Symbol;Acc:HGNC:11998]	WIKIGENE, UNIPROT_GN, HGNC, ENTREZGENE, DBASS3, DBASS5
2	BMP2	2.1	ENSG00000125845	BMP2	bone morphogenetic protein 2 [Source:HGNC Symbol;Acc:HGNC:1069]	UNIPROT_GN, WIKIGENE, HGNC, ENTREZGENE
3	BRCA1	3.1	ENSG00000012048	BRCA1	BRCA1, DNA repair associated [Source:HGNC Symbol;Acc:HGNC:1100]	ENTREZGENE, HGNC, DBASS3, UNIPROT_GN, WIKIGENE, DBASS5

1. split string by newline
2. split each line by tab
3. come up with a consistent parsing scheme based on token order (e.g initial alias, converted alias, name, version, etc)
4. produce a js model object that represents this parsed data

**Comment by jvwong** [comment]
Addressed in 4c52e8bbc95200342a858aba86890b16bc10f8b1
