### ISSUE TITLE
enrichment service related issues

### ISSUE THREAD

**Issue by wxli0** [PathwayCommons/app-ui#481]
1. Implement enrichment.js logic (branch enrichment-logic) #482
    - Copy paste from branch emap
2. Encapsulate parsing algorithm in a helper function (branch enrichment-helper) #484 
3. update package.json, package-lock.json (request, csvtojson package)
4. Simplify the process of creating ret json object (branch enrichment-simplify) #484
    - String -> txt -> csv -> object, to string -> array -> object 
5. Try fetch (branch enrichment-fetch)
6. Add basic tests (branch enrichment-test), move onto branch enrichment-test-copy #487 #494 #486
7. Coding style (branch enrichment-style) #492
    - Make default setting a global const 
    - Declare url as const 
    - variable name: str1, str2, str3, str4
8. Expose endpoint (branch enrichment-endpoint) #493
    - router.post
9. missed custbg parameter in enrichment.js defaultSetting (branch enrichment-custbg) #522

**Comment by wxli0** [comment]
@jvwong Which options should be exposed? (output, organism, significant, sortByStructure, orderedQuery, asRanges, noIea, underrep, hierfiltering, userThr, minSetSize, maxSetSize, threadholdAlgo, domainSizeType, custbg, custbgCb)

**Comment by jvwong** [comment]
I would suggest:

- orderedQuery
- userThr 
- minSetSize
- maxSetSize
- threadholdAlgo
- custbg
- custbgCb

You can also expose data sources but default them (see email in scope Google doc).

Also, you should look at the [help](https://biit.cs.ut.ee/gprofiler/help.cgi?help_id=55) and verify the parameters you pasted above even exist (e.g. 'underrep'). You can ask the help desk . I notice you're assuming I know what I'm talking about, which is generally dangerous.
