### ISSUE TITLE
Add pathway viewer tooltip link for 'Search <gene/protein>'

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#483]
## Description of new feature

Add a link to the entity tooltips in the [pathway view](http://apps.pathwaycommons.org/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-69895) that will launch a search for that gene. This links pathway entities back to the search listing page.

## Motivation for new feature

When a search consists of a single gene name [(HGNC approved symbol e.g. 'TP53')](https://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:11998) or protein identifier [(UniProt Accession e.g. 'P04637')](http://www.uniprot.org/uniprot/P04637) the Search will display an information box  and pathways. This was intended as a 'landing page' when linking from biological databases. 

![image](https://user-images.githubusercontent.com/4706307/37220601-211d6e74-2395-11e8-8661-afc51faa8550.png)

Users viewing a pathway [(e.g. Transcriptional activation of cell cycle inhibitor p21 | Reactome)](http://apps.pathwaycommons.org/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-69895) could be interested in individual genes and proteins therein.  

![image](https://user-images.githubusercontent.com/4706307/37220423-9e322d24-2394-11e8-8311-d782a8f2f6dd.png)

This features facilitates that exploration.

**Comment by MichaelWrana** [comment]
I've attempted to fix this issue in PR #750.
I modified the header of every tooltip to include an anchor tag which links to a new pathway commons search for the name of the protein/complex/etc... in the tooltip.
The `href` of each link is generated as `/search?&q=proteinName`

The new tooltips look like: 

![new tooltip](https://user-images.githubusercontent.com/25777239/40004241-45384bb0-5763-11e8-8177-c97fe0a1028b.png)
The link in the header will open a pathway commons search in a new tab:

![search page](https://user-images.githubusercontent.com/25777239/40004296-5f3daf96-5763-11e8-812f-c2bf97bc7d05.png)

**Comment by maxkfranz** [comment]
That looks like a great start.  Is there a way we could change the design so that the action is clearer?  A user might not understand that clicking the title text would do a new search.

The search link may have to be a distinct UI element.

**Comment by jvwong** [comment]
Regarding text - maybe more direct: 'Search PC for "HIST2H3"' (stole this from right-click browser Google search)

**Comment by MichaelWrana** [comment]
Something like this looks good to me:

![tooltip 1](https://user-images.githubusercontent.com/25777239/40010858-051f5e0e-5774-11e8-9c85-5982c67f44c8.png)

Except the header will go back to black text and the new link will be blue and underlined

**Comment by jvwong** [comment]
Looks good enough to me. Can you remind us here what that search term represents? (HGNC symbol perhaps)

**Comment by jvwong** [comment]
Sometimes. Have you tried clicking on a 'process node' in the [pathway viewer](http://appsbeta.pathwaycommons.org/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-69895):
![image](https://user-images.githubusercontent.com/4706307/40061008-ef5deaba-5825-11e8-9250-9d827fd5204c.png)

What about when you click an edge in the [interactions viewer](http://appsbeta.pathwaycommons.org/interactions?source=P39689):

![image](https://user-images.githubusercontent.com/4706307/40061115-31099cd4-5826-11e8-88e0-46eca51506b2.png)

**Comment by MichaelWrana** [comment]
The logic for checking if the node is a `protein` wasn't working correctly, but I've fixed that in the latest iteration:
`protein` node tooltip:
![tooltip 1](https://user-images.githubusercontent.com/25777239/40062202-b8387cd2-5828-11e8-8512-5741d2761f5c.png)
Any other node tooltip:
![tooltip 2](https://user-images.githubusercontent.com/25777239/40062225-c49d665e-5828-11e8-9dd0-752cbd1c2c30.png)

**Comment by jvwong** [comment]
Let me be clear - I am OK with the search terms used in all these cases. But I think this helps us  1. understand how the metadata is currently being fetched and 2. argues for the need to refactor the metadata fetching system - it's fragile.

**Comment by MichaelWrana** [comment]
I agree.  The metadata gathering system gives quite a few inconsistent results.  For Example:
`Biochemical Reaction` elements don't have a name property, but instead use an index labelled "Display Name" in the `parsedMetadata` Array.  However almost all other elements use the name property.


I've modified the code so links should now appear on almost all the tooltips.
Are there any specific elements where we don't want the links to appear in the tooltip?
Examples:
![screen shot 2018-05-15 at 12 58 44 pm](https://user-images.githubusercontent.com/25777239/40071753-bb1ecec6-583f-11e8-821e-4d4aa74b6a56.png)
![screen shot 2018-05-15 at 12 56 41 pm](https://user-images.githubusercontent.com/25777239/40071754-bb2bc2a2-583f-11e8-8782-44385b8703bb.png)
![screen shot 2018-05-15 at 12 51 42 pm](https://user-images.githubusercontent.com/25777239/40071755-bb3aeaf2-583f-11e8-9d74-4f3b9350b207.png)

**Comment by jvwong** [comment]
Let's wrap this issue up for now as is. We can take the tooltip/metadata redesign offline into a planning doc.
