### ISSUE TITLE
gene-validator should use converted alias for discriminating gene ID validity 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#503]
## Environment info

- Browser version (client) : n/a
- Node.js version (server) :v8.8.1

## Current (buggy) behaviour

The logic for [gene ID validation](https://github.com/PathwayCommons/app-ui/blob/2e3484b9d84f9867b2bdb8c599d6402447f0197e/src/server/enrichment-map/gene-validator/index.js) uses [g:Convert](https://biit.cs.ut.ee/gprofiler/gconvert.cgi) to map an input ID ('initial alias' in the g:Convert output) to a target ID ('converted alias' field in the g:Convert output).
![image](https://user-images.githubusercontent.com/4706307/37349900-e2c70d76-26ad-11e8-99a8-cb3f6bf94bd7.png)

However, neither the ['target' database](https://github.com/PathwayCommons/app-ui/blob/2e3484b9d84f9867b2bdb8c599d6402447f0197e/src/server/enrichment-map/gene-validator/index.js#L14) declared in the defaultSetting object (below) nor the corresponding 'converted alias' output are ever used. Rather, the code works, perhaps by accident, by parsing through the description field.   

```js
/*
Documentation for g:convert validator:
sample url: http://localhost:3000/api/validatorGconvert?genes=ATM ATP ATM
output: {"unrecogized":["ATP"],"duplicate":["ATM"],"geneInfo":[{"HGNC_symbol":"ATM","HGNC_id":"HGNC:795"}]}
*/
...
const defaultSetting = {
  'output': 'mini',
  'organism': 'hsapiens',
  'target': 'ENSG'
};
...
```  

## Desired behaviour

Use the 'target' database option and 'converted alias' output for discriminating valid, duplicate and unrecognized IDs.

## Minimum steps to reproduce

Sample input

```bash
http://localhost:3000/api/gene-query?genes=Q8TEK3  BRPF1 hsa-let-7a-1 
```

**Comment by wxli0** [comment]
working on branch gconvert-bug

**Comment by wxli0** [comment]
The previous one worked because I used nameIndex.
I've changed nameIndex to convertedAliasIndex.
will make a pr if that's desired.

**Comment by jvwong** [comment]
Keep in mind that you have a defaultSetting 'target' set to 'ENSG'...

**Comment by wxli0** [comment]
check for 'ENSG' prefix in converted alias?

**Comment by jvwong** [comment]
What I mean is, what are you going to put in your ['geneInfo' array](https://github.com/PathwayCommons/app-ui/blob/2e3484b9d84f9867b2bdb8c599d6402447f0197e/src/server/enrichment-map/gene-validator/index.js#L45)

```js
   _.forEach(geneInfoList, info => {
...
          if (_.filter(geneInfoList, ele => ele.HGNC_symbol === info[initialAliasIndex]).length === 0) {
            geneInfo.push({ HGNC_symbol: info[initialAliasIndex], HGNC_id: info[descriptionIndex].substring(info[descriptionIndex].indexOf(';') + 5, info[descriptionIndex].length - 1) });
          }
        }
      });
....
```

**Comment by wxli0** [comment]
Maybe just push everything returned from gconvert to the array (i.e. initial alias, converted alias, name, description, namespace).
Should I use change the option 'ENSG' to 'HGNC'?

**Comment by jvwong** [comment]
## MVP use case

"1. Tell me if these input tokens are HGNC approved symbols 2. If there are duplicates".

In the AJAX call to g:Convert, your code should  use 'HGNC' as a value for the 'target' parameter.
In the response body from g:Convert, your code should look at the 'converted alias' field to determine 1. validity 2. duplicates.

What I was pointing at above is that you never use the 'target' parameter nor its output. I don't know what the 'name' or 'description' fields are or any guarantees about what they will contain. Can you find any documentation on these fields? 

## Future use case
What if I am a researcher that is interested in mouse proteins. If I change any of the 'defaultSetting' values, things start to go astray. For example, try to change 'organism' to 'Mus musculus' and 'target' to 'UNIPROTSWISSPROT' inyour defaultSettings then input 'TP53'. What do you put in the 'HGNC_symbol' and 'HGNC_id' fields now?

**Comment by wxli0** [comment]
changed the target to [HGNC](https://github.com/wxli0/app-ui/blob/gconvert-bug/src/server/enrichment-map/gene-validator/index.js#L14)
, used convertedAlias to check [validity](https://github.com/wxli0/app-ui/blob/gconvert-bug/src/server/enrichment-map/gene-validator/index.js#L35), [duplicates](https://github.com/wxli0/app-ui/blob/gconvert-bug/src/server/enrichment-map/gene-validator/index.js#L40)
and pushed the intialAlias and convertedAlias onto the array [geneInfo](https://github.com/wxli0/app-ui/blob/gconvert-bug/src/server/enrichment-map/gene-validator/index.js#L44). Is that ok?

**Comment by wxli0** [comment]
Should I add additional parameters to enable user defined options (e.g. target: ENSG)?

**Comment by wxli0** [comment]
Okay. This is the json response after the changes. Can I make the pull request?
![screen shot 2018-03-13 at 1 58 21 pm](https://user-images.githubusercontent.com/24982880/37360429-9d5f3966-26c6-11e8-9d28-cf5ca8ef80fb.png)

**Comment by jvwong** [comment]
Also consider in response:

```js
{
...
  "options": {
    "organism": "<organism>",
    "target": "<target database>",
    ...
  }
}
```

**Comment by wxli0** [comment]
![screen shot 2018-03-13 at 2 24 47 pm](https://user-images.githubusercontent.com/24982880/37361889-4f9d73d8-26ca-11e8-94af-02bb5a89f6f6.png)
[options in response](https://github.com/wxli0/app-ui/blob/gconvert-bug/src/server/enrichment-map/gene-validator/index.js#L49)

**Comment by jvwong** [comment]
looks good to me.
