### ISSUE TITLE
Expose target, organism for gconvert validator

### ISSUE THREAD

**Issue by wxli0** [PathwayCommons/app-ui#505]
on branch gconvert-target

**Comment by wxli0** [comment]
wait for #504 to be merged

**Comment by wxli0** [comment]
temporarily working based on local branch gconvert-bug
1. add to endpoint (branch gconvert-target-endpoint)
2. add to ui (branch gconvert-target-ui)

**Comment by jvwong** [comment]
I don't know the answer to this but: 

What if I put in some unrecognized 'target' or 'species' - should we be responsible for telling the client? Or does it just fail silently? I notice gconvert just responds silently (N/A for all genes with 'target=jeffwong'.

**Comment by wxli0** [comment]
#524
