### ISSUE TITLE
Reuse enrichment 'gene-validator' service for landing page UniProt lookups

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#512]
Bear with me...

## Background

To generate the landing page info box for a protein, the search client code [calls](https://github.com/PathwayCommons/app-ui/blob/df90b21a3c175c7a34b084d4d1164b936cf28265/src/client/features/search/index.js#L81) a custom service at [('/uniprotIdSearch')](https://github.com/PathwayCommons/app-ui/blob/df90b21a3c175c7a34b084d4d1164b936cf28265/src/server/routes/pc.js#L16) in an attempt to determine if the user input is associated with a human protein, that is, the code tries to [map an input to a UniProt accession](https://github.com/PathwayCommons/app-ui/blob/df90b21a3c175c7a34b084d4d1164b936cf28265/src/server/pathway-commons/search/index.js#L77):

> app-ui/src/server/pathway-commons/search/index.js 
```js
...
const uniprotIdSearch = async (query) => {
  const queries = await (processPhrase(sanitize(query.q.trim())));
  const filteredQueries = queries.filter(entry=>entry.includes('xrefid'));
  if(!_.isEmpty(filteredQueries)){
    const searchResult = await search()
      .query(query) //input query string
      .q(filteredQueries)
      .format('json')
      .fetch();
    const searchSuccess = searchResult != null
    if (searchSuccess && searchResult.searchHit.length > 0) {
      const filteredResults = searchResult.searchHit.filter(hit =>
        hit.uri.startsWith('http://identifiers.org/uniprot/') 
      );
      return filteredResults.map(hit=>_.last(hit.uri.split('/'))); //Parses and returns the Uniprot id
    }
  } 
  return [];
};
...
```

## Refactoring 

Is it worth considering re-using the ID mapping service at [/gene-query](https://github.com/PathwayCommons/app-ui/blob/df90b21a3c175c7a34b084d4d1164b936cf28265/src/server/routes/rest.js#L60)?

- Benefits
  - Can strip out bespoke 'uniprotid' search code  
  - search logic (see above) in general re-uses [string pattern matching approach](https://github.com/PathwayCommons/pathway-commons-client/blob/master/src/private/constants.js) to determine whether input token is 'ID-like' then queries PC for first 'ProteinReference' with a particular URI pattern, all which is error prone (search 'HGNC:11998').  
  - service is at least as flexible in terms of the types of inputs it can interpret (uses [g:Convert](https://biit.cs.ut.ee/gprofiler/gconvert.cgi) under the hood (e.g. search 'HS.437460'))
  - service scales to >1 gene easily

- Caveats
  - Depends on #505 so that target database (UniProt) parameter can be specified
  - Adds [g:Convert](https://github.com/PathwayCommons/app-ui/blob/df90b21a3c175c7a34b084d4d1164b936cf28265/src/server/enrichment-map/gene-validator/index.js#L16) as dependency

**Comment by logmosier** [comment]
Once issue #505/ PR #519 has been taken care of this can be easily switched over to.
