### ISSUE TITLE
Fixed version of gconvert

### ISSUE THREAD

**Issue by wxli0** [PathwayCommons/app-ui#513]
@jvwong 
Referring #449, should we use a fixed version of gconvert for validator as well?

**Comment by jvwong** [comment]
yeah good catch - makes sense if those g:Profiler services complement each other (i.e. a converted alias in g:Convert should be a valid input to g:Profiler, for that version)

**Comment by wxli0** [comment]
on local branch gconvert-version
waiting for #504 #505 to be merged
