### ISSUE TITLE
Reuse enrichment 'gene-validator' service for search 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#514]
This issue follows from #512.

## Refactoring

The suggestion is re-use the enrichment service ['/gene-query']() in the [search](https://github.com/PathwayCommons/app-ui/blob/df90b21a3c175c7a34b084d4d1164b936cf28265/src/server/pathway-commons/search/index.js#L12-L31) to test whether a user specified input token is a gene/product. 

> app-ui/src/server/pathway-commons/search/index.js
```js
...
const processPhrase = (phrase) => {
  const sourceList = [
    'uniprot',
    'chebi',
    'smpdb',
    'refseq'
  ];

  const tokens = phrase.toUpperCase().split(/\s+/g);
  
  return getHGNCData(path.join(__dirname,'/hgncSymbols.txt')).then(collection => {
    return tokens.map(token => {
      //if symbol is recognized by at least one source
      const recognized = sourceList.some(source => utilities.sourceCheck(source, token))
                              || collection.has(token.toUpperCase());
      const sanitized = sanitize(token);
      return recognized ? ( 'xrefid:' + sanitized ) : ( 'name:' + '*' + sanitized + '*' );
    });
  });
};
...
``` 

- Benefits 
  -  See #512 
  - Reduces dependency on custom HGNC text file
  - Move away from pathway-commons-client as dependency for ID recognition 

- Caveats
  - Should use original input tokens/strings in any downstream query.
  - Does not support small molecule lookups

**Comment by logmosier** [comment]
Could we still use the source list to recognize the small molecules and then use gene validator for the genes, ie:
```
const sourceList = [
    'smpdb'// and other small molecule sources
  ];
.....
 return geneValidator(query).then(collection => {
   return tokens.map(token => {
      const recognized = was recognized by geneValidator || 
               sourceList.some(source => utilities.sourceCheck(source, token))
```
It would mean we would still be dependent on pathway-commons-client but to a less extant than we are now and we would be able to recognize small molecules .

**Comment by jvwong** [comment]
As far as I understand, the work that [pathway-commons-client](https://github.com/PathwayCommons/pathway-commons-client/blob/356d8d05a8f81dc8b4e13cdd72323103ffa94af5/src/private/constants.js) is doing is pretty much testing against a regex pattern:

>/src/private/constants.js
```js
module.exports = {
  pcAddress: "https://www.pathwaycommons.org/pc2/",

  idPrefix: "pathwaycommons-js-lib:",

  dsIdValidation: {
    uniprot: id => /^([A-N,R-Z][0-9]([A-Z][A-Z, 0-9][A-Z, 0-9][0-9]){1,2})|([O,P,Q][0-9][A-Z, 0-9][A-Z, 0-9][A-Z, 0-9][0-9])(\.\d+)?$/.test(id),
    chebi: id => /^CHEBI:\d+$/.test(id) && (id.length <= ("CHEBI:".length + 6)),
    hgnc: id => /^[A-Za-z-0-9_]+(\@)?$/.test(id),
    refseq: id => /^((AC|AP|NC|NG|NM|NP|NR|NT|NW|XM|XP|XR|YP|ZP)_\d+|(NZ\_[A-Z]{4}\d+))(\.\d+)?$/.test(id),
    keggpathway: id => /^\w{2,4}\d{5}$/.test(id),
    keggdrug: id => /^D\d+$/.test(id),
    smpdb: id => /^SMP\d{5}$/.test(id),
    drugbank: id => /^DB\d{5}$/.test(id)
  }
};
```  

If we're only really doing this once, can't we just do the regex ourselves in app-ui?  

Also a subtlety of this case that is different from your uniprot/landing page: We should always use the original string/token the user typed in the downstream search and not a 'mapped' alias, specifically in the variable 'token' and the returned variable 'sanitized' above.  

For example, try search for the the micro RNA 'hsa-let-7a-1' versus the associated gene 'MIRLET7A1'.

**Comment by logmosier** [comment]
If the smpdb is the only database in there that handles small molecules then we definitely could just do the regex ourselves.
I thought gene validator also returns the initial alias that was entered along with the converted one, is this not the case @wxli0?

**Comment by jvwong** [comment]
> I thought gene validator also returns the initial alias that was entered along with the converted one, is this not the case @wxli0?

I believe that the 'initial alias' field is indeed the user input string. I just want to be clear that we don't use the 'converted alias'.

**Comment by logmosier** [comment]
Ok, that makes sense. Should we also check for chebi ids as it looks like they also have small molecule entries?

**Comment by jvwong** [comment]
Sure, CHEBI and SMPDB are for small molecules. Let the service take care of genes.
