### ISSUE TITLE
Multi-gene searches

### ISSUE THREAD

**Issue by logmosier** [PathwayCommons/app-ui#520]
Right now if the user enters multiple genes in the search the landing box does not appear and the user does not have the ability to access the interactions app. A better solution to this situation should be implemented.
I think the landing box could look something like this
![screen shot 2018-03-15 at 12 55 45 pm](https://user-images.githubusercontent.com/10948303/37478305-381a9c86-2850-11e8-8922-d26a1f234024.png)
When the user clicks on more they will be shown the content that would come up from a search of only that gene.

The interactions app could either show the paths between the genes searched or could show the nodes from both of the neighbourhoods interweaved.

Paths between:
pros- would likely be a smaller network,
cons- differs from the behaviour of single gene searches which could be confusing

Multiple neighbourhoods:
pros-in line with current behaviour, not likely to have any unexpected/confusing behaviour for the user 
cons-the network could be extremely large

Also with in the Interactions app I think there should be a way for the user to add new queried genes to the view. This could be added to the filter menu or could be included in its own menu accesed through the toolbar.

**Comment by jvwong** [comment]
Nice! I can see this working. 
One reservation with multiple neighbourhoods is the 'interweave' part - that sounds like 'merging' and could get ugly. I think for pathsbetween you can set a limit:
> limit= [Optional] graph query search distance limit (default = 1).

Your add gene idea is interesting, and starts to sound a lot like [GeneMania](https://genemania.org/) was intended to do.

Also I'm gonna leave this 'big picture' idea, that kinda looks at all of this, including @wxli0 's enrichment services as all different aspects of search...
![unified_search](https://user-images.githubusercontent.com/4706307/37486922-55428470-2866-11e8-8f2c-6c7fd56f0480.png)

**Comment by logmosier** [comment]
Waiting on PR #535

**Comment by logmosier** [comment]
The one problem I can think of is the pathsbetween gives some results that may confuse the user. For instance if you search for ATM and MDM2 which have networks like
![screen shot 2018-03-21 at 12 58 15 pm](https://user-images.githubusercontent.com/10948303/37724806-f9ce16ee-2d07-11e8-93cf-0c2a0a271b53.png)
![screen shot 2018-03-21 at 12 58 09 pm](https://user-images.githubusercontent.com/10948303/37724807-fc487702-2d07-11e8-97c7-5ae3dc1a627e.png)
you get a network like 
![screen shot 2018-03-21 at 12 57 54 pm](https://user-images.githubusercontent.com/10948303/37724833-053327cc-2d08-11e8-8ca7-3504bcd4b1a7.png)
from pathsBetween. This is without setting limit so it may be better by adjusting limit but as a user I think this would be confusing why the view with both of them is much smaller.

**Comment by jvwong** [comment]
Let's assume that the user types in two genes in hopes of answering the question: "Are there known instances where these genes (directly) interact?".  In that case, I believe the pathsbetween result is spot on, with one small exception...

I looked at the SIF responses in Cytoscape for either ATM or MDM2 (neighborhood) and both (pathsbetween). I stripped out everything but the two proteins.

A) [ATM](http://www.pathwaycommons.org/pc2/graph?source=http://identifiers.org/uniprot/Q13315&kind=neighborhood&format=txt) 
![image](https://user-images.githubusercontent.com/4706307/37737167-629a3984-2d29-11e8-82e5-643678917b5b.png)

B) [MDM2](http://www.pathwaycommons.org/pc2/graph?source=http://identifiers.org/uniprot/Q00987&kind=neighborhood&format=txt)
![image](https://user-images.githubusercontent.com/4706307/37737244-8ee2f742-2d29-11e8-99b4-44ecaeb96f96.png)

C) [ATM and MDM2](http://www.pathwaycommons.org/pc2/graph?source=http://identifiers.org/uniprot/Q13315&source=http://identifiers.org/uniprot/Q00987&kind=PATHSBETWEEN&format=txt)
![image](https://user-images.githubusercontent.com/4706307/37737285-a9ac02a8-2d29-11e8-85a1-8430752d7aa9.png)

So the dual gene search drops the interacts-with (for some reason? @IgorRodchenkov) but, looks great to me. In fact, you could probably skip the trimming step here if you want.

**Comment by IgorRodchenkov** [comment]
As far as I recall (@ozgunbabur can correct me if I am wrong), PC
PATHSBETWEEN, PATHSFROMTO graph query algorithms does not take into account
PPIs, i.e., MolecularInteraction interactions (thus PSI-MI data sources).

**Comment by IgorRodchenkov** [comment]
**Off-topic:** 
also mind issue #438 that depends on PathwayCommons/cpath2#284 and BioPAX/Paxtools#34 - both are fixed but won't have effect until the next PC release (PC10).
Hopefully, neighborhood query results won't be so large.

**Comment by ozgunbabur** [comment]
Yes, those graph queries are very process-centric. Their definition of
"distance" is based on the number of Conversions one has to hop over to
link two molecules.
