### ISSUE TITLE
Report invalid 'target', 'organism' in gconvert validator

### ISSUE THREAD

**Issue by wxli0** [PathwayCommons/app-ui#524]
following #505

**Comment by wxli0** [comment]
on branch gconvert-target-validity

**Comment by jvwong** [comment]
Should we declare here, the set of target databases? What about:

- ENSG 
- HGNC (i.e. 'Approved Symbol')
- HGNC_ACC (i.e. 'HGNC ID')
- UNIPROTSWISSPROT (i.e. 'Accession')
- ENTREZGENE (i.e. 'Official symbol')   
- ENTREZGENE_ACC (i.e. 'Gene ID')

There are problems with the validator notions of 'duplicates' etc when we start to open up other database. For example, try 'TP53' in g:Convert with 'target database = REFSEQ_MRNA'

![image](https://user-images.githubusercontent.com/4706307/37526258-3f384288-2905-11e8-9b24-eeec0208f0fc.png)

**Comment by wxli0** [comment]
Are [these](https://github.com/wxli0/app-ui/commit/b75645d11ee4c90771060575314cf8fdbcbf4606#diff-a10c2f2341a355021b49217584c19d14R256) all the target databases allowed?

**Comment by wxli0** [comment]
wait for #519 to be merged

**Comment by jvwong** [comment]
Looks fine to me. In general, we should be forgiving, case insensitive.

**Comment by wxli0** [comment]
case insensitive to both target and organism?

**Comment by jvwong** [comment]
Sure.

**Comment by jvwong** [comment]
Talked to @IgorRodchenkov about 'target' names  the app-ui validator service should use (so that we're not adding to the problem). What about:

| validator parameter | g:Convert parameter name | 
|-------------------- |----------------------|
| ENSG                       | ENSG      | 
| HGNCSYMBOL      | HGNC      |
| HGNC                       | HGNC_ACC    |
| UNIPROT                       | UNIPROT      |
| NCBIGENE                       | ENTREZGENE_ACC      |

This issue references #535 and [pull request 532](https://github.com/PathwayCommons/app-ui/pull/535#discussion_r175883937) by @logmosier.

**Comment by wxli0** [comment]
There is no UNIPROT in g:convert.
![screen shot 2018-03-21 at 9 06 05 am](https://user-images.githubusercontent.com/24982880/37711459-2f08e3be-2ce7-11e8-8202-9b306ef7053b.png)

**Comment by jvwong** [comment]
| validator parameter | g:Convert parameter name | 
|-------------------- |----------------------|
| ENSG                       | ENSG      | 
| HGNCSYMBOL      | HGNC      |
| HGNC                       | HGNC_ACC    |
| UNIPROT                       | UNIPROTSWISSPROT      |
| NCBIGENE                       | ENTREZGENE_ACC      |

**Comment by wxli0** [comment]
Something doesn't work as expected when using convertedAlias to identify duplicates. When term IDs are used as query, gConvert finds all genes in each pathway, and since there are some overlapped genes (in convertedAlias) between pathways (e.g. CCL3 is in both GO:0043525 GO:0043523), our service reports GO:0043525 GO:0043523 as duplicate. 

![screen shot 2018-03-22 at 9 57 58 am](https://user-images.githubusercontent.com/24982880/37775101-6734a08a-2db8-11e8-9f9b-71da7be55359.png)

Should we use initialAlias to check for duplicates instead?

**Comment by jvwong** [comment]
The result you are observing, in my opinion, is the expected result. 
I look at the 'duplicate' as referring to the 'converted alias'. For example, put in 'TP53' and  'P04637', with target 'HGNCSYMBOL' - which should tell me they map to the same gene. If you looked at the initial alias, these would NOT be declared duplicates, which is erroneous.

Someone putting in a Gene Ontology term is a weird edge case, I agree and you are right to point out the behaviour of our service (g:Convert). You could also look at this as a cool side effect: You can put in a go term and get the genes!

**Comment by wxli0** [comment]
Reporting GO terms as duplicates still looks weird to me. Two GO terms are the same if all associated genes in the pathways are the same. 
My suggestion is to:
check if it is a pathway ID, if it is, use intialAlias to check for duplicates; otherwise, use convertedAlias. Does it sound better?

**Comment by jvwong** [comment]
Our service isn't intended to convert pathway IDs. It's a weird side-effect of the g:Convert. But you are right to ensure that our service doesn't return confusing results.

I'd rather check if it conforms to the "GO:XXXXXXX" pattern and return as unrecognized.

Think about this: What if g:Convert decides to switch off their service? What if we wanted to switch out g:Convert for some other service, perhaps our own?
