### ISSUE TITLE
Expose organism for emap service

### ISSUE THREAD

**Issue by wxli0** [PathwayCommons/app-ui#525]
Should we expose organism for other species for emap service? Validator and enrichment both support changing organism from the endpoint. Or since there're 254 in total, should we only expose specific ones?

**Comment by jvwong** [comment]
So this is a bit nuanced:

For the enrichment analysis - Reactome, as I understand it, only has pathways for human. GO will have gene sets for human and other species. If you run an enrichment with mouse or rat (not human) and select Reactome i think g:GOst just ignores Reactome (can you find out?).

Also, Baderlab (Ruth) provides [gene sets (GMT)](http://download.baderlab.org/EM_Genesets/current_release/) for human ('hsapiens'), mouse ('mmusculus') and rat (rattus norvegicus - I don't know what g:profiler code is for this - can you find out?). 

So let's make life easy, let's only support human for enrichment and emap.

**Comment by wxli0** [comment]
1. Yes. GOst doesn't report Reactome ID though some genes exist in the Reactome pathway from the gmt file. The checkbox for selecting Reactome database is even disable for some species.
2. You can get the gmt files for mmusculus from [GOst->select organism -> show advanced options -> NAME](https://biit.cs.ut.ee/gprofiler/gmt/gprofiler_mmusculus.NAME.gmt.zip)
