### ISSUE TITLE
emap service: exposing options (weighting, cutoff) for edge similarity

### ISSUE THREAD

**Issue by wxli0** [PathwayCommons/app-ui#526]
1. When calculating similarity rate, expose weight of JC and OC (on branch emap-weight)
    - expose JCWeight, OCWeight=1-JCWeight
    - number between 0 and 1, inclusive
2. Expose cutoff point (on branch emap-cutoff)
    - number between 0 and 1, inclusive

**Comment by jvwong** [comment]
Great. Can we make these issue titles as informative as possible: 'Exposing options (weighting, cutoff) for edge similarity'.

**Comment by wxli0** [comment]
I feel the current pr #529 which only exposes JCWeight might not be flexible for clients.
The following could be better:
1. expose JCWeight, OCWeight
2. when JCWeight is undefined, OCWeight = 1-JCWeight
    when OCWeight is undefined, JCWeight = 1-OCWeight
3. check JCWeight+OCWeight=1 when both are defined. Report errors if not satisfied.
