### ISSUE TITLE
Enrichment service: report warnings from gprofiler service call

### ISSUE THREAD

**Issue by wxli0** [PathwayCommons/app-ui#537]
Extract #warning lines from gprofiler response and parse it into unrecognized and duplicate.
![screen shot 2018-03-19 at 9 57 13 am](https://user-images.githubusercontent.com/24982880/37599842-13ff7bfa-2b5c-11e8-92b5-e3f717fecde2.png)
on branch enrichment-warning

**Comment by jvwong** [comment]
Good catch. Could you reproduce here what your JSON response schema looks like currently?

**Comment by wxli0** [comment]
{unrecognized: ['ATP'],
duplicate: ['AFF4'],
enrichmentResult: {options: {orderedQuery:...,...}, {pathwayInfo: {"GO:0006354":{"signf":"!","pvalue":"8.70e-03","T":"124","Q":"1","tType":"BP","tGroup":"3","tName":"   DNA-templated transcription, elongation","tDepth":"1","Q&T":"1","Q&T/Q":"1.000","Q&T/T":"0.008","Q&TList":"AFF4"},"GO:0006368":{"signf":"!","pvalue":"8.70e-03","T":"100","Q":"1","tType":"BP","tGroup":"3","tName":"   transcription elongation from RNA polymerase II promoter","tDepth":"1","Q&T":"1","Q&T/Q":"1.000","Q&T/T":"0.010","Q&TList":"AFF4"},"REAC:75955":{"signf":"!","pvalue":"7.75e-03","T":"61","Q":"1","tType":"rea","tGroup":"5","tName":"   RNA Polymerase II Transcription Elongation","tDepth":"1","Q&T":"1","Q&T/Q":"1.000","Q&T/T":"0.016","Q&TList":"AFF4"},"REAC:112382":{"signf":"!","pvalue":"7.75e-03","T":"61","Q":"1","tType":"rea","tGroup":"5","tName":"    Formation of RNA Pol II elongation complex ","tDepth":"2","Q&T":"1","Q&T/Q":"1.000","Q&T/T":"0.016","Q&TList":"AFF4"},"REAC:674695":{"signf":"!","pvalue":"7.75e-03","T":"83","Q":"1","tType":"rea","tGroup":"6","tName":"   RNA Polymerase II Pre-transcription Events","tDepth":"1","Q&T":"1","Q&T/Q":"1.000","Q&T/T":"0.012","Q&TList":"AFF4"}}}}

**Comment by wxli0** [comment]
waiting for #538 to be merged

**Comment by jvwong** [comment]
What is "signif": "!" mean?
Also can you format the json for readability?

**Comment by wxli0** [comment]
The exclamation mark stands for significant p-value according to [gprofiler help](https://biit.cs.ut.ee/gprofiler/help.cgi?help_id=23)
Is this one readble? The pathwayInfo field is a map keyed by pathway IDs.
{unrecognized: ['ATP'],
duplicate: ['AFF4'],
enrichmentResult: 
{options: {orderedQuery:...,...}, 
{pathwayInfo: 
{"GO:0006354":{"signf":"!","pvalue":"8.70e-03","T":"124","Q":"1","tType":"BP","tGroup":"3","tName":" DNA-templated transcription, elongation","tDepth":"1","Q&T":"1","Q&T/Q":"1.000","Q&T/T":"0.008","Q&TList":"AFF4”},
"GO:0006368":{"signf":"!","pvalue":"8.70e-03","T":"100","Q":"1","tType":"BP","tGroup":"3","tName":" transcription elongation from RNA polymerase II promoter","tDepth":"1","Q&T":"1","Q&T/Q":"1.000","Q&T/T":"0.010","Q&TList":"AFF4”},
"REAC:75955":{"signf":"!","pvalue":"7.75e-03","T":"61","Q":"1","tType":"rea","tGroup":"5","tName":" RNA Polymerase II Transcription Elongation","tDepth":"1","Q&T":"1","Q&T/Q":"1.000","Q&T/T":"0.016","Q&TList":"AFF4”},
"REAC:112382":{"signf":"!","pvalue":"7.75e-03","T":"61","Q":"1","tType":"rea","tGroup":"5","tName":" Formation of RNA Pol II elongation complex ","tDepth":"2","Q&T":"1","Q&T/Q":"1.000","Q&T/T":"0.016","Q&TList":"AFF4”},
"REAC:674695":{"signf":"!","pvalue":"7.75e-03","T":"83","Q":"1","tType":"rea","tGroup":"6","tName":" RNA Polymerase II Pre-transcription Events","tDepth":"1","Q&T":"1","Q&T/Q":"1.000","Q&T/T":"0.012","Q&TList":"AFF4"}}}}

**Comment by jvwong** [comment]
The "signf" field explained in https://github.com/PathwayCommons/app-ui/issues/533#issuecomment-374272306

**Comment by wxli0** [comment]
working on local branch enrichment-backup/enrichment-warning cloned from remote branch enrichment-response
