### ISSUE TITLE
Throw error when receiving invalid inputs for enrichment service

### ISSUE THREAD

**Issue by wxli0** [PathwayCommons/app-ui#544]
following #533, #541, referring to [gprofiler help](https://biit.cs.ut.ee/gprofiler/help.cgi)
- orderedQuery
   - throw error if not one of 1, 0
- userThr (default: 0.05)
   - throw error if out of [0,1]
- minSetSize
   - throw error if not number
- maxSetSize
   - throw error if not number
   - less than minSetSize
- threshold_algo (default fdr)
   - throw error if not one of "analytical", "bonferroni", "fdr"
- custbg
   - throw error if 
- custbgCb
   - throw error if not one of 1, 0

**Comment by wxli0** [comment]
waiting for #545

**Comment by wxli0** [comment]
working on local branch enrichment-backup/enrichment-error copied from enrichment-backup/enrichment-signf

**Comment by wxli0** [comment]
@jvwong How do we check custbg is space-separated list of valid symbols? [gprofiler help ](https://biit.cs.ut.ee/gprofiler/help.cgi?help_id=55)
I think duplicate symbols in custbg is okay as long as each one is valid. Can we post the list to our validator service and check the returned unrecognized array?

**Comment by jvwong** [comment]
Good catch. 
Correct me if I am wrong, but for the 'enrichment' service, we assume that the client is sending recognized queries (genes). So let us assume the same thing for background (genes). 
So let the user/client validate their gene lists on their own.

**Comment by jvwong** [comment]
That being said, does g:GOSt return relevant errors (i.e. background gene not recognized)? Maybe we can forward those. If not, forget about it for now.

**Comment by wxli0** [comment]
g:Gost doesn't return errors if unrecognized. 
Ok. will ignore it.

**Comment by wxli0** [comment]
userThr should be in (0, 1], when userThr=0, g:GOSt treats it as 1.

**Comment by wxli0** [comment]
check query (genes) is an array.
