### ISSUE TITLE
emap service: gene set lookup

### ISSUE THREAD

**Issue by wxli0** [PathwayCommons/app-ui#560]
following #524 
I came across this side effect of g:Convert during testing, which can be used in our emap service. Is it better to reimplement gene set look up process by parsing the response from g:Convert instead of storing a huge static file in pathwayTable folder?

**Comment by jvwong** [comment]
Correct me if I am wrong but will this mean that everytime the app-ui is built, the app will make 17 400 calls to g:Convert?

```js
$ wc -l hsapiens.pathways.NAME.gmt
  17489 hsapiens.pathways.NAME.gmt
```

**Comment by jvwong** [comment]
Actually I see what you are saying: You want to re-use the g:Convert to grab the genes only for those in the emap input pathwayID list (lazy-load)?
 
I wonder more and more whether that borders on 'overloading/abusing' their service?

**Comment by wxli0** [comment]
> Correct me if I am wrong but will this mean that everytime the app-ui is built, the app will make 17 400 calls to g:Convert?
No. We will only make one call to g:Convert by posting GO terms in query once.
![screen shot 2018-03-23 at 1 44 01 pm](https://user-images.githubusercontent.com/24982880/37845246-653f8f2c-2ea0-11e8-87a6-9846475c6fe5.png)

**Comment by wxli0** [comment]
> I wonder more and more whether that borders on 'overloading/abusing' their service? Would that be horribly slow (what if I had 300 GO terms?)

So there is a tradeoff. 
current solution: storing huge gmt file in the folder. 
using g:convert: can be slower. I will try with more than 300 GO terms and see how long it takes.

**Comment by jvwong** [comment]
This makes sense. 

Perhaps you can make this an official, but unadvertised part of validator: If you input a  'GO:XXXXXXX' pattern, we will try to report:

```js
{
	"options": {
		"target": "<target>",
		"organism": "<organism>"
	},
	"unrecognized": [
		"GO:123JEFFW"
	],
	"duplicate": [],
	"geneInfo": [
		{
			"initialAlias": "GO:0006368",
			"convertedAlias": [
                            "EAPP", "RNF8", "TAF1L", ..., "ENY2"
                        ]
		},		
                ...
}
```

**Comment by wxli0** [comment]
Yeah. It does take much longer time for g:Convert when the size is 1000 terms (gconvert takes 30s whereas our solution takes 38ms). I think we should stick with the current solution.
