### ISSUE TITLE
"Detailed Views" (SBGN-PD) of an interaction lacks title etc  

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#566]
If I examine the tooltip for an interaction it provides useful information including a title, 'Pubmed' links, and 'Detailed Views'. However, the 'detailed view' of an interaction is typically bereft  of any useful details like name, info.

1. Can we use the tooltip title in the SBGN detailed view ? Can we pass it, get it somewhere else?  
2. Should we punt 'info'? I can't recall any occasion where this has anything useful. Pathways from REACTOME have reasonably good stuff but that's pretty much it.

For example, search and [view interactions for IL4](http://localhost:3000/interactions?ID=P05112) then view 'IL4 controls phosphorylation of JAK2'. 

![image](https://user-images.githubusercontent.com/4706307/37848920-31502d64-2eac-11e8-98bf-c5f044bcb64c.png)

Clicking the first detailed view interaction gives a nice SBGN-PD view:

![image](https://user-images.githubusercontent.com/4706307/37849173-0c146dca-2ead-11e8-8fa6-003cb6782b31.png)

**Comment by logmosier** [comment]
1. Are you saying that instead of Unknown network we would have IL4 controls phosphorylation of JAK2 as the name of the network? If so I think this is possible.
2. After a quick look it does appear that reactome, and some panther pathways have some useful information but that is about it, so I don't think it is that useful.

**Comment by jvwong** [comment]
>Are you saying that instead of Unknown network we would have IL4 controls phosphorylation of JAK2 as the name of the network? If so I think this is possible.

Yes. 
Where does this tooltip title even come from? Can we get/generate them directly in the SBGN-PD viewer? Have you seen edge tooltips with no useful name?

>After a quick look it does appear that reactome, and some panther pathways have some useful information but that is about it, so I don't think it is that useful.

There is this illusion that pathway comments have all this useful text. This motivated the 'info' panel and the idea that it could be used for boosting Google indexing -  but I'm not convinced (for cases other than Reactome).

**Comment by logmosier** [comment]
The tooltip title comes directly from the SIF file entry so any valid SIF entry will have a title, I dont think there would be any edge cases that would not also break the format of the SIF file. I don't know if we could generate the name in the SBGN-PD viewer we would likely have to pass it in.

**Comment by jvwong** [comment]
The title is likely templated in from the BioPAX to SIF converter. That is, the pattern is fixed and the genes are inserted:

<genename1> controls phosphorylation of <genename2> 
<genename1> controls expression of <genename2> 

![image](https://user-images.githubusercontent.com/4706307/37852449-01b458d4-2eb9-11e8-84d4-24a15a9691dd.png)

**Comment by jvwong** [comment]
Is passing it in doable? I would also say punt the info panel unless there's some content I'm missing.

**Comment by logmosier** [comment]
I think it is doable, may need to pass it in with the query and add that as a option for the view feature though. Also Are you talking about removing the info panel just from the detailed view links or entirely removing it, just want to make sure?

**Comment by jvwong** [comment]
> I think it is doable, may need to pass it in with the query and add that as a option for the view feature though. 

OK - I guess someone could alter that via the url param? Anyways, it's more confusing to present 'Unknown network' to a user every time.

> Also Are you talking about removing the info panel just from the detailed view links or entirely removing it, just want to make sure?

Only the detailed view. I have yet to see an instance where the info contains more than 'REPLACED ...".

**Comment by jvwong** [comment]
>  I wonder if it would make more sense to make a seperate viewer to handle these links.

I am not sure what you mean by 'separate'?

**Comment by logmosier** [comment]
Like instead of calling the view feature some other code would be used to handle the detailed views. After looking at it a little bit more I dont think this will be need.

**Comment by jvwong** [comment]
Note to self: Interesting place to experiment with BioPAX to English translation?
