### ISSUE TITLE
g:Convert validator service:  reorganize output when input is pathway ID

### ISSUE THREAD

**Issue by wxli0** [PathwayCommons/app-ui#567]
referring to https://github.com/PathwayCommons/app-ui/issues/560#issuecomment-375757268
When input is pathway ID, convertedAlias should be all the genes in the pathway.
```{
	"options": {
		"target": "<target>",
		"organism": "<organism>"
	},
	"unrecognized": [
		"GO:123JEFFW"
	],
	"duplicate": [],
	"geneInfo": [
		{
			"initialAlias": "GO:0006368",
			"convertedAlias": [
                            "EAPP", "RNF8", "TAF1L", ..., "ENY2"
                        ]
		},		
                ...
}
```

**Comment by jvwong** [comment]
FYI you can format code snippets in Markdown by surrounding it with three backticks.
https://help.github.com/articles/creating-and-highlighting-code-blocks/
