### ISSUE TITLE
Enrichment service optional parameters aren't respected

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#573]
## Environment info

- Browser version (client) :
- Node.js version (server) : 8.8.1

## Current (buggy) behaviour

Ignores some of the optional parameters supplied.

## Desired behaviour

Respect my optional parameters.

## Minimum steps to reproduce

POST
- http://localhost:3000/api/enrichment/
- Content-Type: application/x-www-form-urlencoded
- parameters
  - genes
    - DOT1L AFF4 NAP1L3 BRPF1 TCF20 HLTF SIRT1 TDG SUV39H2 CBX7 DNMT1 DPY30 ING5 MLLT6 CHD1L USP27X BRPF3 ELP4 HCFC1 MARCH5 SCML2 PRDM10 SUPT16H TRIM24 GTF2H1 KDM3A PAF1 PCGF5 BAZ1B NCOA1 UBE2B SGF29 KDM5B MTA3 PCMT1 GTF3C4 MTA2 RBBP4 RNF20 SETD2 SSRP1 MBD1 POLR2B TP53BP1 UBR7 ARID4B ASH1L BRD4 HAT1 HDAC1 KAT2A MBD3 MSL3 RPA3 BAZ2A JMJD6 PHF7 SIN3B SP100 ZMYND11 
   - significant
     - 0
  - userThr 
    - 0.001

Should return no results because of the userThr. In reality returns results as if userThr is absent.

## Notes

My guess is that your [userSetting keys are different from you defaultSetting keys](https://github.com/PathwayCommons/app-ui/blob/75f82d44928905c19a5e9cb63805d2eaf3754c88/src/server/enrichment-map/enrichment/enrichment.js#L52) (snake vs camel casing) so the _.assign isn't doing its job

> 
```js
...
const defaultSetting = {
  "output": "mini",
  "organism": "hsapiens",
  "significant": 0,
  "sort_by_structure": 1,
  "ordered_query": 0,
  "as_ranges": 0,
  "no_iea": 1,
  "underrep": 0,
  "hierfiltering": "none",
  "user_thr": 0.05,
  "min_set_size": 5,
  "max_set_size": 200,
  "threshold_algo": "fdr",
  "domain_size_type": "annotated",
  "custbg": [],
  "custbg_cb": 0,
  "sf_GO:BP": 1,
  "sf_REAC": 1,
};
const gProfilerURL = "https://biit.cs.ut.ee/gprofiler_archive3/r1741_e90_eg37/web/";


const enrichment = (query, userSetting) => {
  const promise = new Promise((resolve, reject) => {
    const formData = _.assign({}, defaultSetting, { "query": query }, userSetting);
    const orderedQueryVal = Number(formData.ordered_query);
...
```

**Comment by wxli0** [comment]
It's one of the prs to be reviewed.
https://github.com/PathwayCommons/app-ui/pull/553/files

**Comment by jvwong** [comment]
bah, I knew/saw this earlier but forgot. Sorry about the bloat.
