### ISSUE TITLE
Network view node search box: Open by default

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#575]
## Description of new feature

Upon viewing a network, the the search box is not visible/open. Open by default.

## Motivation for new feature

Open by default to allow quick access to search. 

![image](https://user-images.githubusercontent.com/4706307/37876801-d95a0bf0-301f-11e8-9a9c-87d35a7cc530.png)

**Comment by d2fong** [comment]
Should we always have it open and get rid of the ability to close it?

**Comment by maxkfranz** [comment]
I think Dylan's suggestion makes sense for most cases.

The only reason I can think of where we'd want to keep the togglability is for small screens, like mobile.  For small screens, it might make sense to keep the toggle button and also have the search closed by default.

**Comment by d2fong** [comment]
I ask because it was Caitlin's idea in the PR.  I tested it on my phone I think it looks okay if we got rid of the search icon.

**Comment by maxkfranz** [comment]
On small mobile screens, does the tool bar always fit on a single line?  If not, we may need to tweak the CSS so it does.

**Comment by CaitlinOCallaghan** [comment]
Yes, the tool bar always fits on mobile version. Here is the view from an iPhone 5: 
![image](https://user-images.githubusercontent.com/38890251/40008161-aabcf7b6-576c-11e8-9b3a-577b2bce6bde.png)

**Comment by jvwong** [comment]
OK let's get a feature branch --> pull request in for dropping the icon, then reference this issue.
