### ISSUE TITLE
gene-validator: NCBIGENE should accept and return integer

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#592]
## Description of new feature

NCBI Gene IDs are integers. For example, [TP53](https://www.ncbi.nlm.nih.gov/gene/7157) has a gene identifier `7157`.  

## Motivation for new feature

The client should expect to  input or output for NCBI Gene IDs that are integers. Currently, the service uses g:Convert-specific formatting (prefix). 

For instance, to validate the NCBI Gene ID `7157`, the user must input: `http://localhost:3000/api/gene-query?target=HGNC&genes=ENTREZGENE_ACC:7157`. The  `ENTREZGENE_ACC` is not to my knowledge official. Likewise, when the target database is NCBIGENE, the prefix is also returned:

> http://localhost:3000/api/gene-query?target=NCBIGENE&genes=TP53 
```js
{
	"options": {
		"target": "ENTREZGENE_ACC",
		"organism": "hsapiens"
	},
	"unrecognized": [],
	"duplicate": [],
	"geneInfo": [
		{
			"initialAlias": "TP53",
			"convertedAlias": "ENTREZGENE_ACC:7157"
		}
	]
}
```

**NB**: The above does NOT apply to HGNC IDs, as these DO in fact contain a prefix.

**Comment by wxli0** [comment]
on branch gconvert-NCBI

**Comment by wxli0** [comment]
https://github.com/PathwayCommons/app-ui/issues/584#issuecomment-378401207 
set prefix to ENTREZGENE_ACC
