### ISSUE TITLE
Enrichment service hangs when parameters our of bounds; accepts non-sensical

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#594]
## Environment info

- Browser version (client) :
- Node.js version (server) : v8.8.1

## Current (buggy) behaviour

Sending a request to `enrichment` service with out-of-bounds/bad parameters does not return.

## Desired behaviour

Return useful error message to client if parameters out of bounds.

## Minimum steps to reproduce

POST 
http://localhost:3000/api/enrichment/
genes = DOT1L AFF4 NAP1L3 BRPF1 TCF20 HLTF SIRT1 TDG SUV39H2 CBX7 DNMT1 DPY30 ING5 MLLT6 CHD1L USP27X BRPF3 ELP4 HCFC1 MARCH5 SCML2 PRDM10 SUPT16H TRIM24 GTF2H1 KDM3A PAF1 PCGF5 BAZ1B NCOA1 UBE2B SGF29 KDM5B MTA3 PCMT1 GTF3C4 MTA2 RBBP4 RNF20 SETD2 SSRP1 MBD1 POLR2B TP53BP1 UBR7 ARID4B ASH1L BRD4 HAT1 HDAC1 KAT2A MBD3 MSL3 RPA3 BAZ2A JMJD6 PHF7 SIN3B SP100 ZMYND11 

then try any of the following individually or together: 

userThr = 1.1
minSetSize = -1 (this makes no sense. why does service return this as acceptable -1?)
maxSetSize = Inf

**Comment by wxli0** [comment]
> userThr = 1.1
> maxSetSize = Inf

These two should be resolved once #553 is merged since [#552](https://github.com/PathwayCommons/app-ui/pull/552/files) has been merged.




> minSetSize = -1 (this makes no sense. why does service return this as acceptable -1?)

ok. will add this one after #553 is merged.
