### ISSUE TITLE
Interactions Tooltip: Remove 'more' option when only a few 'Links'; Is 'Links' a good description?  

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#598]
## Description of new feature

The Interations tooltip displays 'Links' which (often?) lists the first PubMed link followed by 'more' option to expand the list. 

1. Should display all in the list when there are just a few (i.e. one link that is hidden).   
2. Do we put anything here other than PubMed links? If not, then 'Links' is unnecesary.

## Motivation for new feature

Reduce unnecesary clicks  by user. Reduce uninformative text.

**Comment by jvwong** [comment]
(Note to @jvwong: Future work on displaying useful publicationxref data).

**Comment by logmosier** [comment]
2. The expression interactions often have both links to pubmed and reactome links

**Comment by logmosier** [comment]
1.  The links in the interaction tooltips currently use the same code as the links in the viewer tooltips. Should this change be applied to the links in the viewer tooltips as well or should it only be applied to the interaction tooltips links.
2. Now that reactome links have been moved under 'Detailed Views' (#613 ) I believe only Pubmed links will appear under links in the interaction tooltips on edges (on nodes there will be other links as well).

**Comment by jvwong** [comment]
> 1. The links in the interaction tooltips currently use the same code as the links in the viewer tooltips. Should this change be applied to the links in the viewer tooltips as well or should it only be applied to the interaction tooltips links.

No - don't alter the SBGN-Viewer tooltip 'Links'. I have this tabled 'elsewhere'.

> 2. Now that reactome links have been moved under 'Detailed Views' (#613 ) I believe only Pubmed links will appear under links in the interaction tooltips on edges (on nodes there will be other links as well).

Let's rename 'Links' as 'PubMed' and stop there. We can log another issue to [e-fetch](https://www.ncbi.nlm.nih.gov/books/NBK25499/#chapter4.EFetch) better citation info.

![image](https://user-images.githubusercontent.com/4706307/38336655-8b39fe58-3830-11e8-9c54-3a08c172f7e5.png)

**Comment by jvwong** [comment]
logged in #620
