### ISSUE TITLE
Remove comment headers from src/client, src/server/routes

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#6]
Example comment header to remove:

```js
/**
    Pathway Commons Central Data Cache

    Pathway Commons Server Routing
    index.js

    Purpose : Defines basic routes for the server

    Requires : None

    Effects : None

    Note : None

    TODO: None

    @author Geoff Elder, Jonah Dlin
    @version 1.1 2017/10/10
**/
```

Generally, these can get stale/out of date very fast.  

- Your names will be recorded in the package.json field.  They don't have to be in every file. https://github.com/PathwayCommons/app-ui/issues/5 

- history, dates and versions are tracked by git

- todos, notes, etc should be tracked by github issues

**Comment by jonahdlin** [comment]
Submitted new PR with fix #9
