### ISSUE TITLE
Interactions view: Differences in edge tooltip information display

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#606]
Originally I was trying to understand what eSIF data maps to the tooltip 'Links' versus 'Detailed View'. I noticed a difference in the way that tooltip information for edges is displayed, despite the observation that the eSIF fields are the same.  Why?

Case:  Examining [IL4 interactions](http://localhost:3000/interactions?ID=P05112), filtered for expression.  In particular, I was looking at:

 'ANXA1 controls expression of TNF' 
![anxa1_tnf_expression](https://user-images.githubusercontent.com/4706307/38256051-67818130-372b-11e8-9ec4-9af2519325c5.png)

versus 'IL4 controls expression of ANXA1'. 
![il4_anxa1_expression](https://user-images.githubusercontent.com/4706307/38256063-6cf16338-372b-11e8-8c35-7dbe99edc540.png)

Why are 'Detailed Views' specific to the former?

**Comment by logmosier** [comment]
Originally the 'Detailed Views' where handled the same as the other links with the database name being 'Pathway Commons'. 
![](https://user-images.githubusercontent.com/4706307/37098679-7d5c4ad4-21ec-11e8-970e-a7f97503cfc6.png)
The changes to move the 'Detailed Views' under 'Detailed Views' and not Links came from issue #466.  This may have been because of some misunderstanding on my end but I thought that was the change you were asking for in the issue.

**Comment by jvwong** [comment]
I don't exactly follow. I am suggesting that 

1. Anything under eSIF `MEDIATOR_IDS` gets mapped to a link under `Detailed Views`
2. Anything under eSIF `INTERACTION_PUBMED_ID` gets mapped to link under `PubMed`

**Comment by logmosier** [comment]
So in the example you gave at the start of this issue the Reactome links would be placed under 'Detailed Views' in the second picture so the tool tips would be formatted like:
picture 1:
__________________________________________________________
`PubMed:....`
`Detailed Views: Interaction 1, Interaction 2 `
__________________________________________________________
picture 2:
__________________________________________________________
`PubMed:....`
`Detailed Views:`
`Pathway Commons: Interaction 1, Interaction 2,`
`Reactome:... `
______________________________________________________________
is that what you are thinking?

**Comment by jvwong** [comment]
Yes. 

One question: Would eSIF `INTERACTION_DATA_SOURCE` ever have more than one entry (like you are representing under picture 2)?

**Comment by logmosier** [comment]
> One question: Would eSIF INTERACTION_DATA_SOURCE ever have more than one entry (like you are representing under picture 2)?

Yes 
![screen shot 2018-04-03 at 2 17 18 pm](https://user-images.githubusercontent.com/10948303/38267528-ccf242ca-3749-11e8-9600-35b09d3b44c8.png)
![screen shot 2018-04-03 at 2 17 28 pm](https://user-images.githubusercontent.com/10948303/38267529-ccfe0150-3749-11e8-9400-8e2c23bdbe74.png)

**Comment by logmosier** [comment]
I can have the reactome links point to either our [view app](http://localhost:3000/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-6797712) or to their [website](http://reactome.org/content/detail/R-HSA-6797712) which do you think would be best?

**Comment by jvwong** [comment]
Yes, since in SIF the datasource-to-URI is ambiguous, what you have above is fine. Saying it's Reactome doesn't really give a user all that much more information; they have to view the SBGN.
