### ISSUE TITLE
Emap service http status code

### ISSUE THREAD

**Issue by wxli0** [PathwayCommons/app-ui#609]
According to [wiki](https://github.com/PathwayCommons/app-ui/wiki/Enrichment-Map-Services), send  status code 201 when having unrecognized pathwayId in 'pathwayInfoList'

on branch emap-status

**Comment by jvwong** [comment]
I think 201 is reserved for creating a resource. Isn't 200 perfectly fine? The response correctly files those it can't find under "unrecognized".

**Comment by wxli0** [comment]
I was trying to think of a code other than 200 to differentiate the response when containing unrecognized IDs (warning) from normal ones. Is it necessary?

**Comment by jvwong** [comment]
I don't this so. This is a similar case to validator; just return in "unrecognized". To be honest, I'm not sure what the g:Profiler GMT file covers in terms of GO IDs...

**Comment by wxli0** [comment]
Ok.
