### ISSUE TITLE
Interactions tooltip: Display PubMed citation information 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#620]
TODO - related to #598

**Comment by jvwong** [comment]
I was actually referring to the 'interaction' viewer tooltip. There should probably be some common service for this since it's used more than one place.

**Comment by MichaelWrana** [comment]
So I should try and modify the `Interaction` protein-interaction tooltip to have the PubMed citation info like the `View` protein-interaction tooltip?

**Comment by jvwong** [comment]
Closing - part of refactoring
