### ISSUE TITLE
Enrichment service: expose lowerBound as optional parameter

### ISSUE THREAD

**Issue by wxli0** [PathwayCommons/app-ui#622]
From our lab meeting last week, when the query size is large enough, should we expose the lowerBound of the size of qAndTList as a filter for the pathways returned from enrichment service? i.e. return the pathways whose qAndTList sizes are >= lowerBound. And 0 by default.

**Comment by wxli0** [comment]
@jvwong Is this what Gary mentioned at the meeting?

**Comment by jvwong** [comment]
I suppose we could design this to be completely generic. For instance, I give you a set of key, rule and you filter acordingly?

**Comment by wxli0** [comment]
In the context of enrichment service, it would be expose an optional parameter "rule" (a function) from the endpoint?

**Comment by wxli0** [comment]
[this one](https://github.com/cytoscape/cytoscape.js/blob/master/documentation/md/collection/filter.md)?

**Comment by jvwong** [comment]
Yes, which argues that point that the client could filter on a cytoscapejs object they could create from the emap output. 
However, if the client was using only 'enrichment' service, other than pValue (recall usrThr parameter), you would need some sort of key-rule functionality. Question is, does anyone really care about this function? I suppose you'd have to get feedback...
