### ISSUE TITLE
Consider having wrapper webservices for external resources

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/app-ui#623]
See https://github.com/PathwayCommons/app-ui/blob/development/src/client/services/server-api/index.js#L36

E.g. EBI

Consider caching, rate limiting, etc.

**Comment by jvwong** [comment]
Commit specific line: https://github.com/PathwayCommons/app-ui/blob/f97b32566cd8d8feba1fd130c86c45da6bc1caae/src/client/services/server-api/index.js#L43
