### ISSUE TITLE
Consider removing text info for interactions

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/app-ui#626]
https://github.com/PathwayCommons/app-ui/blob/399536631ac23de5a31ce56f5880ad40f2202b54/src/client/features/view/index.js#L35

**Comment by logmosier** [comment]
Even though the issue is 'for interactions' should we maybe consider just removing the info tab from the viewer as it very rarely(only really reactome pathways) has use full information?

**Comment by jvwong** [comment]
Let's keep the pathway info tab. Reactome is a popular source and I would hate to lose that info they provide.
