### ISSUE TITLE
Refactor parseGProfilerResponse

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/app-ui#636]
https://github.com/PathwayCommons/app-ui/blob/development/src/server/enrichment-map/enrichment/enrichment.js#L14

- Avoid doing `gProfilerResponse.split('\n')` over and over
- Just filter the array `arr.filter( (el, index) => true | false )` : `lines.filter( (line, lineNumber) => true|false )`

**Comment by wxli0** [comment]
on branch gconvert-parse
