### ISSUE TITLE
Consider removing options from enrichment response, validator reponse

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/app-ui#637]
https://github.com/PathwayCommons/app-ui/blob/399536631ac23de5a31ce56f5880ad40f2202b54/src/server/enrichment-map/enrichment/enrichment.js#L103

**Comment by wxli0** [comment]
https://github.com/PathwayCommons/app-ui/blob/development/src/server/enrichment-map/gene-validator/index.js#L90

**Comment by wxli0** [comment]
wait on pr #612
