### ISSUE TITLE
Avoid duplicate expensive operations : DRY

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/app-ui#638]
e.g. edge.edgeId.split('_')

https://github.com/PathwayCommons/app-ui/blob/development/src/server/enrichment-map/emap/generateGraphInfo.js#L78-L79

https://github.com/PathwayCommons/app-ui/blob/development/src/server/enrichment-map/emap/intersect.js#L21

**Comment by wxli0** [comment]
wait on pr #612
