### ISSUE TITLE
Interactions view accept URL parameter, rather than 'ID'

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#647]
## Description of new feature

Accept a URL parameter. Start the transition to a more generic and flexible 'SIF' viewer, similar to the 'pathway'/SBGN viewer. Expose [control](https://github.com/PathwayCommons/app-ui/blob/a15dda9842c2d2a6dd5a8dbb7f1abb88ddbba4dc/src/client/features/interactions/index.js#L57) of viewer content.  

## Motivation for new feature

A user can view any SIF resource. For instance, any particular output from PC get/graph.

**Comment by jvwong** [comment]
Caveat: Security issues associated with accepting URI

**Comment by jvwong** [comment]
Should be explicit parameter different from, for example, NCBI gene ID.

**Comment by jvwong** [comment]
Clarifying the type of input parameter. 

Input parameter
  -  'source' from [PC Graph](http://www.pathwaycommons.org/pc2/home#graph)

The app will set 'kind = neighborhood' for single genes; otherwise 'kind=pathsbetween'. Format is 'txt'.

In this case, the above concerns are not likely to be a problem so will not reopen.

**Comment by IgorRodchenkov** [comment]
@jvwong @logmosier 
What if we'd always use `direction=bothstream` parameter to neighborhood graph queries (where the dafault is `direction=undirected`) as this gets less data (e.g., skips MolecularInteractions, i.e., there won't be any 'interacts-with' SIF edge types)?
