### ISSUE TITLE
Interactions: Empty result - at least one type should be enabled  

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#652]
Background: When seeded with a gene, the search page info box can launch the interactions view with data from a graph search.

An interesting case is [searching for the microRNA 'hsa-let-7a-1' (maps to the symbol MIRLET7A1 or ID 406881)](http://localhost:3000/search?gt=0&lt=250&q=hsa-let-7a-1&type=Pathway). With [kind = pathsbetween](http://www.pathwaycommons.org/pc2/graph?source=MIRLET7A1&kind=PATHSBETWEEN&format=txt) no result, but there is for [kind = neighbourhood](http://www.pathwaycommons.org/pc2/graph?source=MIRLET7A1&kind=NEIGHBORHOOD&format=txt). Consequently, the [corresponding interactions view](http://localhost:3000/interactions?id=406881&kind=NEIGHBORHOOD) is empty.

**Comment by jvwong** [comment]
my bad this works.

**Comment by jvwong** [comment]
Reopening because of the confusion caused by the sole filter for 'Expression' being disabled by default:

![image](https://user-images.githubusercontent.com/4706307/38568212-1e511f80-3cb6-11e8-855a-348201cb016a.png)

**Comment by jvwong** [comment]
Just logging this here but I notice the info box doesn't show up with `MIRLET7A1` although it appears that data does come back from the validator...

**Comment by logmosier** [comment]
If you are on the development branch the landing box won't work due to the removal of the get functions for geneValidator. I have already made a pull request (#650) with a fix .

**Comment by jvwong** [comment]
> If you are on the development branch the landing box won't work due to the removal of the get functions for geneValidator. I have already made a pull request (#650) with a fix.
FYI I was picking in those changes you that are in your pull request.

>Just realised that MIRLET7A1 won't show up regardless as currently I dont show the landing box if there are no other search results.
What do you mean by 'other'? Other than NCBI GENE?

**Comment by logmosier** [comment]
> What do you mean by 'other'? Other than NCBI GENE?

No as it is right now if no pathway search results are returned no landing box is displayed.

**Comment by jvwong** [comment]
I think that you could show the landing box either way. For the `MIRLET7A1` search, there are indeed no pathways but some interactions. Is there a reason not to?

**Comment by logmosier** [comment]
No, there is no reason not to. I think  I had set it that way originally as it seemed weird to give information on a gene with no search results but now that we have the interaction view it makes sense to show the box regardless.

**Comment by jvwong** [comment]
Well I have at least 1 example of a case where there are interactions and no pathways. So I would say make them independent.
