### ISSUE TITLE
Enrichment service returns response with all "custbg" inside "duplicate"? 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#665]
When I call the service with the parameter "custbg", it returns these genes in the "duplicate" field. Is this expected?

Case:

- endpoint:
  - http://localhost:3000/api/enrichment/
- parameters
  - genes
    - DOT1L AFF4 NAP1L3 BRPF1 TCF20 HLTF SIRT1 TDG SUV39H2 CBX7 DNMT1 DPY30 ING5 MLLT6 CHD1L USP27X BRPF3 ELP4 HCFC1 MARCH5 SCML2 PRDM10 SUPT16H TRIM24 GTF2H1 KDM3A PAF1 PCGF5 BAZ1B NCOA1 UBE2B SGF29 KDM5B MTA3 PCMT1 GTF3C4 MTA2 RBBP4 RNF20 SETD2 SSRP1 MBD1 POLR2B TP53BP1 UBR7 ARID4B ASH1L BRD4 HAT1 HDAC1 KAT2A MBD3 MSL3 RPA3 BAZ2A JMJD6 PHF7 SIN3B SP100 ZMYND11 
  - custbg
    - CHD1L HDAC3 TRIM24 PRDM6 ATR PBRM1 PHF3 ING4 DNMT1 NCOA1 TDG BRD4 BRPF1 AFF4 ATRX MTA1 ASH1L USP27X DOT1L ELP4 RING1 JMJD4 HDAC4 KAT6A NCOR1 PSIP1 RBBP5 ASXL3 MLLT6 PARP2 TRIM28 DOT1L INO80 TCF20 CBX7 POLR2B TDRD6 NCOR2 PRMT5 HDAC8 SMARCA2 CHD1 DMAP1 KDM5A HLTF MUM1 DPY30 HCFC1 KAT2A MTA3 NAP1L3 CHD5 AFF4 NAP1L3 RAI1 RNASE12 BRPF1 ELP3 CBX2 PRDM10 TCF20 CBX5 NSD1 PHF12 BAZ1B BRPF3 PCGF5 SUV39H2 PRDM1 HLTF SCML2 BOP1 TRIM33 ING5 PRDM16 EP300 PRMT1 SIRT1 SMARCD1 BAZ2B KDM3B SIRT1 TDG DOT1L EPC2 FBXO44 KDM5D KIAA2026 PCMT1 PRDM14 SUV39H2 GTF3C4 HSPBAP1 CBX7 DNMT1 L3MBTL2 PHC1 SETD2 SETDB1 SMNDC1 DNMT3B ZCWPW2 GTF2B DPY30 TDRD3 ING5 KDM4B MLLT6 PADI4 BRD2 EZH2 KDM4D LBR SFMBT1 SP140 SSRP1 ATM ING5 PRDM16 SIN3B SUPT16H TP53BP1 CHD1L CHD4 PRDM1 USP27X PHF7 PRMT8 RAG2 ARID4B ERCC5 KDM5B MBD1 MTF2 PRDM5 RPA3 ZMYND11 BRPF3 ELP4 FKBP1A MEN1 SIRT4 SIRT7 SMYD4 KAT2B KAT8 KDM2A KDM2B L3MBTL3 RNF20 SETD5 ASH2L HCFC1 SCML2 SCML2 SETDB2 USP17L5 GTF2F1 HR KDM3A PAF1 PRDM10 PRDM14 TDRD6 UBE2B CBX4 DPY30 GTF2H1 PRMT7 SUPT16H TRIM24 FBXL19 GTF2H1 HDAC1 KDM3A SETD6 SFMBT2 SMYD1 TDRD5 CDY2B CDY2A CHD3 ING3 JMJD6 MBTD1 NAP1L1 PADI1 SETD1A SIRT5 SMN1 SMN2 TAF1 USP22 BAZ1A KAT5 MBD3 MTA2 PADI1 PADI3 PAF1 PCGF5 PHF8 PRDM12 PRMT6 RAG2 RBBP4 RBBP7 SETMAR SP110 BAZ1B BPTF CDY1 CDY1B CHD5 HLTF MSL3 NCOA1 PHF6 PHIP PRMT8 TDRKH UBE2B UBR7 CDYL2 CLOCK GADD45B HAT1 KDM5B MTA3 PCMT1 PHF13 PRDM6 PRKAA2 UBE2B BAZ2A BRWD3 GTF3C4 L3MBTL4 MLLT10 MTA2 RBBP4 RNF20 RNF217 SETD2 SMYD5 SSRP1 MBD1 PAF1 PHF11 JADE3 POLR2B RAG2 RNF20 TP53BP1 UBR7 WDR82 ARID4B ASH1L BRD1 BRD4 GLYR1 HAT1 HDAC1 HDAC2 KANSL1 KAT2A KDM4E MBD3 MSL3 NCOA1 PAXIP1 RPA3 SP100 SP140L TDRD10 TRIM66 BAZ2A EED EZH1 HCFC1 JMJD6 MTA3 ORC1 PHC3 PHF7 PRDM16 PRDM9 SIN3B SIRT2 SP100 ZGPAT ZMYND11 CHD4 CREBBP DNMT3A EPC2 HDAC3 HELLS JMJD4 KAT7 KDM3A KIAA2026 L3MBTL2 NAP1L3 PHF13 RNF17 SP140L TAF1L TDRD6 ZMYND8 AIRE BRD2 CARM1 CARM1 EHMT2 EP400 GADD45B HDAC7 HELLS KAT6A KDM1A MBD2 MBD4 MBD4 NSD1 PHIP POLR2B PRKAA1 SHPRH SMARCC2 ASH2L ATRX BRD1 BRD2 BRD3 CDY1 CDY1B CDYL2 EP300 ING2 JMJD8 L3MBTL4 MLLT6 MPHOSPH8 ORC1 PHF21A PHF3 SATB1 SCMH1 TET1 UBE2E1 ASH1L BRD3 CHAF1A CHD3 CREBBP DPY30 FKBP2 H2AFZ HDAC11 ING5 KAT6B KAT8 KDM6A LBR MBD4 MTF2 NCOA3 PADI3 PADI6 PRDM15 PRMT1 PWWP2B SCML4 SIN3A SMARCA2 SMARCE1 TDG USP51 ASXL1 BRWD3 CHD7 CHD9 DNMT3L EED FBXW9 GADD45B INTS12 KAT8 KDM2A KIAA2026 L3MBTL1 MBD2 MBD5 MECP2 MTF2 NAP1L2 NCOR1 PADI6 PCMT1 PHF2 RNF17 SCML2 SMARCA4 SRCAP TCF20 TET1 TRIM33 ASXL2 CDY2B CDY2A CHAF1B CHD1 CHD9 CREBBP CSTL1 DMAP1 EHMT2 ELP3 ELP4 FBXL19 FKBP2 FKBP5 FMR1 FXR2 HDAC6 ING1 INO80 IWS1 JARID2 KDM4A MEN1 MLLT6 MPHOSPH8 MTA3 PCGF6 PHF20 PHF21B PRMT2 RBBP4 RING1 SETD7 SETDB2 SIRT1 SIRT4 SIRT5 SIRT6 SMYD3 TAF1 ASXL2 BOP1 BRD1 CHD5 DPF2 EPC2 EZH1 JARID2 KDM4B NCOA3 NCOR1 PADI6 PCGF2 PHC2 PHF8 PRDM9 PRDM9 PRMT3 PRMT3 PRMT5 PSIP1 RAI1 RNASE12 RPA3 SHPRH SIRT7 SMN1 SMN2 SMN1 SMN2 STK31 STK31 TAF1L TDRD12 TDRD5 TET2 TET3 TRIM24 TRIM33 UHRF1 WDR5 WDR82 ASXL3 BRD4 CBX5 CBX5 CDYL CECR2 CXXC1 DMAP1 DOT1L DPF2 EHMT1 EP300 FMR1 G2E3 GADD45B H2AFZ HDAC10 HDAC2 KAT6A KDM4C KDM4C KDM6B KDM8 MBD5 MUM1 NAP1L2 PARP1 PCGF1 PCGF2 PCGF5 PCGF6 PHF8 PRDM13 PRDM13 PRMT2 RAG2 SATB1 SETDB2 SIN3B SIRT2 SIRT3 SMARCA1 SMARCC1 SUPT16H TDRD12 TDRD7 TDRKH TRIM66 UBE2A UBE2B UHRF2 WDR5 AFF1 AKAP1 ARID4A ATAD2 BRD8 BRD8 BRPF3 CSTL1 ELP4 FBXO44 HDAC5 HDAC6 ING1 ING2 KAT6B MORF4L1 PARP2 PCGF5 PHF10 PHF3 PRMT2 PRMT7 PYGO2 SETD5 SETD6 SETDB2 SFMBT1 SFMBT2 SMYD2 SMYD5 SP140 SUV39H1 TCEA1 TCF19 TDRD1 TDRD9 TRIM28 ZMYND8 AFF4 AKAP1 AKAP1 ARID4A BAZ2A BAZ2B BRD9 CBX1 CBX5 CDYL2 CHAF1B CHAF1B DNMT1 DNMT3A DNMT3B EP300 EP400 ERCC5 HDAC5 HDGFL1 HIRA ING3 ING4 JMJD8 KAT5 KAT5 KDM2B KDM3A KDM4D KDM5C KDM5D MBD2 MECOM MORF4L1 PHC2 PHF1 JADE3 PHF21A PHF21B PHRF1 PRDM10 PRDM13 PRDM2 PRKCD RAI1 RNASE12 RNF17 RNF2 SETDB1 SFMBT2 SMARCA5 SMARCD1 SMYD2 SP100 SUZ12 TAF1L TRIM66 UHRF1 AFF1 ASH1L ASH2L ASXL1 BAZ1A BMI1 BRD2 BRD4 BRDT BRWD3 CECR2 CHAF1A CHD2 CHD2 CHD6 CREBBP EHMT1 EPC1 EPC2 GLYR1 HDAC5 HDAC7 HDAC8 HELLS HR HSPBAP1 INTS12 JARID2 JMJD1C JMJD1C JMJD8 JMJD8 KDM4A L3MBTL3 MEN1 MLLT10 MLLT10 MSH6 NAP1L1 NCOR2 ORC1 PCGF1 PCGF1 PCMT1 PHF12 PHF19 PHF2 PHF20L1 PHF23 PHF23 PHF6 PRDM12 PRDM4 PRDM4 PRKAA1 RING1 SCMH1 SETD1A SETD1B SETD2 SETD7 SETDB1 SIRT1 SIRT3 SIRT4 SMYD2 TAF1L TAF3 TDG TDRD6 TET1 TET3 TP53BP1 TRIM24 TRIM28 UBE2A UHRF2 USP17L5 USP17L5 USP51 UTY ZGPAT ZMYND8 AFF1 AFF1 AIRE ASXL2 ASXL2 ATAD2B ATAT1 AURKB AURKB BOP1 BRDT BRWD1 BRWD1 BRWD3 CBX4 CDYL CHD1L CHD8 CHD8 CLOCK CSTL1 DNMT1 DPF2 EZH1 GTF2F1 ING1 ING4 JARID2 JMJD1C JMJD7-PLA2G4B KDM1B KDM3B KDM5C KDM5D L3MBTL4 MECP2 MORF4L1 MPHOSPH8 MTA1 MTF2 PAXIP1 PCGF6 PHF1 PHF20 PHF20L1 PHF7 PRMT6 PRMT8 PRMT8 PSIP1 RAI1 RNASE12 RNF20 SCMH1 SETMAR SFMBT2 SIRT2 SIRT6 SMARCA1 SMARCA4 SMARCC2 SMARCD1 SMNDC1 SMYD4 SSRP1 TCEA1 TET1 UHRF2 WDR82 AKAP1 ARID4B ASXL3 ATAD2B ATM BRD1 BRD7 BRDT BRWD1 CBX1 CBX8 CDY2B CDY2A CECR2 CHD8 CHD9 CHD9 CLOCK DIDO1 DNMT3A DNMT3B DNMT3L ELP3 EPC1 EZH2 FBXL19 FBXO17 FBXW9 FBXW9 FKBP2 FKBP5 FMR1 GAPDH GTF2B GTF2F1 GTF2H1 H2AFZ HCFC1 HDAC1 HDAC1 HDAC10 HDAC10 HDAC4 HDAC4 HDAC5 HDAC7 HSPBAP1 INO80 JMJD6 JMJD7-PLA2G4B KAT2B KAT6B KAT8 KDM2A KDM4A KDM4C KDM8 KIAA2026 L3MBTL2 L3MBTL4 MBD5 MECP2 MSH6 MSL3 MTA2 MTA2 NAP1L1 NAP1L1 NAP1L2 NCOA3 NCOR2 NCOR2 NSD1 PADI3 PADI4 PAXIP1 PCGF1 PHC1 PHC3 PHF5A PHF7 PPARGC1A PPARGC1A PRDM11 PRDM15 PRDM2 PRDM5 PRDM7 PRKAA1 PRKAA1 PRKAA2 PRKCD PRKCD PRMT1 PRMT7 RBBP7 RBBP7 REN RNF2 RNF2 RPH3A SATB1 SETD1A SETD1B SETD3 SETDB1 SIN3A SIRT6 SMARCC1 SMN1 SMN2 SMYD2 SP110 SP110 SRCAP SRCAP SUV39H1 TAF1 TCEA1 TDRD3 TDRD5 TET3 TET3 TP53BP1 TRIM28 UBE2I UBE2I UBR7 UHRF1 USP51 UTY ZCWPW1 ZCWPW2 ZMYND11 AIRE ASH2L ATAD2 ATM BAZ2A BAZ2B BMI1 BRD8 BRD8 BRDT CBX4 CBX8 CDY1 CDY1B DNMT3L HDAC11 HDAC2 HDAC8 HIF1AN ING3 KAT2A KAT2B KAT6B KDM2A KDM2B KDM3B KDM5C MBD2 MBD5 MBTD1 PAF1 PHC1 PHC3 PHF10 JADE3 PHF20 PHF20L1 PRDM11 PRDM4 PRDM6 PRDM8 PRMT5 PRMT5 RBBP4 RING1 RNF17 SCML4 SETD1B SETD3 SETD4 SETD4 SETMAR SFMBT1 SMARCD3 SMYD1 SMYD3 STK31 SUV39H2 TAF1 TDRD3 TDRD9 TRIM33 ZCWPW1 ARID4B ATR ATRX BAZ1B BPTF BRD9 BRD9 CBX3 CBX6 CBX8 CHD6 DIDO1 EHMT1 EP400 EZH2 GADD45A GADD45A GLYR1 HDAC10 HDAC2 HDAC3 HDAC9 ING2 KANSL1 KDM4D KDM5C L3MBTL1 MBD4 NAP1L2 PADI2 PCGF2 PHF20L1 PHF21A PHF3 PHF6 PRDM12 PRDM7 PRDM9 SETD3 SIRT4 SIRT7 SMARCA1 SMARCA5 TRIM66 UBE2I UHRF1 USP22 ACTL6B ATR BPTF BRD7 CDY1 CDY1B CHD5 DPF3 FKBP1A GTF2B ING2 INO80 KANSL1 KDM1B KDM1B KDM3B MBD3 NSD1 PADI2 PHF19 PHF2 PHF20 PHF21A PHF21B PHRF1 PRDM7 PRDM8 PRMT6 PWWP2B RNF2 RPA3 SCML4 SMARCC2 SP100 SUV39H1 TCF20 TDRD5 ZMYND8 ASXL3 BRD3 BRD9 CECR2 CHD1 CHD7 CHD7 EP400 EPC1 FMR1 HAT1 HDAC9 HLTF INTS12 KAT6A KDM4B KDM5A KDM6A KDM6A MECOM MTA1 NCOA3 PADI4 PADI4 PBRM1 PBRM1 PHC2 PHF1 PHF14 JADE3 PHF19 PHF23 PHIP RBBP7 RNF40 SMARCC2 SUZ12 TDRD12 TDRKH TET2 UBE2A USP22 WDR82 ZCWPW2 BPTF BRD3 CDY2B CDY2A CHAF1A CHD3 CHD6 DIDO1 EPC1 ERCC5 G2E3 HIRA HIRA JMJD7-PLA2G4B KAT7 KDM1A KDM1A NCOA1 PADI2 PADI3 PARP1 PARP2 PHC2 PHF14 PHIP PRDM15 PRMT6 PYGO1 RBBP5 RSF1 SIRT3 SMARCA2 SND1 TET2 USP17L5 ATRX BMI1 CBX3 ELP3 GTF3C4 HDAC7 JMJD4 KDM5B KDM6A KDM6B L3MBTL3 MECOM PARP1 PHC1 PHF6 PRDM14 PRMT1 PYGO2 SETD3 SETMAR SIRT2 SIRT3 SMARCA5 SMARCE1 SMARCE1 SMNDC1 SMYD3 SUPT16H ACTL6B ACTL6B ACTL6B ARID4A ASXL1 ASXL1 ATAD2B ATR AURKB BOP1 BRPF3 BRWD1 CARM1 CBX2 CBX2 CBX4 CBX6 CBX6 CBX7 CBX7 CBX8 CHAF1A CHAF1B CHD1L CHD2 CHD3 CHD4 CHD4 CHD6 CXXC1 CXXC1 DIDO1 DMAP1 DNMT3L DPF3 DPF3 EED EED EHMT1 FBXL19 FBXO17 FBXO17 FKBP1A FKBP5 FKBP5 FXR2 G2E3 GADD45A GADD45A GLYR1 GTF2F1 H2AFZ HDAC11 HDAC4 HDAC6 HDAC6 HDAC8 HDAC9 HDGF HDGF HDGFL1 HIF1AN HIRA IWS1 JMJD4 JMJD6 JMJD7-PLA2G4B KAT5 KAT7 KDM1A KDM1B KDM2B KDM4A KDM4B KDM4C KDM4D KDM4E KDM5A KDM5A KDM6B KDM6B KDM8 KDM8 L3MBTL1 L3MBTL1 L3MBTL2 MBD1 MBD1 MECOM MEN1 RIOX2 MORF4L1 MPHOSPH8 MYC NAP1L3 NCOR1 ORC1 PARP1 PBRM1 PHF1 PHF10 PHF10 PHF12 PHF13 PHF13 PHF19 PHF2 PHF23 PHF5A PHRF1 PHRF1 PPARGC1A PRDM1 PRDM10 PRDM11 PRDM11 PRDM12 PRDM13 PRDM14 PRDM2 PRDM5 PRDM8 PRDM8 PRKAA2 PRMT2 PRMT7 PYGO1 PYGO2 RBBP5 RNF217 RNF40 SATB1 SCMH1 SETD1A SETD1B SETD4 SETD7 SHPRH SIN3A SIN3B SIRT5 SMARCA1 SMARCA4 SMARCA5 SMARCD3 SMARCD3 SMARCE1 SMYD1 SMYD1 SMYD3 SMYD4 SMYD5 SND1 SND1 SP110 SP140 SP140L SP140L SRCAP SSRP1 SUV39H1 TAF3 TAF3 TDRD1 TDRD10 TDRD10 TDRD10 TDRD7 TDRD7 TDRKH UBE2E1 UBE2E1 USP22 USP27X USP27X WDR5 WDR5 ZCWPW1 ZCWPW1 ATAD2 AURKB BAZ1A BMI1 DPF3 EHMT2 EZH1 FBXW9 FKBP1A FKBP2 KDM4E L3MBTL3 MBTD1 PADI2 POLR2B PRDM15 PRDM6 PRMT3 SMARCD3 SUV39H2 UBE2E1 ATM CBX1 CBX3 CBX6 DPF1 EZH2 HAT1 HDAC11 HDAC3 HIF1AN PADI1 PADI1 PAXIP1 PCGF2 PRDM1 RNF217 SHPRH SMNDC1 SMYD5 SUZ12 UBE2I USP51 CSTL1 DPF1 ERCC5 GTF2H1 MECP2 MSL3 PHF8 PRMT3 PYGO2 SFMBT1 SIRT6 SIRT7 TCEA1 BAZ1B BRPF1 CDYL DNMT3B FBXO44 HELLS HIF1AN HR IWS1 MLLT10 PCGF6 PHF12 PSIP1 RBBP5 RNF40 SCML4 SMARCA2 STK31 UTY ATAD2B ATAT1 CHD8 GTF3C4 ING3 ING4 KDM5B MSH6 PHC3 PRDM4 PYGO1 SMYD4 TDRD1 UBE2A BRD7 BRPF1 CARM1 CHD2 CXXC1 FXR2 JMJD1C PADI6 PRDM16 PRDM2 PRKAA2 SETD4 SMARCC1 SMARCC1 SMARCD1 UTY CBX2 KAT2B RNF217 SETD2 SMARCA4 TET2 ZCWPW2 BRD7 KAT2A PRDM5 CBX1 CLOCK TDRD3 ATAD2 CHD1 DNMT3A FBXO44 GTF2B HSPBAP1 INTS12 AFF4 KDM5D RNF40 SETD5 SIN3A SP140 TAF3 BAZ1A MTA1 PRKCD SETD5 SIRT5 SUZ12 CBX3 PPARGC1A KANSL1 RSF1 UHRF2 ATAT1 HDAC9 KAT7 KDM4E SETD7 EHMT2 MBTD1 PARP2 TDRD12 FBXO17 CDYL2 ZMYND11 BAZ2B MBD3 RSF1 IWS1 PRDM7 CHD7 

```json
{
	"duplicate": [
		"DOT1L",
		"AFF4",
		"NAP1L3",
		"BRPF1",
		"TCF20",
		"HLTF",
		"SIRT1",
		"TDG",
		"DOT1L",
		"SUV39H2",
		...
		"PRDM7",
		"CHD7"
	],
	"unrecognized": [],
	"pathwayInfo": {
		"GO:0006354": {
			"pValue": 0.0265,
			"t": 18,
			"q": 58,
			"qAndT": 10,
			"qAndTOverQ": 0.172,
			"qAndTOverT": 0.556,
			"tType": "BP",
			"tGroup": 1,
			"tName": "DNA-templated transcription, elongation",
			"tDepth": 1,
			"qAndTList": [
				"PAF1",
				"ZMYND11",
				"POLR2B",
				"AFF4",
				"SUPT16H",
				"ELP4",
				"GTF2H1",
				"BRD4",
				"SSRP1",
				"SETD2"
			]
		},
		"GO:0006368": {
			"pValue": 0.0265,
			"t": 18,
			"q": 58,
			"qAndT": 10,
			"qAndTOverQ": 0.172,
			"qAndTOverT": 0.556,
			"tType": "BP",
			"tGroup": 1,
			"tName": "transcription elongation from RNA polymerase II promoter",
			"tDepth": 1,
			"qAndTList": [
				"PAF1",
				"ZMYND11",
				"POLR2B",
				"AFF4",
				"SUPT16H",
				"ELP4",
				"GTF2H1",
				"BRD4",
				"SSRP1",
				"SETD2"
			]
		}
	}
}
```

**Comment by wxli0** [comment]
gProfiler recognizes duplicates in both query and custbg, should we recognize duplicates in custbg?

I noticed I forgot to check if the duplicate, unrecognized gene had always existed in the arrays. will make a pr.

**Comment by jvwong** [comment]
Maybe we should assume that the user has sent a valid set, i.e. used our first service. Then we can just remove the unrecognized and duplicate keys and make life simple. It seems that we are 'revalidating' which is what g:GOSt does, but we shouldn't.
