### ISSUE TITLE
Dependency conflict: Cytoscape.js and cytoscape-sbgn-stylesheet

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#669]
Running a fresh install of app-ui [development](https://github.com/PathwayCommons/app-ui/tree/f97b32566cd8d8feba1fd130c86c45da6bc1caae) resulted in the following error:

![screenshot at apr 12 23-07-46](https://user-images.githubusercontent.com/4706307/38715021-f44e04da-3ea6-11e8-8507-d73a6b41f280.png)

node v8.8.1.

I tracked this down to a [commit to cytoscape.js (unstable)](https://github.com/cytoscape/cytoscape.js/tree/3c4af2f8e7602b65dca503b24d3fc93efdde4add). Note that app-ui development branch references the cytoscape.js unstable only:

> package.json
```js
{
  "name": "app-ui",
 ...
  "dependencies": {
   ...
    "cytoscape": "git+https://github.com/cytoscape/cytoscape.js.git#unstable",
...
    "cytoscape-sbgn-stylesheet": "^3.0.0",
    ...
}

```  

I got it to work with [cytoscape.js commit 1e70ac4ee9c832d3de3db0a45948b4d1cd73e184](https://github.com/cytoscape/cytoscape.js/tree/1e70ac4ee9c832d3de3db0a45948b4d1cd73e184)

**Comment by maxkfranz** [comment]
That should resolve things such that future commits of `cytoscape#unstable` can be used.  We should probably have a ticket for updating to `cytoscape@3.3.0` when it's released.

I noticed that I get some warnings in the console, but they probably aren't related:

![screen shot 2018-04-18 at 1 02 40 pm](https://user-images.githubusercontent.com/989043/38947112-8659d884-4309-11e8-929a-63bc56bccb2e.png)
