### ISSUE TITLE
Distiller: Reconsider service names and paths to increase understandability    

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#671]
## Current status:
- enrichment-map
  - validator
  - enrichment
  - emap

## Idea 1: Validation; Nested enrichment-related tasks
- id-validator
- enrichment
  - analysis
  - network

## Idea 2: Nest all services named as actions as subpaths
- enrichment
  - validate
  - calculate
  - visualize

**Comment by wxli0** [comment]
will change to 
- enrichment
   - validation
   - analysis
   - visualization
