### ISSUE TITLE
Enrichment service to return subset of g:GOSt response, renamed

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#672]
(User feedback) Suggestion that `enrichment` service should return, for each pathway/id, only following key-values [current name] that are less g:Profiler-specific. 

TODO, please discuss with Ruth //

- description [tName]
- p-value [pValue]
- intersection [qAndTList]

**Comment by wxli0** [comment]
Should I create this drop down menus for some of the optional parameters? It'd be convenient to select from the drop-down menu but some error cases won't be detected (e.g. thresholdAlgo = "wwwww")
The alternative is to use a plain text input bar as "custbg".
![screen shot 2018-04-13 at 4 23 58 pm](https://user-images.githubusercontent.com/24982880/38756421-82938fea-3f37-11e8-9a05-25e2c44ca466.png)
