### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by logmosier** [PathwayCommons/app-ui#681]
General Feedback for the landing box/ interactions app:
Landing Box:
- clearer separation of the the landing box and search results
- The synonyms may not be recognized symbols, leads to confusion

Interactions:
- Layout:
  - Neighborhood: Better layout that does not produce the long vertical line of proteins
  - PathsBetween:Lay the two sides of the path on opposite ends of the screen and all the paths between them in the middle.
- Wait till all trimming is done before showing network 
- Show filter options even when no interactions of that type are present to let user know no interactions of that type are present
- Highlight the queried nodes in some way to make them stand out

**Comment by jvwong** [comment]
Split into individual issues.
