### ISSUE TITLE
Landing page info box: Make clear that 'Also known as' gene names are not standard  

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#689]
The info box lists the 'Also known as' gene names, whose origin is unclear and not guaranteed to be valid biological database symbols. The nature of this list should be made explicit and clear.

![image](https://user-images.githubusercontent.com/4706307/39016000-f54013c4-43ec-11e8-88d0-9d573e5206e2.png)

**Comment by logmosier** [comment]
Would it be better to maybe just replace them with some valid biological database ids? I already have them for the links.

**Comment by jvwong** [comment]
I talked briefly with @risserlin about the use case for non-standard synonyms - she suggests removing them. I'm still on the fence.

The case to remove: Right now, you can only get the infobox when you type a standard name. I can't get anywhere with 'p53'. So in that case, I already know the gene I am entering. For linkouts (e.g. UniProt) the user already knows the gene.

The case to keep: Someone could put in a non-human-readable identifier and get back 'more information. For instance, I know the ENSG ID or UniProt accession from some experimental output (RNA Sequencing experiment) but I don't know a lot about the genes, and I may only recognize some of the synonyms.        

What about this (using names of NCBI Gene fields):

### Official full name
#### Official Symbol 
#### Other names
and make people click to see any of those 'other names'?
...

**Comment by logmosier** [comment]
Ya that could work.

**Comment by jvwong** [comment]
Oi - I hate to nit pick but...
![image](https://user-images.githubusercontent.com/4706307/39068818-9bf419fe-44ab-11e8-90fa-7d825c8d51ba.png)

1. 'Official Ids'
There's no databases associated with your IDs or symbols - what is 472? These ID/symbols are unique to a particular database, not universally. You do provide the links below (UniProt, NCBI Gene, and HGNC at least). In my above comment, I was thinking just put the HGNC approved symbol.

2. 'Unofficial Ids'
How about 'Other names'

**Comment by logmosier** [comment]
Is this more like what you had in mind?
![screen shot 2018-04-20 at 3 59 30 pm](https://user-images.githubusercontent.com/10948303/39071113-d79d90d6-44b3-11e8-9604-c3947042a8ca.png)

**Comment by jvwong** [comment]
I'm fine with this.
