### ISSUE TITLE
fix cy hover style selectors 

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#69]
The way that the hover events are currently set up prevent users from clicking child nodes in expanded complex nodes

https://github.com/PathwayCommons/app-ui/blob/master/src/client/features/view/cy/events/hover.js

**Comment by d2fong** [comment]
Might need to change the selector from 
```js
node[class!="compartment"], $node >node
```

http://js.cytoscape.org/#selectors/compound-nodes

Take a look at subject selector.  Maybe that is what we need.

**Comment by maxkfranz** [comment]
Check whether the node is the event target.  If not, it's just from bubbling (i.e. parent).

**Comment by hmtinc** [comment]
Should the hover style be disabled when the node is expanded?
