### ISSUE TITLE
Output and return Reactome stable identifier rather than g:Profiler-specific IDs

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#696]
Background: The enrichment and emap services output and accept as input Reactome pathway identifiers.

Issue: The format output from enrichment service (i.e g:Profiler) is ostensibly related to, but different from Reactome's 'Stable Identifier'. Consider:
1. Mapping enrichment output to 'Stable Identifier' format. I can only guess that  g:Profiler gives the integer part of 'R-HSA-XXXXXX'. Can anyone confirm/deny this guess? 
2. Accept Reactome Stable Identifier in emap. 

This will further decouple the services, make them less g:Profiler-specific and relate more directly  to Reactome data itself. 

Example: Consider enrichment output with the following entry with pathway "REAC:674695":
```js
{
	"pathwayInfo": {
         ...
		"REAC:674695": {
			"p-value": 0.0000223,
			"description": "RNA Polymerase II Pre-transcription Events",
			"intersection": [
				"PAF1",
				"POLR2B",
				"AFF4",
				"SUPT16H",
				"GTF2H1",
				"SSRP1"
			]
		},
         ...
}
``` 

The corresponding [Stable Identifier in Reactome is R-HSA-674695:](https://reactome.org/content/detail/R-HSA-674695)
![image](https://user-images.githubusercontent.com/4706307/39069765-d67abc38-44ae-11e8-8f9c-aca8c9bac25f.png)

**Comment by wxli0** [comment]
> Mapping enrichment output to 'Stable Identifier' format. I can only guess that g:Profiler gives the integer part of 'R-HSA-XXXXXX'. Can anyone confirm/deny this guess?

Do you want to get this merged to dev before any confirmation/denial?

**Comment by jvwong** [comment]
THis is only a guess on my part. Maybe ask them directly?

**Comment by urdvr** [comment]
Hello, 
I'm writing on behalf of g:Profiler team.

> I can only guess that g:Profiler gives the integer part of 'R-HSA-XXXXXX'. Can anyone confirm/deny this guess?

I can confirm this, but the format will change to the more correct stable identifier format when we do the next data update. Right now we return the ID "REAC:XXXXXX", starting from the next version we will return "REAC:R-HSA-XXXXXX"

This update should happen within the next couple of weeks.

**Comment by jvwong** [comment]
Great. Thanks for the info. In that case, let's keep our solution as is and keep an eye on g:Profiler updates.
