### ISSUE TITLE
Always show the landing box with "Interactions" button

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/app-ui#702]
As you might know, we're in process of submitting Pathway Commons links to UniProt (linkout).
We want them use our search app URL template:  `http://apps.pathwaycommons.org/search?q=%u` that will be soon pointing to the new landing page with the gene info box (see appsbeta/pathwaycommons.org). 

The problem is that there are cases when we have some data for a UniProt ID, but it does not match any pathways (and this is normal); so, the result is empty:

http://appsbeta.pathwaycommons.org/search?q=A0A075B6K4&type=Pathway
(though there are matching BioPAX entities: http://www.pathwaycommons.org/pc2/search?q=xrefid:A0A075B6K4)

Also, `&type=Pathway` parameter seems to matter not at all (which is in fact great for the linkout).

I suggest we always show the landing box with "Interactions" button, regardless any pathways found or not. UniProt team, as a rule, do not want to link to search pages or no-data pages...

@logmosier @d2fong @jvwong @gbader

**Comment by IgorRodchenkov** [comment]
Refs #695

**Comment by jvwong** [comment]
@logmosier correct me if I am wrong, but isn't this the intended behaviour of the current (development branch) info box? 

By the way, the above example breaks the search in the latest dev #703.

**Comment by logmosier** [comment]
This is not the intended behavior but the reason the box is not showing up is because A0A075B6K4 does not have a NCBI id not that there are no search results. The landing box with display if there are no search results .
![screen shot 2018-04-23 at 2 21 11 pm](https://user-images.githubusercontent.com/10948303/39145499-df63afe4-4701-11e8-9584-f1de8d473a1e.png)
To fix this I could add a fall back so that if there is no NCBI id we fetch the data from Uniport but there would still be cases where Uniprot ids would not get caught as it looks like g:profiler does not recognize them:
![screen shot 2018-04-23 at 2 25 13 pm](https://user-images.githubusercontent.com/10948303/39145602-45033162-4702-11e8-8b00-138b1a8b8d36.png)
![screen shot 2018-04-23 at 2 25 27 pm](https://user-images.githubusercontent.com/10948303/39145603-45149614-4702-11e8-90b1-3b7d7e21a833.png)

**Comment by jvwong** [comment]
Proposing this fall-back strategy for query parameter that is a single token:

1. Try app-ui validator service for NCBI Gene or UniProt
2. Try PC webservice search/traverse

![smart search 1](https://user-images.githubusercontent.com/4706307/39203484-eb7e81b6-47c2-11e8-8639-237363bf1332.png)

**Comment by IgorRodchenkov** [comment]
Interesting. I have one concern/doubt (perhaps somewhat off-topic) and a
suggestion.

Concern: let's make sure we keep it simple and nothing "too smart" stays
between user query strings and PC search web service (full-text search); so
we don't fool ourselves and loose search power trying to improve it... I
believe this has not yet become problem.

Suggestion (idea): what if we simply make the app (apps/search) understand
special single ID queries like 'q=uniprot:P12345' or 'hgnc:NOG'?
This could much simplify all the troubles and help integrate PC links into
UniProt, NCBI, GeneCards.

IR.

**Comment by jvwong** [comment]
Re: Suggestions. That would make life easy.

Re: Concern. As far as I understand, we only use the id-mapping for the purposes of setting the lucene prefix (i.e. xrefid). It was my suggestion to always use the original user's input for the query to PC for pathways. The interactions is another story - @logmosier ?

**Comment by logmosier** [comment]
Re: Concern. That is correct the id for the search is only used for the purpose of  the lucene prefix (i.e. xrefid) for the search. For the interactions currently the id used for fetching the information for the landing box is used though that is mainly to make it easier to get information for the additional information panel the interaction viewer itself can use any id that would return a result from PC graph.

**Comment by jvwong** [comment]
Let's think about these for now:

1. NCBI Gene
2. UniProt
3. HGNC

As far as I know, HGNC and NCBI Gene are generally well coordinated.

**Comment by logmosier** [comment]
Ya it seems that the overlap between HGNC and NCBI Gene is pretty large.

**Comment by IgorRodchenkov** [comment]
Just to clarify what we mean by those (from xrefs, search, MIRIAM, etc.
point of view)  -

'NCBI Gene' - also known as GeneID, EntrezGene - is to refer to numerical
IDs
(KEGG uses the same numbers but calls this collection  "KEGG GENE" and uses
like hsa:7529; un UniProt/SwissProt data file, there are DR lines like

*DR    GeneID; 7529; -.DR    KEGG; hsa:7529; -.*
)

'UniProt' - UniProt Accession Numbers, e.g., 'P31946' (probably, without
the isoform suffix; and definitely not '1433B_HUMAN' type of id, which is
unstable and not-recommended uniprot identifier).

HGNC - what we mean here is actually 'HGNC Symbol' (we do not need to
support HGNC:1234 IDs) - e.g. 'TP53', 'BMP2' - we want to link GeneCards to
PC using gene symbols.

IR.

**Comment by logmosier** [comment]
The actual search would also need to be modified to handle these links as right now if you go to http://appsbeta.pathwaycommons.org/search?gt=0&lt=250&q=hgnc:ATM&type=Pathway instead of http://appsbeta.pathwaycommons.org/search?gt=0&lt=250&q=ATM&type=Pathway you dont get any search results.

**Comment by IgorRodchenkov** [comment]
No; we will remove the prefix before sending query to PC2 search service

**Comment by IgorRodchenkov** [comment]
I mean, we just want to allow q=hgnc%3AATM (‘:’ in url parameters must be encoded) for the apps urls like appsbeta.pathwaycommons.org/search?q=hgnc%3A... (to keep our apps’ logic simple) but PC web service won’t “understand” such prefixed query strings (unless the prefix is a lucene index field name, e.g., xrefid:).

Alternatively, we could have a separate apps endpoint for one-id search, such as /search/uniprot/P12345 or even like ...org/uniprot/P12345

**Comment by logmosier** [comment]
Ya, sorry I meant the code for the search on the site not the search that PC2 does.

**Comment by jvwong** [comment]
Logic within pull request #729 

![landing_ logic 2](https://user-images.githubusercontent.com/4706307/39434817-adf3183a-4c67-11e8-8093-b9df29d39474.png)

**Comment by IgorRodchenkov** [comment]
There are some more issues related to this info box, links. I will create a new issue.

**Comment by jvwong** [comment]
OK yeah this one was getting way tooo long...
