### ISSUE TITLE
Search with UniProt ID hangs app.

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#703]
## Environment info

- Browser version (client) : Firefox 59.0.2; Chrome 65.0.3325.181
- Node.js version (server) : 8.9.3

## Current (buggy) behaviour

The app hangs when a particular UniProt ID is entered.

## Desired behaviour

Show interactions info box and pathway search hits.

## Minimum steps to reproduce

Type 'A0A075B6K4' and search. 

Firefox 59.0.2 
![image](https://user-images.githubusercontent.com/4706307/39141304-730f6182-46f5-11e8-9c81-7cd2860805e2.png)
![image](https://user-images.githubusercontent.com/4706307/39141359-98c78ef4-46f5-11e8-88c6-5991c0aa5bc2.png)

Chrome 65.0.3325.181
![image](https://user-images.githubusercontent.com/4706307/39141322-7b5ee704-46f5-11e8-85f8-5c3ad1f50c86.png)

**Comment by IgorRodchenkov** [comment]
It does not hang for me right now here in the lab (neither apps nor appsbeta; but I remember seeing similar troubled behaviour before... when I was connecting from outside our lab).
