### ISSUE TITLE
Update to Docker-related files and documentation

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#719]
Updates to the Docker and Docker Compose files.

`/Dockerfile`
- Bump up to Node.js v9
- Add unprivileged user `appuser`

`/docker-compose.yml`
- uses `development` image tag
- expose app on port `9090` 
- set environment variables, in particular, rethinkdb [config `host`](https://github.com/PathwayCommons/app-ui/blob/51383112ef5964ee236fc52218a20f98648b8c92/src/server/database/config.js#L6)
- expose rethinkdb UI on port `8020` 

`/docker-compose.production.yml`
- uses `latest` image tag
- use a host rethinkdb instance via `host.docker.internal`

`README.md`
- Added section on Docker Compose usage

**Comment by maxkfranz** [comment]
@jvwong We shouldn't be using node@9.  Odd major versions are generally unstable.  It's better to stick to even-numbered LTS releases, like 6 or 8.

**Comment by jvwong** [comment]
@maxkfranz yeah @d2fong mentioned this and we dropped it to v8 in #720
