### ISSUE TITLE
Hide old tooltips when a new tooltip is created 

### ISSUE THREAD

**Issue by hmtinc** [PathwayCommons/app-ui#73]
Tooltips don't go way when a new node is selected, which causes crowding on the screen and smaller mobile devices.

**Comment by maxkfranz** [comment]
There should be a tippy option for this (multiple / single?)

**Comment by hmtinc** [comment]
Tippy's multiple option only works if you use the click trigger to show and hide tooltips. The option has no effect if you programmatically show the tooltip

**Comment by hmtinc** [comment]
Implemented a fix in #106 which keeps track of the visible status in the tooltip class
