### ISSUE TITLE
Making service options more generic (Reducing g:profiler-specific options)

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#731]
Related to #730 and #732

To the extent that it is reasonable, we aim to provide services that are independent of the implementation. Making them generic will lessen the impact of changing dependencies (i.e. g:Profiler) for clients.

@risserlin

1. Validation
  - 'genes'
  - 'organism'
  - 'target'

2. Analysis
  - 'genes'
  - 'backgroundGenes'
  - 'minSetSize'
  - 'maxSetSize'
  - 'significantOnly'

3. Visualization
  - 'pathways'
  - 'cutoff'
  - 'jaccardOverlapWeight'

**Comment by CaitlinOCallaghan** [comment]
Without the models section 

![image](https://user-images.githubusercontent.com/38890251/40255749-46535d72-5ab6-11e8-9ce5-1ae88c4f0323.png)

**Comment by CaitlinOCallaghan** [comment]
I just want to verify that these are the proper changes for the parameters:

1. Validation
'target'  -> 'targetDb'

2. Analysis 
remove 'userThr'
remove 'thresholdAlgo'
Are 'backgroundGenes' and 'datasources' new parameters?
What should we do with 'custbg'?

3. Visualization
'pathwayInfoList' -> 'pathways'
'cutoff' -> 'similarityCutoff'
'JCWeight' -> 'jaccardOverlapWeight'
remove 'OCWeight'

**Comment by jvwong** [comment]
> Analysis
> remove 'userThr'
> remove 'thresholdAlgo'
> Are 'backgroundGenes' and 'datasources' new parameters?

'datasources' is a new parameter. Will require updates - let's drop this parameter for now.  

> What should we do with 'custbg'?

custbg --> backgroundGenes


> Visualization
> 'pathwayInfoList' -> 'pathways'
> 'cutoff' -> 'similarityCutoff'
> 'JCWeight' -> 'jaccardOverlapWeight'
> remove 'OCWeight'

JCWeight, OCWeight --> jaccardOverlapWeight

**Comment by jvwong** [comment]
No, that `target` is a [cytoscape.js](http://js.cytoscape.org/#notation/elements-json) data key: The node where an edge terminates.

**Comment by jvwong** [comment]
- /analysis
  - remove 'orderedQuery' and default 'false'
