### ISSUE TITLE
add  ISSUE_TEMPLATE to master

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#751]
1. create a branch off of master 
2. add the file https://github.com/PathwayCommons/app-ui/blob/development/ISSUE_TEMPLATE.md
3.  submit a pull request to master

**Comment by d2fong** [comment]
@q4wen I am assigning this to you.

**Comment by q4wen** [comment]
Should I just add this file under root directory of the project under app-ui/ ?

**Comment by maxkfranz** [comment]
Yes, you're basically just copying it from dev to master.  The file should go in the root dir of the project.
