### ISSUE TITLE
Infox box: Link for HGNC should reference "Approved Symbol"

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#756]
## Description of new feature

Background: The search info box for a gene displays links to various biological databases, including [HGNC](https://www.genenames.org/). Currently the text and URI reference the 'HGNC ID' (format `HGNC:XXXXX`).

![image](https://user-images.githubusercontent.com/4706307/40012736-988eb310-5779-11e8-89df-9ef7eec5dd01.png)

Issue: The goal is to update the link text and URI for HGNC to reference the HGNC approved symbol. 

1. Text: "HGNC Symbol"
2. URI format: `http://identifiers.org/hgnc.symbol/<HGNC approved symbol>`

## Motivation for new feature

This is in line with the format of biological identifiers kept in Pathway Commons.
@IgorRodchenkov

**Comment by q4wen** [comment]
Is the symbol in text the same as <HGNC approved symbol>?

**Comment by jvwong** [comment]
My bad, the text for the link should not change - it should be "HGNC".
