### ISSUE TITLE
Require access to Pathway Commons URI via environment variable.

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#764]
## Description of new feature

The URI for Pathway Commons should be declared and accessed in one place, through an environment variable. 

## Motivation for new feature

This will enable the app to fetch from any valid host/domain and ease maintenance.

**Comment by IgorRodchenkov** [comment]
@jvwong @d2fong @maxkfranz @MichaelWrana 

There are many places (a dozen or so) in the apps code where either `www.pathwaycommons.org` or `pathwaycommons.org` or `www.pathwaycommons.org/pc2/` is hardcoded as string.
However, there are several different PC servers, such as production PC9  (www.pathwaycommons.org/pc2/), beta (beta.pathwaycommons.org/pc2/), experimental  (textmining.pathwaycommons.org/pc2/), etc.

Therefore, tt least the PC web **service** base URL should be configurable via an enviroment variable, e.g., PC_URL - just like PORT and NODE_ENV (and also - described in the README). 

Probably, Pathway Commons project home page URL http://www.pathwaycommons.org, which is probably used in links to logo or html pages, does not need to be configurable (can be simply a global constant defined just once; note that simply adding '/pc2/' to the PC home URL, although works right now, won't necessarily resolve to the PC web service endpoint URL in the future), unlike the PC service endpoint URL. 

(I just wanted to try the latest search/view app connect to the beta PC10 web services, and could not do without refactoring/patching apps-ui code...)

**Comment by d2fong** [comment]
https://github.com/PathwayCommons/pathway-commons-client/pull/8

**Comment by IgorRodchenkov** [comment]
Done.
