### ISSUE TITLE
Landing box pcQuery uses incorrect parameter name

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#768]
## Environment info

- Browser version (client) : n/a
- Node.js version (server) : 8

## Current (buggy) code

The `pcFallback` function in [/src/client/features/search/landing-box.js](https://github.com/PathwayCommons/app-ui/blob/development/src/client/features/search/landing-box.js#L34) calls PC to search for a matching 'entityReference' but sets an unrecognized parameter key name `entry`

```js
...
const pcFallback = (unrecognized,genes) => {
  ...
     return ServerAPI.pcQuery('search', {q:entry,entry:'entityreference'}).then((search)=>{
  ...
};
...
``` 

## Desired code

This parameter name should be [`type`](http://www.pathwaycommons.org/pc2/#search).

```js
...
const pcFallback = (unrecognized,genes) => {
  ...
     return ServerAPI.pcQuery('search', {q:entry,type:'entityreference'}).then((search)=>{
  ...
};
...
```

**Comment by IgorRodchenkov** [comment]
Good catch (I sweat when saw it, because the search would return tons of irrelevant hits :)))
