### ISSUE TITLE
Improved mobile support

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/app-ui#773]
## Description of new feature

Since this project is structured similarly to Factoid, it would be straightforward to apply similar changes to this project: https://github.com/PathwayCommons/factoid/issues/273

## Motivation for new feature

There are several minor issues with the UI on touch devices.  I was able to resolve most of the same sort of problems in the Factoid ticket.  Once I reviewed the changes a bit more and merged them into Factoid, we should apply the same sort of changes here.

**Comment by maxkfranz** [comment]
@d2fong This relates to the mobile discussion we had the other day.

**Comment by maxkfranz** [comment]
See https://github.com/PathwayCommons/factoid/pull/286

Many of the commits in the PR could apply to app-ui

**Comment by d2fong** [comment]
Ok I'll take a stab at porting these changes over
