### ISSUE TITLE
Pathway viewer loading icon persists when network empty  

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#779]
## Environment info

- Browser version (client) : Version 66.0.3359.181 (64-bit); Firefox 60.0.1 (64-bit)
- Node.js version (server) : n/a

## Current (buggy) behaviour

When I launch a (pathway) view of an interaction, the loading icon persists. However, It disappears when I resize the browser. 

## Desired behaviour

The loading icon should disappear on load of (possibly empty) network.

## Minimum steps to reproduce

1. Search [`GDF15 and TP53`](http://appsbeta.pathwaycommons.org/search?gt=0&lt=250&q=GDF15%20TP53&type=Pathway)
2. In the [interactions view](http://appsbeta.pathwaycommons.org/interactions?source=7157&source=9518), find the edge connecting GDF15 and TP53
![image](https://user-images.githubusercontent.com/4706307/40499072-d3497cce-5f4e-11e8-9f6d-279beff3bc4f.png)

3.  Launch a pathway view of any [interaction](http://appsbeta.pathwaycommons.org/view?removeInfoMenu=true&title=GDF15%20in%20complex%20with%20TP53&uri=http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FComplex_4839c52f0b319f9132e85d41891024c4) 

![image](https://user-images.githubusercontent.com/4706307/40499038-bb2c9590-5f4e-11e8-8f86-75dbae1ca09d.png)

**Comment by MichaelWrana** [comment]
As of right now, I can't figure out how to get rid of the loading icon, but perhaps this is a reasonable alternative:


The following message will display if the node and edgelist for a network is empty:
![img](https://user-images.githubusercontent.com/25777239/40731871-084727ae-6400-11e8-8b0f-53c955047457.png)
