### ISSUE TITLE
development branch: view is broken

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/app-ui#781]
I noticed that pathway views do not load properly with the app-ui from the development branch (this issue was there before my changes and merging pull requests over the last several days).

There are many messages like (in Chrome Developer Tools, console):
```
Edge `Protein_411e06de14a5a9dc62cff6662264d2ca--to--reactome_R-HSA-202626_LEFT_TO_RIGHT-input` has invalid endpoints and so it is impossible to draw.  Adjust your edge style (e.g. control points) accordingly or use an alternative edge type.  This is expected behaviour when the source node and the target node overlap.
```

Compare e.g. this:
`http://apps.pathwaycommons.org/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-201451`

and (if you run rethinkdb and app-ui localli) - 
`http://localhost:3000/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-201451`

**Comment by jvwong** [comment]
Maybe related to #771?

**Comment by IgorRodchenkov** [comment]
Ah, yes (sorry, could not find existing ticket). Let's address #771 and close this one.
