### ISSUE TITLE
Datasource filter: Setting value attribute for <select> 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#784]
## Environment info

- Browser version (client) : Chrome Version 66.0.3359.181 (Official Build) (64-bit)
- Node.js version (server) :n/a

## Current (buggy) behaviour

Browser complains: `Warning: The `value` prop supplied to <select> must be a scalar value if `multiple` is false.

Check the render method of `Search`.` 

![image](https://user-images.githubusercontent.com/4706307/40581187-fdd7f2c2-611f-11e8-9679-f615f6909d76.png)

## Desired behaviour

Seems to arise from value set on `<select>` in [datasource filter](https://github.com/PathwayCommons/app-ui/blob/development/src/client/features/search/index.js#L159-L167).

```js
    const searchResultFilter = h('div.search-filters', [
      h('select.search-datasource-filter', {
        value: state.query.datasource,
        onChange: e => this.setAndSubmitSearchQuery({ datasource: e.target.value })
      }, [
        h('option', { value: [] }, 'Any datasource')].concat(
          _.sortBy(state.dataSources, 'name').map(ds => h('option', { value: [ds.id] }, ds.name))
          )),
    ]);

```

Aside: Should value on `options` be array?

**Comment by CaitlinOCallaghan** [comment]
I was able to remove the error.

I do believe that the options value as an array is necessary. Without the array, you can select a specific data source and get proper results, but if you try to go from that select data source back to 'any datasource' the code breaks and '0 results' is returned.

**Comment by CaitlinOCallaghan** [comment]
Issue has been merged so we can now close it

**Comment by IgorRodchenkov** [comment]
Can I now select several data sources, e.g., reactome and panther (PC web service accepts an array or values for the datasource parameter in /search, /traverse, /graph queries)?

**Comment by jvwong** [comment]
Hold on. Something is still causing the error...

**Comment by jvwong** [comment]
That [latest merge](https://github.com/PathwayCommons/app-ui/pull/795) rids the warning but now removes the dropdown:
![image](https://user-images.githubusercontent.com/4706307/40753815-fdd93674-6443-11e8-9705-dcd5580c4703.png)

**Comment by CaitlinOCallaghan** [comment]
I see what you mean and will look into it further. What's odd is that when I pulled up local host just now, (without changing any code) a new error has arisen. However, earlier on both my and Rex's machines there was no error. Did you get this one too?  

"warning.js:33 Warning: The `value` prop supplied to <select> must be an array if `multiple` is true. Check the render method of `Search`."

![image](https://user-images.githubusercontent.com/38890251/40760023-c93be3ac-6462-11e8-8842-3075e3545feb.png)

**Comment by CaitlinOCallaghan** [comment]
![image](https://user-images.githubusercontent.com/38890251/40760133-54c34b0e-6463-11e8-80fc-340b4d446144.png)

**Comment by jvwong** [comment]
I only get the above error when I click the filter itself.

**Comment by maxkfranz** [comment]
I don't think using `multiple: true` makes sense here.  We're only selecting one value, rather than shift-selecting multiple values, right?
