### ISSUE TITLE
Use human readable label in text input box for database referrers (prefixed) 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#785]
## Description of new feature

The search displays a landing box for a query of the form `q=<db:id>`, which we interpret as a referral from a recognized biological database. This `<db:id>` term is used to populate the search input, but it won't mean much to the user. 

Example, arrival from NCBI Gene for 7157:
![image](https://user-images.githubusercontent.com/4706307/40622540-26476534-6270-11e8-94df-c3a0383caefb.png)

In this case, replace `<db:id>` input text with a human-readable equivalent (HGNC?). 

## Motivation for new feature

Make the landing page more user-friendly.

**Comment by IgorRodchenkov** [comment]
If it doesn't have an HGNC symbol (and this is not due to a bug, like in http://appsbeta.pathwaycommons.org/search?q=A0A075B6K4&type=Pathway - no HGNC link for some reason, and no interactions can be found... I am reporting this in a separate ticket)
then let's show db:id.

**Comment by jvwong** [comment]
> @jvwong did you mean - in the above example - to use "TP53" insteaad (sic) of "ncbi:7157" but only in the input box?

Yes.  

>Just want to confirm, does every referenced gene/protein (query of the form q=<db:id>) has a HGNC symbol? I am concerned that the input box will display random thing if it does not have a HGNC symbol.

Like @IgorRodchenkov said, you can always fallback to <db:id>. As I [recall](https://github.com/PathwayCommons/app-ui/issues/702#issuecomment-383689892), we can map UniProt Accession A0A075B6K4 to HGNC ("IGLV3-10") but NOT to NCBI. Not sure why the HGNC link disappears (new issue?)... 

> http://appsbeta.pathwaycommons.org/api/validation/
```js
{
	"genes": [
		"A0A075B6K4"
	],
	"target": "hgncsymbol",
	"organism": "hsapiens"
}
```

out
 ```js
{
	"unrecognized": [],
	"duplicate": {},
	"geneInfo": [
		{
			"initialAlias": "A0A075B6K4",
			"convertedAlias": "IGLV3-10"
		}
	]
}
```

**Comment by IgorRodchenkov** [comment]
@jvwong , yes - see new issue(s) #786

**Comment by jvwong** [comment]
Closing.

Reason
  - Difficult to tell whether search was performed via referral vs typing in search box
  - Risks rare case of frustrating users who wish to type in prefix:id
  - User area presented with info box that clearly describes the context
