### ISSUE TITLE
Landing, gene info box: no HGNC link, no interactions in some cases, broken links

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/app-ui#786]
Check e.g., http://appsbeta.pathwaycommons.org/search?q=A0A075B6K4&type=Pathway; there are several issues:

1. Despite it says "Official Symbol: IGLV3-10", there is no HGNC link;
2. Clicking 'View INteractions' results in "no interactions" despite there are a couple (transcription) in PC: http://www.pathwaycommons.org/pc2/search?q=xrefid:IGLV3-10
3. "Gene Cards" links to http://identifiers.org/genecards/IGLV3undefined10 (should be /IGLV3-10)
4. I think, all the external links should open a new browser tab/window instead of reloading current one.

Other things (I should probably create separate tickets for the following):
 - can we hide internal parameters from the apps query url in the address box? I.e., it should not probably show gt=0&lt=250&type=Pathway all the time; might I am wrong;
- try to submit &type=foobar ... - the app should probably return an error page like  "unsupported parameter value" or fall bacl to the default (type=Pathway);
- did you know that datasources filter can be also used with PC /graph and /traverse queries; i.e., applies to the interactions sea4rch as well? If we want to use that feature, I will have to revert one of my recent changes - to show all the data sources rather than pathway-data ones in that drop-down list...

@jvwong @q4wen

**Comment by q4wen** [comment]
There is probelm when the gene/protein is not in NCBI. (The current implementation is check NCBI first. If the gene cannot be found in NCBI, the system will go to Uniprot where the function has bug and needs to be fixed).  

>3. "Gene Cards" links to http://identifiers.org/genecards/IGLV3undefined10 (should be /IGLV3-10)

"undefined" is caused by the "-" in the original ID. Current validator only accepts numbers and letters. However, http://identifiers.org/genecards/IGLV3-10 still goes to error page.

**Comment by IgorRodchenkov** [comment]
But IGLV3-10 id a valid HGNC Symbol, and there should be identifiers.org/hgnc.symbol/IGLV3-10 link (and something else or none for GeneCards)

IR

**Comment by IgorRodchenkov** [comment]
Indeed, empty TXT result, alright then. 
That's because, even though the graph query finds a biopax sub-network, the result of the following conversion to SIF/TXT format is nothing, because some of the interaction participants  (Rna) there have no HGNC symbols...

**Comment by jvwong** [comment]
The HGNC link should be doable:

![image](https://user-images.githubusercontent.com/4706307/40805287-c5edd244-64eb-11e8-96d4-b2410152ad33.png)

**Comment by jvwong** [comment]
> 3. "Gene Cards" links to http://identifiers.org/genecards/IGLV3undefined10 (should be /IGLV3-10)

This arises from some seemingly [unnecessary `replace` in landing-box.js](https://github.com/PathwayCommons/app-ui/blob/8dc1890f0c89ac2bf1c7972c4f9e866127956513/src/client/features/search/landing-box.js#L46):
> /src/client/features/search/landing-box.js
```js
const idToLinkConverter = (ids)  =>{
...
      [database.database]: database.url+database.search+ids[database.database].replace(/[^a-zA-Z0-9:]/g)
  }))
  );
...
};

```

Suggest to remove `.replace(...)`.

**Comment by q4wen** [comment]
What is the difference(relation) between HGNC and HGNC symbol?

> Despite it says "Official Symbol: IGLV3-10", there is no HGNC link;

The reason why HGNC Symbol is missing is that Uniprot does not return an HGNC symbol but an HGNC id. In #756, the link of HGNC is changed to HGNC symbol. In current implementation, the system consider HGNC Symbol and HGNC as separate database.

"Official Symbol" is showing because it comes from Gene Cards not from HGNC/HGNC Symbol.

**Comment by jvwong** [comment]
In the image I posted for UniProt data returned, the `type: HGNC` entry in `dbReferences` has a properties['gene description'] that appears to be the HGNC symbol. Is this safe?

**Comment by IgorRodchenkov** [comment]
What about opening those links (in the gene info box) in a separate tab/window (it still replaces current page)?

**Comment by IgorRodchenkov** [comment]
"HGNC Symbol" is the primary official name for the HGNC catalog of gene names (also known as GeneId, gene name, etc.). 
Okay, if, in some rare case, we have UniProt ID, HGNC ID (like HGNC:1234) but no gene symbol (is indeed that possible?), then let's create a link to identifiers.org/hgnc/HGNC:1234...

**Comment by IgorRodchenkov** [comment]
Another related to this issue:
the ID pattern in https://www.ebi.ac.uk/miriam/main/datatypes/MIR:00000323 seems incorrect, which makes some GeneCard links (URIs) like `http://identifiers.org/genecards/IGLV3-10` unresolvable.

So, I requested MIRIAM/Identifiers.org to fix and update the record for GeneCards.
