### ISSUE TITLE
Make it more obvious that complexes start collapsed

### ISSUE THREAD

**Issue by hmtinc** [PathwayCommons/app-ui#79]
@cannin 
https://github.com/PathwayCommons/pathways-search/issues/131

> I wouldn't expect users to read the manual first, and it isn't obvious that the complexes start collapsed.

>Maybe using cookies, try to identify the first time a user visits the site and make them more aware of things they need to know (symbols, complex information, etc) in a modal or toggleable text.

**Comment by maxkfranz** [comment]
Use localStorage, not cookies
