### ISSUE TITLE
ServerAPI method querySearch mangles searches terminating with <db>:<id> 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#790]
## Current (buggy) behaviour

 
We allow query of the format `q=db:id` to signify referral from biological database. A requirement is that the pathway search sent to PC web service uses only the `id` portion. To this end, the [`querySearch`](https://github.com/PathwayCommons/app-ui/blob/62d497192378d9614df05db5041bfbcf7bda6479/src/client/services/server-api/index.js#L29) tests for this pattern and strips out the `db:` prefix:

> /src/client/services/server-api/index.js#L29
```js

const ServerAPI = {
...
  querySearch(query){
    const queryClone=_.assign({},query);
    if(/(uniprot:\w+|ncbi:[0-9]+|hgnc:\w+)$/.test(queryClone.q)){queryClone.q=queryClone.q.split(':')[1];}
    return fetch(`/pc-client/querySearch?${qs.stringify(queryClone)}`, defaultFetchOpts).then(res => res.json());
  },
...
}
```   
Edge case (rare) is  that when multiple tokens are entered, with the final one being of the format `db:id` then entire query including and before the `db:` prefix is removed.

Example case: Search for [`MDM2 ncbi:7157 `](http://appsbeta.pathwaycommons.org/search?gt=0&lt=250&q=MDM2%20ncbi%3A7157%20&type=Pathway) results in a PC search with `q=7157`.   

## Desired behaviour

The search should ideally send the entire search phrase as is

**Comment by IgorRodchenkov** [comment]
I think, we introduced db:id queries as a special case for linkout/cross-reference from UniProt, GeneCards, NCBI. Ideally, we should not allow multiple terms in such queries. Jeff is right - typing db:id plus other words in the text input field needs to be processed as it used to be before introducing db:id feature...
Good catch!

**Comment by maxkfranz** [comment]
Wouldn't it make sense that ehe `db:id` format should be valid to use everywhere in the app-ui code -- except just before passing the ID to external PC services?
