### ISSUE TITLE
App hangs and throws error upon slow/failed response from g:Profiler

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#805]
## Environment info

- Browser version (client) : n/a
- Node.js version (server) : 8

## Current (buggy) behaviour

The search is non-responsive (spinner) when trying to search for any term. This coincides with non-responsive calls to g:Profiler's  g:Convert.

![image](https://user-images.githubusercontent.com/4706307/40815306-89d7be82-6513-11e8-947b-8a6b40a3f691.png)

The server console outputs the following:

```js
(node:10781) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without acatch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
(node:10781) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'substring' of undefined
    at cleanUpEntrez (/Users/jeffreywong/Projects/PathwayCommons/web/app-ui/src/server/enrichment/helper/clean-up-entrez.js:5:20)
    at _.forEach.info (/Users/jeffreywong/Projects/PathwayCommons/web/app-ui/src/server/enrichment/validation/index.js:78:26)
    at arrayEach (/Users/jeffreywong/Projects/PathwayCommons/web/app-ui/node_modules/lodash/lodash.js:508:11)
    at Function.forEach (/Users/jeffreywong/Projects/PathwayCommons/web/app-ui/node_modules/lodash/lodash.js:9334:14)
    at fetch.then.then.body (/Users/jeffreywong/Projects/PathwayCommons/web/app-ui/src/server/enrichment/validation/index.js:75:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

## Desired behaviour

Should ideally allow failure of dependencies gracefully and enable return of PC web service results. 

## Minimum steps to reproduce

Running search locally. Search by clicking sample search.

**Comment by jvwong** [comment]
@CaitlinOCallaghan let's both take a stab at this. Idea is the `validator` should honour its contract to clients even in the case where the underlying dependency (i.e. g:Convert)  1. is unreasonably slow to respond or 2. fails. My fault for not looking into all these Promise/fetch/catch...

Tasks
 - [ ]   TODO.

**Comment by maxkfranz** [comment]
For now, could we revert the problematic commit?  The bugs can be addressed in the feature branch and a new PR can be made once everything's working.

**Comment by jvwong** [comment]
It's not a problematic commit. It's that the implementation of the service itself was never acknowledging/handling this case.

**Comment by maxkfranz** [comment]
OK, but reversing the merge that uses the service would have the same "fixing" effect.  We didn't have problems when we we're using it in the UI, right?
