### ISSUE TITLE
app-ui v1.0.0 release

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#811]
@IgorRodchenkov @maxkfranz @d2fong 

Before it gets away, is it time to tag and draft a release? 

Outstanding questions:

- [ ] Test production build  
- [ ] Choosing a dev commit to merge to master
- [ ] [Freeze cytoscape.js version](https://github.com/PathwayCommons/app-ui/issues/771#issuecomment-393209917)  
?

**Comment by IgorRodchenkov** [comment]
Let's do it.
I deployed the latest (yesterday) development branch code to http://appsbeta.pathwaycommons.org/ - production build, connects to beta PC10.

**Comment by jvwong** [comment]
@IgorRodchenkov do you remember which commit? I noticed some [weird error](http://appsbeta.pathwaycommons.org/view?removeInfoMenu=true&title=RB1%20controls%20expression%20of%20POLR2A&uri=http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FTemplateReactionRegulation_b57de0c2e11853d3c096a0a79020ea92) that doesn't happen on the latest dev.

**Comment by IgorRodchenkov** [comment]
Alright, I am going to create a PR for merging current develoipment into master, try it manually, merge, tag as a release. 
Any objections, last minute issues? @d2fong @jvwong

**Comment by maxkfranz** [comment]
Let's hold off merging any non-bug-fix PRs to dev until we have 1.0.0 released.

After 1.0.0 is released, each bug-fix PR will have to be evaluated on master and dev.  If the issue affects both, either we'll have to do cherry-picking back to master or do two PRs per bug-fix.

**Comment by IgorRodchenkov** [comment]
@maxkfranz I am branching from master, merging there from development; so we'll do final touch-ups there. The development can be uses as before - no special restrictions are required, I think.

PS:
Remember that when you switch betweeb PC servers by using PC_URL environment option - to test, try, fix something - then you should probably also purge the rethinkdb and re-generate the generic-phyiscal-entity-map.json file (but not necessarily push it).

**Comment by IgorRodchenkov** [comment]
@maxkfranz @jvwong 
(I am making app-ui release from v1.0.0 branch)
Shall I fix the cytoscape version or smth? Curently, we have 
`"cytoscape": "git+https://github.com/cytoscape/cytoscape.js.git#unstable"`
in the package.json, and new package-lock.json from time to time.

**Comment by IgorRodchenkov** [comment]
@d2fong @jvwong 
Do you know what are those errors and how to fix
(I build-prod and run the app in production, using beta PC10 URL as PC_URL)?
![screenshot from 2018-06-14 09-39-20](https://user-images.githubusercontent.com/991169/41415768-51398818-6fb7-11e8-8e7d-8849fec4adf8.png)

**Comment by jvwong** [comment]
I ran prod locally with `beta.pathwaycommons.org` and works fine.

**Comment by IgorRodchenkov** [comment]
ok

**Comment by IgorRodchenkov** [comment]
@jvwong @d2fong 

Trying to release (in v1.0.0 branch), following the README, had to run _test_ first - 

PC_URL="http://beta.pathwaycommons.org/pc2/" npm test

2 tests fail:
```
43 passing (18s)
  2 failing

  1) Test saveDiffs.js saveDiffs Optionally accepts a callback:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  2) Test update.js saveLayout optionally accepts a callback:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by jvwong** [comment]
>2 tests fail: 

see https://github.com/PathwayCommons/app-ui/pull/827

**Comment by IgorRodchenkov** [comment]
Great. @jvwong @d2fong @maxkfranz 
Now, shall we fix or ignore all the errors printed by: `npm run lint` ?

**Comment by maxkfranz** [comment]
As a rule, we should have all CI checks (incl. linting) pass in order to do a release -- or even to merge a PR.

Could we update the dev branch to make the CI do linting checks, like Factoid does?

- https://github.com/PathwayCommons/factoid/blob/master/.travis.yml
- https://github.com/PathwayCommons/factoid/blob/master/package.json

**Comment by jvwong** [comment]
I think we're done here.

 There is a failing test (#854) which really only affects the `/enrichment` services, which aren't even supposed to be part of this release.
