### ISSUE TITLE
Receive and Interpret Validation Response

### ISSUE THREAD

**Issue by CaitlinOCallaghan** [PathwayCommons/app-ui#815]
If ' unrecognized [] ' && ' duplicate [] ' empty, continue to analysis ( do nothing for now ) 
If arrays !empty, provide user feedback indicating invalidity (unrecognized and/or duplicates)

- [ ] underline tokens violating input conventions
- [ ] pop up message indicating type of invalidity 
                  if multiple instances of same type of infraction, only provide one message
                  if input token count < 4, ask for larger input 

## Test cases: 

1. All valid
   genes: [ 
      "TP53",
      "ATM",
      "MCM3",
      "XPO1"
   ]

2. One unrecognized
   genes: [ 
      "notAGene",
      "TP53",
      "ATM",
      "MCM3",
   ]

3. One set duplicate
   genes: [ 
      "TP53",
      "TP53",
      "ATM",
      "MCM3",
   ]

4. One set duplicate and one unrecongnized
   genes: [      
      "notAGene",
      "TP53",
      "TP53",
      "ATM",
   ]

5. All valid, but not enough tokens
   genes: [ 
      "TP53",
      "ATM",
      "MCM3",
   ]

**Comment by jvwong** [comment]
Do we mark valid IDs explicitly or just leave as is.

**Comment by CaitlinOCallaghan** [comment]
For now, leave as is and once everything is up and running we can add that feature

**Comment by jvwong** [comment]
We're all realizing how non-trivial this task is. Let's reduce the scope of this component for now:

- [x] Accept text input
- [x] Display unrecognized tokens
- [ ] Provide an array of unique recognized gene identifiers (i.e. for parent component)
