### ISSUE TITLE
Show interaction filter icon/panel, regardless of viewport width

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#817]
## Description of new feature

The interaction filter should be available, irrespective of browser width. 
Currently, this is not the case.
![image](https://user-images.githubusercontent.com/4706307/41105397-a8338b4a-6a3b-11e8-9778-e0ce56ead7b1.png)

## Motivation for new feature

The user will always be able to view and filter all available edges.

**Comment by q4wen** [comment]
This issue is done and can be closed.
