### ISSUE TITLE
Managing User Node Selection for Drill-Down

### ISSUE THREAD

**Issue by MichaelWrana** [PathwayCommons/app-ui#819]
I'm working on a feature which will allow users to select a group of nodes and hide them from view to reduce clutter
### Question
How should the user be allowed to select a group of nodes to hide?
### Some Potential Solutions
- shift+left-click+drag to select an area of nodes, menu-bar buttons to hide/show
- shift+left-click a node to add it to a selection list, menu-bar buttons to hide/show
- add a tooltip toggle, then add nodes to selection list with left-click, menu-bar buttons to hide/show
- A new side-menu (like downloads), with hide/show buttons and a list where selected nodes can be viewed

More Info: Google Doc

I wanted to get some input on which option seems the most natural to users before coding anything.

**Comment by jvwong** [comment]
- Google Slides/Powerpoint:
  - click (outside glyph) + drag to select region
  - shift + click(inside glyph) to select multiple
