### ISSUE TITLE
Console error:  Launching tooltip for entity with no metadata.name 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#821]
## Environment info

- Browser version (client) : Chrome Version 67.0.3396.79
- Node.js version (server) : n/a

## Current (buggy) behaviour

Console Error:

```js
index.js:25 Uncaught TypeError: Cannot read property 'push' of null
    at new MetadataTip (index.js:25)
    at Element.<anonymous> (show-tooltip.js:20)
    at _loop2 (emitter.js:214)
    at emitter.js:193
    at forEachEventObj (emitter.js:91)
    at Emitter.p.emit.p.trigger (emitter.js:181)
    at Core.emit (events.js:80)
    at emitter.js:226
    at forEachEventObj (emitter.js:118)
    at Emitter.p.emit.p.trigger (emitter.js:181)
```
references `src/client/common/cy/tooltips/index.js`

```js
...
  constructor(name, data, cyElement) {
...      }else{
        this.data.push(["Search Link",this.name]);
      }
   ...
  }

...
``` 
![image](https://user-images.githubusercontent.com/4706307/41175436-0c7d497a-6b2b-11e8-884d-53a78a2cfcaf.png)

## Minimum steps to reproduce

Pathway view of  [TP53 controls expression of GDF15 | CTD](http://localhost:3000/view?removeInfoMenu=true&title=TP53%20controls%20expression%20of%20GDF15&uri=http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FTemplateReactionRegulation_f1400b6e5b133c647a396106e5f05fad)

Click the source/sink glphy.

**Comment by MichaelWrana** [comment]
Should be resolved with #810
