### ISSUE TITLE
Pathway physical entity tooltips absent of links for xref fields (uniprot etc)  

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#822]
In reviewing #704 I was comparing tooltips in the development branch with production. I noticed  many instances where the `Links` section was different or even absent in the dev.

For instance:

Production for [Valine, leucine and isoleucine biosynthesis | KEGG](http://apps.pathwaycommons.org/view?uri=http%3A%2F%2Fidentifiers.org%2Fkegg.pathway%2Fhsa00290)

![image](https://user-images.githubusercontent.com/4706307/41182128-61612206-6b42-11e8-8bbe-f7feb780689e.png)

Development: 

![image](https://user-images.githubusercontent.com/4706307/41182184-8de657b0-6b42-11e8-9446-612b95e3ae78.png)

**Comment by MichaelWrana** [comment]
The issue here was no data was being collected for the Entity References' cross-references.

Fixed in #810
