### ISSUE TITLE
Add "smart-slider" to interactions page

### ISSUE THREAD

**Issue by MichaelWrana** [PathwayCommons/app-ui#831]
## Description of new feature

- Add a new slider to the `interaction` view
- When slid, nodes would disappear and reappear based on degree AND node metadata
- Eg. nodes with more publications should be hidden less often than nodes without.

## Motivation for new feature

Degree is generally a good guess for the importance of network nodes on the `interaction` page.  However, it might be possible to take advantage of the BioPAX metadata to provide an improved slider.

**Comment by jvwong** [comment]
Just going on experience, the 'co/citation' edge-weighting 1. introduces an additional dependency  2. prioritizes things based on a dubious criteria. From our experience, there might be some who would want to filter on data source, but not a lot. Let's close and focus on the other issues.
