### ISSUE TITLE
Improve area-selection functionality on `view` page

### ISSUE THREAD

**Issue by MichaelWrana** [PathwayCommons/app-ui#832]
## Description of new feature
- shift+left-click+drag to select a group of interactions
- highlight selected nodes similarly to search bar
- focus on the interaction nodes within the selection area

## Motivation for new feature
Hiding/showing nodes in the `view` page doesn't make sense with a slider.  More connections doesn't typically imply more important in these networks.  In order to implement hide/show functionality the user will have to select nodes themselves.

**Comment by jvwong** [comment]
Duplicate of meta-issue #833.
