### ISSUE TITLE
Fix lint errors before v1.0.0 release

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/app-ui#834]
(development) npm run lint:

`✖ 33 problems (33 errors, 0 warnings)`

refs #811

**Comment by d2fong** [comment]
That’s a lot of problems

**Comment by maxkfranz** [comment]
OK, maybe we should just worry about that for a later release then.  The students could clean up the lint errors and we could do a 1.0.1 release afterwards.

**Comment by q4wen** [comment]
`console.log()` causes `Unexpected console statement  no-console` error. Should we remove `console.log(err)` or disable `no-console` rule in lint?

**Comment by maxkfranz** [comment]
You shouldn't be using `console.log()` for logging errors.  There's a logger module that can be used to log to the console and to log files using winston.  It has the same interface as `console`.

There are three log levels:

- `console.log()` -- debug level, e.g. query hit an edgecase
- `console.info()` -- info level, e.g. served this query
- `console.error()` -- error level, e.g. query failed
