### ISSUE TITLE
Show/hide actions

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#842]
@MichaelWrana does it make sense to 'show only selected' rather than 'hide selected'?

**Comment by MichaelWrana** [comment]
I’ve already written code for “show only selected” and “hide selected” so changing or adding that would only take a few minutes.

It’s more a question of what would be most inuitive to the user.  I’m concerned with adding too many buttons for the select feature so replacing is preferable.

Maybe we should get some user input for this one?
