### ISSUE TITLE
Custom approach for direct fetch from genenames.org for query hgnc:<id> pattern

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#857]
//TODO 
// https://rest.genenames.org/fetch/symbol/TP53

**Comment by q4wen** [comment]
The return JSON does not contains description or other database links. If the validator fails, the landing page will only show official name, alias and a link to HGNC. Should the landing box still be displayed?

**Comment by q4wen** [comment]
As describe above, if the validator fails, the landing page from HGNC will be like this:

![screen shot 2018-07-03 at 4 35 26 pm](https://user-images.githubusercontent.com/16858225/42243395-2f0bdc00-7edf-11e8-81cd-2e10cbc23742.png)

**Comment by jvwong** [comment]
There **may** be other db links for UniProt, NCBI Gene (Entrez). Not always the case. 

Below for [TP53](http://rest.genenames.org/fetch/symbol/TP53) there are IDs for both:

```json
{
   ...
    "response": {
        ...
        "docs": [
            {
                "hgnc_id": "HGNC:11998",
                "symbol": "TP53",
                "name": "tumor protein p53",               
               ...
                "entrez_id": "7157",
                ...
                "uniprot_ids": [
                    "P04637"
                ],
               ...
            }
        ]
    }
}
```

The gene for a microRNA [MIRLET7A1](http://rest.genenames.org/fetch/symbol/MIRLET7A1) is a gene that doesn't have a protein (so no UniProt) but has a NCBI Gene entry (Entrez)

```js
{
   ...
    "response": {
       ...
        "docs": [
            {
                "hgnc_id": "HGNC:31476",
                "symbol": "MIRLET7A1",
                "name": "microRNA let-7a-1",
              ...
                "alias_symbol": [
                    "hsa-let-7a-1"
                ],
               ...
                "entrez_id": "406881",
             ...
        
            }
        ]
    }
}
```
