### ISSUE TITLE
Client-side network filtering tasks

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#859]
- [x] Server shall return everything to client
- [ ]  Calculate and store centrality on client
- [ ] Find default slider value so n=20 nodes are shown
  - cytoscape.js: eles.sort(), slice()

Later on let's push this to server...

**Comment by MichaelWrana** [comment]
When determining centrality, should I only consider the visible edges, or is it ok to include all potential edges in the graph. (eg: binding edges visible vs binding & expression edges visible)

**Comment by jvwong** [comment]
Good question. Are you thinking that if you calculate on ALL, filtering might lead to sparse, empty graph?

**Comment by MichaelWrana** [comment]
Yes, and we might end up with nodes not hiding and showing accurately, since the edges that make them 'central' are not visible.  Like what we saw yesterday with the two nodes that appeared to be disconnected from the main network.

**Comment by jvwong** [comment]
My suggestion is to keep it simple: consider ALL for now.

Filtering was really a stop-gap: Ideally users won't need it and we won't need to do it. Also it would be complex to have the client fetch from server each time there is a filter event.

**Comment by maxkfranz** [comment]
By reducing the number of nodes with the centrality calculation, it may be possible to show all the edge classes without too much clutter.  But that's only valid if you include all edges in the calculation.

For now, I would show all edges by default.

**Comment by MichaelWrana** [comment]
All this is finished client-side, using all edges in the graph in PR #853
