### ISSUE TITLE
Interactions: Client unnecessarily filters network for source parameter   

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#863]
Launching interactions with parameter `source=<string>`, where value is not HGNC symbol, completely filters out the network data that is returned. I'd expect it to display data.

**Comment by jvwong** [comment]
See [src/client/features/interactions/index.js](https://github.com/PathwayCommons/app-ui/blob/57e0abf8fe2ff73df0d6618f228278cc79b51393/src/client/features/interactions/index.js#L80)

```js
...
class Interactions extends React.Component {
...
    this.state.cy.on('trim', () => {
      const state = this.state;
      const ids = state.ids;
      if(ids.length === sources.length){
        const cy = state.cy;
        const mainNode = cy.nodes(node=> ids.indexOf(node.data().id) != -1);
        const nodesToKeep = mainNode.merge(mainNode.connectedEdges().connectedNodes());
        cy.remove(cy.nodes().difference(nodesToKeep));
      }
    });
...
module.exports = Interactions;
```

**Comment by maxkfranz** [comment]
```js
const mainNode = cy.nodes(node=> ids.indexOf(node.data().id) != -1);
```

This line looks slow.  It looks like it should be using a Cytoscape collection instead of `ids`. A collection acts like a set and can be queried like a map by ID.

**Comment by maxkfranz** [comment]
Also you're using `merge()` without creating an empty `cy.collection()` first.  That will cause bugs.

**Comment by jvwong** [comment]
This is overlapping with @MichaelWrana 's work #859 since this will likely all move back to server or get cut out altogether.

The original intent of all this (I suspect) was to show/highlight nodes connected to the user's query (source parameter). When `source=<HGNC SYMBOL>` that's trivial, since SIF returns HGNC. Not so easy in other cases.

**Comment by jvwong** [comment]
@MichaelWrana @q4wen - What do you think about just deleting the entire block of code above? Then we can simply do [`source=http://identifiers.org/uniprot/Q99988`](http://localhost:3000/interactions?source=http://identifiers.org/uniprot/Q99988)
