### ISSUE TITLE
Correctly spell database names in display text   

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#864]
Cases:

- Landing box
  - [x] `UniProt`
  
![image](https://user-images.githubusercontent.com/4706307/42227369-5cff6274-7eaf-11e8-98a4-fd66fae63df9.png)

- Pathway view tooltips
  - [ ] `UniProt`
  - [ ] `HGNC` rather than `HGNC Symbol`
![image](https://user-images.githubusercontent.com/4706307/42227438-86fa3d2e-7eaf-11e8-8914-d7455689544e.png)

**Comment by MichaelWrana** [comment]
There are separate cases for links to be named as "HGNC" vs "HGNC Symbol" : 

![screen shot 2018-07-04 at 10 15 46 am](https://user-images.githubusercontent.com/25777239/42282033-3e47f7fa-7f73-11e8-91a8-195456e0483f.png)


Should I combine or leave as-is?

**Comment by jvwong** [comment]
Let's leave this alone. Its not worth changing.

**Comment by jvwong** [comment]
The tooltip link to UniProt is still spelled incorrectly:

![image](https://user-images.githubusercontent.com/4706307/43078028-30518ec0-8e57-11e8-848c-3ab7ff5801e1.png)
