### ISSUE TITLE
SIF viewer layout should only run on visible elements

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/app-ui#867]
## Environment info

- Browser version (client) : Chrome latest
- Node.js version (server) : Node 8

## Current (buggy) behaviour

The layout runs on hidden nodes

## Desired behaviour

Only include visible elements.  Better for performance and visual result

## Minimum steps to reproduce

1. Toggle some edges off, e.g. expression
1. Run the layout
1. Node empty space

**Comment by jvwong** [comment]
Possibly related: Fit to screen

**Comment by maxkfranz** [comment]
> Possibly related: Fit to screen

Yes, it should be `cy.fit(visibleEles)` not `cy.fit()` all.

**Comment by MichaelWrana** [comment]
The Fit to Screen button seems to be running on only visible elements, I think the layout is a separate issue:


![screen-recording-2](https://user-images.githubusercontent.com/25777239/43272395-dab70bf2-90c7-11e8-851d-d9c200cae458.gif)
