### ISSUE TITLE
Hover highlight should use opacity

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/app-ui#868]
## Description of new feature

The hover highlight should not change node or edge colour.  It should instead fade out the other edges and nodes.

## Motivation for new feature

You can still see the edge colours.

**Comment by jvwong** [comment]
I don't see this functioning on the SBGN/pathway views but it works on ball-stick views.

**Comment by MichaelWrana** [comment]
It looks like @d2fong is doing a major rework of the pathway view, which I think is related to the hover stuff.  Maybe it no longer works because pathway view now has its own event files?

**Comment by MichaelWrana** [comment]
Update: Should work for SBGN view now with #925

**Comment by jvwong** [comment]
I find that the highlight on hover for edges rather cumbersome, especially when there are a lot of elements on the screen. Would it be better to highlight on node only?

**Comment by maxkfranz** [comment]
I agree nodes only is probably less jittery.  It's too easy to inadvertently hover over an edge in dense graphs.
