### ISSUE TITLE
Managing state variables

### ISSUE THREAD

**Issue by gaelder** [PathwayCommons/app-ui#87]
Many pathway instances have state variables that are ambiguous, distracting and often not very helpful.

https://github.com/PathwayCommons/pathways-search/issues/98

**Comment by jvwong** [comment]
This arose again:  I was interested in viewing some BioPAX in the app and seeing an entity pool node with state variable 'phosphorylated' - the entity also had a state variable 'active'. In this case 'active' was shown but not the 'phorphorylated'.
  
Need a way to either 1. show multiple OR 2. prioritize. 

See https://github.com/PathwayCommons/pathways-search/issues/98.

**Comment by jvwong** [comment]
Moving this to https://github.com/PathwayCommons/sbgnml-to-cytoscape/
