### ISSUE TITLE
Hover + zoom leads to 'supersized' glyphs in viewer

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#870]
Consider a pathway that is zoomed out: Highlighting a glyph (by mousing over) then zooming in leads to glyphs that are very large. 

One would expect the glyphs to be the same size at any time during the zoom.

I have reproduced an example for the [Transcriptional activation of cell cycle inhibitor p21 | Reactome](http://localhost:3000/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-69895) by zooming out, hovering over process node, then zooming in while maintaining hover: 

![zoombug](https://user-images.githubusercontent.com/4706307/42249953-04df751e-7efc-11e8-98cd-2d80a628f8ad.gif)

**Comment by maxkfranz** [comment]
We should probably just rework the highlight this and nix the font changes altogether: 

Hover highlight should use opacity #868
