### ISSUE TITLE
Increases minimum zoom so that pathway features are still viewable   

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#871]
Currently pathways an be zoomed out to the point where little detail is discernable. Increase the minimum zoom.

E.g. [Transcriptional activation of cell cycle inhibitor p21 | Reactome](http://localhost:3000/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-69895):

![image](https://user-images.githubusercontent.com/4706307/42250048-9addc9d0-7efc-11e8-9fc7-b365a1bd7b6b.png)

**Comment by maxkfranz** [comment]
We have to take into account the size of all networks.  Larger graphs need a smaller min zoom for initial fitting.

**Comment by jvwong** [comment]
Are there cases where users want to zoom out beyond the 'fit to screen'?

**Comment by maxkfranz** [comment]
Yes.  If you lose your place, you want to zoom out far to see everything and then zoom back in.  If you stop at the fitted level, then some things may still be off-screen.

It's probably best to be liberal about the value.  Maybe something like 0.1 or 0.2.  The main thing is that the network shouldn't be so small to become a dot.
