### ISSUE TITLE
refactor landing box

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#875]
The design, general code quality, and performance of the landing box page need to be improved.

**Comment by jvwong** [comment]
See https://github.com/PathwayCommons/app-ui/pull/869#issuecomment-402716919

**Comment by jvwong** [comment]
Just so this is not lost:

> 1. [This commit](https://github.com/PathwayCommons/app-ui/commit/733274da90f7b67d64c9abf4076b297756569925) inadvertently removed the 'Official Symbol' field. This is part of #875.

> 2. Same commit inadvertently removed the 'View Interactions Between Entities' link parameter. Also will be addressed in #875.

> 3. We should use Gene Cards recommended link instead:

> Linking to particular GeneCards
>If you are a web developer and you want to make links to particular GeneCards, use 
"https://www.genecards.org/cgi-bin/carddisp.pl?gene=XXX" (with XXX being the gene symbol).

>  To link using an external id, use "https://www.genecards.org/cgi-bin/carddisp.pl?id=YYY" 
(where YYY is a UniProt accession, EntrezGene id, Ensembl id, or HGNC id).
> Optionally, a source for the id can be specified by adding "&id_type=" to the url. The possible types are "uniprot", "entrezgene", "ensembl", and "hgnc". To avoid confusion, it is strongly recommended to use the id_type parameter, especially for numeric ids.
