### ISSUE TITLE
Painter failing for some pathways

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#879]
- Setup: 
  - bash env
    - `PC_URL: 'http://beta.pathwaycommons.org/pc2/'`
    - `PC_VERION: '10'`
  - Cytoscape v3.6.1
  - Enrichment Map v3.1.0

Painter app fails in certain cases, complaining

![image](https://user-images.githubusercontent.com/4706307/42297845-484d17b4-7fd0-11e8-9b17-60646b7f2ca0.png)

Reproduce (see me for `em.cys` file):

Cytoscape enrichment map, pathway: GLYCEROPHOSPHOLIPID BIOSYNTHESIS%REACTOME%R-HSA-1483206.4

**Comment by jvwong** [comment]
Why are valid genes greyed out:

![image](https://user-images.githubusercontent.com/4706307/42329474-c00dee22-803e-11e8-8dca-d30220c5b491.png)

**Comment by IgorRodchenkov** [comment]
PC_VERSION is not app's option, but is only to be used with src/scripts/updtae.sh to generate new generic entities to gene names mapping! Also - see the latest README - the value should be "v10" not "10", "v9" not "9" - it's a directory name in pathwaycommons.org/archives/PC2/

**Comment by jvwong** [comment]
duplicate of #890
