### ISSUE TITLE
Server Side Technical Debt

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#897]
- [x] remove layout/pathway caching
- [x] unmaintainable metadata generation code ( need Igor's new service )
- [x] general code quality improvements needed

## WHY
Pathway commons creates new releases every N months with entirely new uris for pathways.  It will never be feasible to store human created layouts while this happens and it adds too much complexity to the system for marginal gain.

**Comment by IgorRodchenkov** [comment]
Lately, I've a little bit maintaided that "unmaintainable metadata generation code" :))
