### ISSUE TITLE
Save layout positions per layout option

### ISSUE THREAD

**Issue by gaelder** [PathwayCommons/app-ui#90]
Use Case:

I run the klay layout and play around with it moving a few nodes, etc.
I then run the dagre layout and then play around with it.
I switch to the klay layout and it should look exactly as it was before I ran the dagre layout
Potential complications:

What if I actually want to run the klay layout again instead of always going back to my modified version?

https://github.com/PathwayCommons/pathways-search/issues/107

**Comment by maxkfranz** [comment]
I would keep algorithmic layouts separate from manual (saved) layouts.
