### ISSUE TITLE
Color Enrichment Nodes by P-Value 

### ISSUE THREAD

**Issue by CaitlinOCallaghan** [PathwayCommons/app-ui#900]
## Description of new feature

 - color enrichment nodes based on p-value
 - render side menu to display color legend
 - rename 'p-value' property to 'p_value'

**Comment by CaitlinOCallaghan** [comment]
Most of the p-values seem to be less than .1 - would logarithmic scale be best to help show the subtle differences between nodes?

**Comment by maxkfranz** [comment]
Generally, with a p-value you want to know whether it's less than the threshold or not: https://en.wikipedia.org/wiki/P-value#Definition_and_interpretation

So you could just use two colours, one for within the threshold and one for outside.  You could use gradients for the two colours to show how close to the threshold they are.

For example:

No gradient case:

0  <= pVal <= 0.05 is green
0.05 < pVal <= 1 is white (regular bg colour)

Gradient case:

0 => 0.05 is dark green to light green
0.05 => 1 is light yellow to white
