### ISSUE TITLE
SIF download option broken for enrichment

### ISSUE THREAD

**Issue by CaitlinOCallaghan** [PathwayCommons/app-ui#909]
## Current (buggy) behaviour

New cytoscape changes broke SIF download option for enrichment

## Minimum steps to reproduce

Download enrichment network as SIF file

**Comment by IgorRodchenkov** [comment]
Example? Steps to reproduce?
Please double-check to confirm this is still problem (because there was a temporary problem with CORS filters configuration on PC2 server, which also caused downloads fail on the app-ui pathway view pages...)

**Comment by jvwong** [comment]
@IgorRodchenkov this isn't referring to the web services but rather a 'json-to-sif' feature in-browser.

**Comment by jvwong** [comment]
Let's take a pass on this feature for now. I'm not sure its useful.
