### ISSUE TITLE
More accurate graph size in the listing

### ISSUE THREAD

**Issue by gaelder** [PathwayCommons/app-ui#91]
num interactions is taken from the pathway commons response, but that is not necessarily how large the graph will be once nodes are filtered.
A better estimate would be to take cy.nodes().size().

Requires - refactor cy to be passed as a prop instead of being localized state of the viewer

https://github.com/PathwayCommons/pathways-search/issues/111

**Comment by maxkfranz** [comment]
Interactions would be `cy.edges().length` -- not nodes

**Comment by jvwong** [comment]
Technically the num Interactions is correct with respect to the BioPAX. I think the main reason for the discord are things like bp:memberPhysicalEntity which are not displayed in SBGN-ML. Close.
