### ISSUE TITLE
Tooltip mockups

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#911]
## Description of new feature

TODO

**Comment by CaitlinOCallaghan** [comment]
![image](https://user-images.githubusercontent.com/38890251/43022184-600cc94c-8c34-11e8-8b49-e9d931e886ae.png)


- 'information' is received from GO or Reactome API
- 'more information' links to corresponding GO or Reactome page 
- 'search pathway' links to PC w query = pathwayName

- ***the wording for 'intersecting genes in pathway and entered list' needs improvement 
- genes will be listed in alphabetical order

**Comment by CaitlinOCallaghan** [comment]
![image](https://user-images.githubusercontent.com/38890251/43022447-56bd8e34-8c35-11e8-96ed-3217dcab9e6e.png)

For Edges

- again, wording is up for debate
- **** wording to describe intersecting gene names will be uniform for edges and nodes
- is there any other information that should be added?

**Comment by jvwong** [comment]
In general, 'shared genes' makes sense to me. 
This looks good enough to get going on implementation. Don't agonize too much about styling, interactivity.
