### ISSUE TITLE
Undefined CSS

### ISSUE THREAD

**Issue by MichaelWrana** [PathwayCommons/app-ui#912]
## Environment info

- Browser version (client) : N/A

## Current (buggy) behaviour

When running `npm run watch` the following errors appear

![screen shot 2018-07-18 at 10 16 36 am](https://user-images.githubusercontent.com/25777239/42887408-e75e3e16-8a73-11e8-88a0-09ae15b05f46.png)

## Desired behaviour

`undefined [undefined]` should not be there

## Minimum steps to reproduce

`npm run watch` in console

**Comment by jvwong** [comment]
fixed in https://github.com/PathwayCommons/app-ui/commit/de3647490d6d31500c426498f6056d80780491b7#diff-7168efd3b50f2bfaa667392a5503c157
