### ISSUE TITLE
Using SIFGraph web services 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#916]
## Description of new feature

Use the SIFGraph web services for interactions data.
http://www.pathwaycommons.org/sifgraph/swagger-ui.html

**Comment by q4wen** [comment]
New service does not contain node metadata (participant type, uniprot/hgnc id).
Old service:
http://www.pathwaycommons.org/pc2/graph?cmd=graph&source=TP53&pattern=controls-phosphorylation-of&pattern=in-complex-with&pattern=controls-expression-of&pattern=interacts-with&kind=neighborhood&format=txt&user=app-ui
![screen shot 2018-07-24 at 4 17 12 pm](https://user-images.githubusercontent.com/16858225/43163765-220efd82-8f5d-11e8-8c91-b17e65b99555.png)

New service: 
http://www.pathwaycommons.org/sifgraph/v1/neighborhood?direction=BOTHSTREAM&limit=1&pattern=CONTROLS_EXPRESSION_OF&source=TP53

**Comment by q4wen** [comment]
Some data is missing in the new SIF graph service:
1. node metadata (as mentioned in last comment)
2. `pubmedIds` of each interaction
3. Different interaction graph. For example, for interaction graph of TP53 and MDM2,
Old service: 
http://www.pathwaycommons.org/pc2/graph?cmd=graph&source=TP53&source=MDM2&pattern=controls-phosphorylation-of&pattern=in-complex-with&pattern=controls-expression-of&pattern=interacts-with&kind=pathsbetween&format=txt&user=app-ui
![screen shot 2018-07-26 at 12 10 14 pm](https://user-images.githubusercontent.com/16858225/43274326-ee4e0ea4-90cc-11e8-9a65-d04b60b9007d.png)


 New service:  
 http://www.pathwaycommons.org/sifgraph/v1/pathsbetween?directed=false&limit=1&pattern=CONTROLS_PHOSPHORYLATION_OF&pattern=IN_COMPLEX_WITH&pattern=CONTROLS_EXPRESSION_OF&pattern=INTERACTS_WITH&source=TP53&source=MDM2
![screen shot 2018-07-26 at 12 09 01 pm](https://user-images.githubusercontent.com/16858225/43274276-c42493e6-90cc-11e8-9422-2f739dd0fe8a.png)
<br/>

Am I requesting the SIF graph service correctly? I am not sure about the parameters (directed, limit and pattern). @jvwong @IgorRodchenkov

**Comment by maxkfranz** [comment]
It looks like there is a slightly larger result if you remove the pattern filter: http://www.pathwaycommons.org/sifgraph/v1/pathsbetween?directed=false&limit=1&source=TP53&source=MDM2

But this still doesn't look close to the old service result.

**Comment by IgorRodchenkov** [comment]
Try adding  direction=undirected parameter.

PS:
We are to use Sifgraph service anyway... I will look into which metadata we want and how better to get it from either web services next week. 

IR

**Comment by IgorRodchenkov** [comment]
i.e. use direction=undirected with neighborhood type queries to get similar to PC2 sif result

IR

**Comment by IgorRodchenkov** [comment]
Parameters are described here:

http://www.pathwaycommons.org/sifgraph/swagger-ui.html

IR

**Comment by maxkfranz** [comment]
> i.e. use direction=undirected with neighborhood type queries to get similar to PC2 sif result

OK, so it looks like `directed=false` became `direction=undirected` for the new SIF service

**Comment by IgorRodchenkov** [comment]
In sifgraph, yes, but  ‘directed’ parameter doesn’t apply to the neighborhood query, which still have ‘direction’.. 

Well, just see the swagger docs. The data are always returned in our extended SIF format (aka TXT).

IR

**Comment by IgorRodchenkov** [comment]
Also, PubMed IDs are still there in the 5th column; e.g.: 
http://www.pathwaycommons.org/sifgraph/v1/neighborhood?direction=UNDIRECTED&pattern=CONTROLS_EXPRESSION_OF&source=TP53

(NOTE: direction=UNDIRECTED  - **uppercase** - cause sifgraph is a bit less forgiving than PC2 - should now be used if we want to see interacts-with type edges; - because the default in the sifgraph service is BOTHSTREAM, for /v1/neighborhood ).

**Comment by q4wen** [comment]
> Also, PubMed IDs are still there in the 5th column; 

In PC2 service, we also have  `MEDIATOR_IDS ` in the 7th column. Does the new SIF graph service have the same format?

**Comment by IgorRodchenkov** [comment]
Please try and look at the data

IR

**Comment by jvwong** [comment]
> In PC2 service, we also have MEDIATOR_IDS in the 7th column. Does the new SIF graph service have the same format?

@q4wen please see https://github.com/PathwayCommons/app-ui/pull/938#pullrequestreview-141180261

More generally, the columns look the same:

|PARTICIPANT_A |	INTERACTION_TYPE|	PARTICIPANT_B|	INTERACTION_DATA_SOURCE|	INTERACTION_PUBMED_ID|	PATHWAY_NAMES|	MEDIATOR_IDS|
|---|---|---|---|---|---|---|

**Comment by IgorRodchenkov** [comment]
Well, okay, the new SIF graph service does not have exactly the same format as PC's TXT format - sifgraph returns only the first (interactions) section of the two-section TXT format...

So, we have to implement and add there a new query path, e.g., 'sifgraph/v1/nodes' (and also  'sifgraph/v1/nodes/<id>'), to return the node(s) metadata (can be JSON instead of TSV), or make it simply return (optionally) CyJSON ({network:{nodes,edges}}) data that the app (interactions) could use right away (app-ui wouldn't then need to parse to convert query result TXT into CyJSON data/metadata object).

**Comment by jvwong** [comment]
For the purposes of the apps, I personally care more about using the MEDIATOR_IDS (already there in section 1) to view the SBGN. Those PARTICIPANT_TYPES (in section 2) are all really just squished into the node. Unless someone wants to filter by PARTICIPANT_TYPES, etc.?
