### ISSUE TITLE
Layout picker heuristics

### ISSUE THREAD

**Issue by hmtinc** [PathwayCommons/app-ui#92]
@d2fong 
https://github.com/PathwayCommons/pathways-search/issues/128

>investigate possibility of choosing a layout based on some characteristics of the graph.

>Can we identify some simple rules to choose a default layout. e.g. if there are no compound nodes, then apply a force-directed layout, if there is one compound node with only nodes within it; if one compound node with nodes inside and out; if 2 or more compound nodes; if there are only a few edges betweeen compound nodes.
Dagre seems to work well:

>for graphs that have many connected components, with a small amount of connections between them
Dagre doesn't work that well for:
large graphs
graphs with many disconnected components
graphs that don't have an inherent tree structure
Klay works well for:

>large graphs, but it spaces nodes out too much
Klay doesn't work that well for:
graphs that have many connected components
Force Directed works well for:

>graphs without compound nodes
graphs that have already been run with klay / dagre
Force Directed doesn't work well for:
many graphs and I don't know why

**Comment by jvwong** [comment]
This is just too open-ended. Probably it's own project. Closing.
