### ISSUE TITLE
Default Fetch Option 

### ISSUE THREAD

**Issue by q4wen** [PathwayCommons/app-ui#922]
## Current (buggy) behaviour

`defaultFetchOpts` in [app-ui/src/client/services/server-api/index.js](https://github.com/PathwayCommons/app-ui/blob/master/src/client/services/server-api/index.js#L7) does not work properly.

## Desired behaviour

Should be like 
` {headers: {'Accept': 'application/json'}}`

**Comment by jvwong** [comment]
Why isn't the current dev version not accomplishing this? It has the Accept field. Are you saying that we need to remove the other keys?

**Comment by jvwong** [comment]
nevermind, I see the difference, we're using [node-fetch](https://www.npmjs.com/package/node-fetch)
