### ISSUE TITLE
Information and documentation

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#923]
## Description of new feature

We should inform the user about some essential aspects of the pathway enrichment app. The user will be better informed about what the app will accomplish.

## Motivation for new feature

This will allow them to better understand if the app is suitable for their needs and what type of results to expect.

**Comment by jvwong** [comment]
Things that are important to know:

- analysis algorithm and implementation, version (g:GOSt)
- pathway data sources, versions
- pathway sizes (i.e. min/max_set_size)  

other?

**Comment by CaitlinOCallaghan** [comment]
Where do we want to put this information? On its own page? An info panel accessible from the tool bar?

**Comment by jvwong** [comment]
Info panel seems like a natural home.

**Comment by CaitlinOCallaghan** [comment]
### Enrichment Map Information
- Sentence describing use for and purpose of enrichment app. 

The Pathway Commons Enrichment Map application serves to graphically display over-represented functional categories as an interactive network given an input set of genes. 


-------- Start expandable list --------

### Accepted Gene Nomenclature 
- list all identifiers from archived g:profiler 
- perhaps render a search bar to filter visible list (not a major priority but could be useful)?  
![image](https://user-images.githubusercontent.com/38890251/43160249-a5949c30-8f52-11e8-9a86-fd905032bef7.png)

### Default Parameters 
- organism: homo sapien
- minimum gene set size: 5 genes
- maximum gene set size: 200 genes
- adjusted p-value algorithm: Benjamini-Hochberg procedure, false discovery rate (FDR)
- adjusted p-value threshold: 0.05

- can rename section to 'Settings'

### Analysis
- Functional analysis for Enrichment Map is powered by gProfiler's g:GOst service, archived version rev 1741 with build date 2017-10-19 and Ensemble 90 and Ensembl Genomes 37.
- I'm unsure of how to properly word the version/instance but this is how it's stated from the archived site ( https://biit.cs.ut.ee/gprofiler_archive3/r1741_e90_eg37/web/gconvert.cgi)
--> "Ensemble 90 and Ensembl Genomes 37 (rev 1741, build date 2017-10-19)"

### Visualization
- node size: size of gene set
- edge width: size of gene set overlap
- network structure and network functionality are powered by Cytoscape.js version 3.2.14

### More Information
- Enrichment analysis can be further explored with Cytoscape's EnrichmentMap App.  
- link to Cytoscape enrichment app information

**Comment by jvwong** [comment]
Maybe more like an FAQ? Also order from least technical to most technical:

--- 

> ### Enrichment Map Information
> - Sentence describing use for and purpose of enrichment app.
>
> The Pathway Commons Enrichment Map application serves to graphically display over-represented functional categories as an interactive network given an input set of genes.

We should settle on a name for the app (not 'Enrichment Map' at least). 

### What does <app name> do?
This app identifies biological pathways that contain your genes of interest and displays them as an interactive network, allowing you to explore individual pathways in more detail. Pathways are drawn from Reactome (version Y) and the Gene Ontology, Biological Process (version Z).      

--- 

> ### Accepted Gene Nomenclature
>
> - list all identifiers from archived g:profiler
> - perhaps render a search bar to filter visible list (not a major priority but could be useful)?

Let's just stick to the popular databases we would conceivably support beyond g:Convert:

### What kind of input do you accept?
This app will recognize:
  - An approved symbol from HUGO Gene Nomenclature (HGNC) (e.g. 'TP53'). Also acceptable are  HGNC IDs (e.g. 'HGNC:11998')
  - A protein accession from UniProt (e.g. 'P04637')
  - A Gene ID from NCBI Gene (e.g. '7157')  
 
--- 

> ### Visualization
> - node size: size of gene set
> - edge width: size of gene set overlap
> - network structure and network functionality are powered by Cytoscape.js version 3.2.14

### What do the elements of the network represent?

Each pathway is represented by a node (circle) whose size corresponds to the number of genes in that pathway. Pathways that share genes are connected by edges (lines) whose width corresponds to amount of shared genes. Click on a node to see...

--- 

> ### Analysis
> - Functional analysis for Enrichment Map is powered by gProfiler's g:GOst service, archived version rev 1741 with build date 2017-10-19 and Ensemble 90 and Ensembl Genomes 37.
> - I'm unsure of how to properly word the version/instance but this is how it's stated from the archived site ( https://biit.cs.ut.ee/gprofiler_archive3/r1741_e90_eg37/web/gconvert.cgi)
--> "Ensemble 90 and Ensembl Genomes 37 (rev 1741, build date 2017-10-19)"

### How does the app identify pathways?

Briefly, the input gene list is compared to genes in each candidate pathway and a statistical score  is calculated (adjusted p-value). Pathways with an adjusted p-value less than a threshold (0.05)  are deemed 'enriched' for genes in the input list and displayed in the network. This analysis is performed by gProfiler's g:GOst service (rev 1741  2017-10-19). Please refer to their [documentation](https://biit.cs.ut.ee/gprofiler_archive3/r1741_e90_eg37/web/) for further details.

---
