### ISSUE TITLE
Long text in title extends beyond bounds of app-bar-title container

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#930]
## Environment info

- Browser version (client) : Chrome 67.0.3396.99 (Official Build) (64-bit)
- Node.js version (server) : n/a

## Current (buggy) behaviour

Long text in titles will extend beyond the app-bar-title container bounds. 

## Desired behaviour

Not extend outside of container.

## Minimum steps to reproduce

See [TP53 regulates transcription of additional cell cycle genes whose exact role in the p53 pathway remain uncertain | Reactome ](http://localhost:3000/pathways?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-6804115)

![image](https://user-images.githubusercontent.com/4706307/43149869-872c53da-8f36-11e8-97a2-61639b68f81b.png)

**Comment by d2fong** [comment]
Can you still reproduce this?  I can't reproduce it on my computer?

**Comment by d2fong** [comment]
Nevermind, I can reproduce it when I zoom in with Chrome.

**Comment by jvwong** [comment]
I was resizing the browser width (Chrome, Firefox)
