### ISSUE TITLE
relocate enrichment unrecognized token feedback

### ISSUE THREAD

**Issue by CaitlinOCallaghan** [PathwayCommons/app-ui#941]
## Description of new feature

show feedback in side-menu if unrecognized tokens exist

## Motivation for new feature

current feedback box:
- covers the toolbar
- cannot be highlighted and copied
- uses an intricate path of setting states and case checking

**Comment by jvwong** [comment]
Sounds good as setup for slate or in-place markup.

**Comment by CaitlinOCallaghan** [comment]
View right after network loads

If unrecognized tokens:
- bad tokens listed in side menu
- input box open

![image](https://user-images.githubusercontent.com/38890251/43341884-d7f6624a-91ae-11e8-9947-f15dfc4d33a5.png)

All tokens valid:
- input box closed

![image](https://user-images.githubusercontent.com/38890251/43341863-c2e60112-91ae-11e8-80a1-c860e3933fbd.png)

**Comment by CaitlinOCallaghan** [comment]
I agree, I think moving the feedback to the side panel is a good halfway point before slate/in-place markup is implemented.

**Comment by maxkfranz** [comment]
Great.  It's a simple way to show that info.

It would be great to disable spellcheck on the textarea though.  The red underline could be confused with validation.

**Comment by CaitlinOCallaghan** [comment]
That's a good point, I will disable it

**Comment by jvwong** [comment]
We should avoid saying 'token' (users won't know what that is).  'Unrecognized inputs'?

**Comment by maxkfranz** [comment]
GeneMANIA uses the text 'unrecognised gene' and people seem to get it.

**Comment by maxkfranz** [comment]
![screen shot 2018-07-27 at 3 43 08 pm](https://user-images.githubusercontent.com/989043/43343317-cbc27b8a-91b3-11e8-8755-6ff67dfaf6bc.png)
