### ISSUE TITLE
pathways tooltip is broken when a node doesnt have a label or a display name

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#945]
sometimes a node will not have a label name / display name so in the pathways search link in the tooltip will just be ''.

Steps to reproduce:
1. go to /pathways?uri=http%3A%2F%2Fidentifiers.org%2Fwikipathways%2FWP2828
2. click on a process node (square box looking thing)
3. it should have a tooltip title called 'unknown entity'
4. click on the 'find relevant pathways' button
5. the node has no search term so you just search an empty string

Desired behaviour:
Possibly don't show the button if there is no search term.

**Comment by jvwong** [comment]
Related to #961
