### ISSUE TITLE
Google indexing 

### ISSUE THREAD

**Issue by hmtinc** [PathwayCommons/app-ui#95]
@jvwong 
https://github.com/PathwayCommons/pathways-search/issues/119

>https://stackoverflow.com/questions/8925397/how-to-let-google-index-my-database-driven-pages-that-are-not-direcly-linked-t
https://support.google.com/webmasters/answer/156184?hl=en

**Comment by jonahdlin** [comment]
TL;DR: There isn't as of now, and I can implement it, but it will take a few weeks to test if it worked.

Soon after a new site is added, google will quickly search through the HTML for index-able items like description and title. @maxkfranz has told me that if we set those fields with JS (which is our only option unless we bring back HTML templating), Google will still index the site, but only after a few weeks. So I can add the code in on Monday, but I won't know if it works or not for a while.

**Comment by maxkfranz** [comment]
It's not really worth doing until the UI is more or less finalised, at least for search.
