### ISSUE TITLE
chrome zoom breaks the network view

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#950]
## Environment info

- Browser version (client) : Chrome 67.0.3396.99 
- Node.js version (server) : 

## Current (buggy) behaviour

The network viewer is wonky after randomly changing chrome zoom levels

## Desired behaviour

The network viewer should work correctly after any amount of zoom changes

## Minimum steps to reproduce
1. Go to the following link:
http://localhost:3000/pathways?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-6804115
2. Play with the zoom level:
press:
`cmd +`, or `cmd -` a bunch of times

3. Reset zoom level (Optional)
press:
`cmd 0`

The network is either permanently small or large depending on the zoom level you got to.

**Comment by jvwong** [comment]
I get a cutoff compartment that can't be dragged:

![image](https://user-images.githubusercontent.com/4706307/44529701-baa05e00-a6ba-11e8-868f-b93e79372ea1.png)
