### ISSUE TITLE
Interactions Sidebar Does not appear by default

### ISSUE THREAD

**Issue by MichaelWrana** [PathwayCommons/app-ui#951]
## Environment info

- Browser version (client) : Safari Latest

## Current (buggy) behaviour

Upon Loading the interaction viewer the sidebar does not appear, but the button in the top-left menu indicates it should be there.

In order to make it appear, it is required to press the button twice.  Once to "hide" the sidebar, then again to make it appear.

The network also "thinks" the sidebar is there, and cuts of nodes at an apparently invisible barrier.

## Desired behaviour

Sidebar should either appear by default, or button should indicate the sidebar as "not visible" by default.

## Minimum steps to reproduce

Open: http://localhost:3000/interactions?source=TP53&source=GDF15

**Comment by MichaelWrana** [comment]
Example Image

![screen shot 2018-08-08 at 12 01 04 pm](https://user-images.githubusercontent.com/25777239/43849209-e7cc602c-9b02-11e8-8b86-3e9192a95325.png)

**Comment by d2fong** [comment]
This is fixed in my branch.  Would you like me to merge my work so that you can work off of it?
