### ISSUE TITLE
Cache: Case when cache sets value as error

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#954]
## Environment info

- Browser version (client) : n/a
- Node.js version (server) : n/a

## Current (buggy) behaviour

There is in-memory caching for fetching SIF and [validation](https://github.com/PathwayCommons/app-ui/blob/f6754e6137890a465c007ab1858523cf20b976a5/src/server/enrichment/validation/index.js#L144-L146). In the latter case, I noticed searching for one of the examples 'TP53 MDM2' failed, and each subsequent call thereby returned nothing/Error for that query. 

## Desired behaviour

Don't want failed responses to be cached.

## Minimum steps to reproduce

Difficult to reproduce but can turn off g:Convert call temporarily.

Maybe caching is bad here, remove.?

**Comment by maxkfranz** [comment]
The cache should never store failures.  There should be a `.catch()` that sends an error to the client and leaves the cache as-is.

**Comment by maxkfranz** [comment]
`.catch()` -- on a promise object
