### ISSUE TITLE
Remove logic/operations from service calls to GO/Reactome  

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#958]
In [/src/client/services/server-api/index.js](https://github.com/PathwayCommons/app-ui/blob/750ba569d987f99bd3445f38485beacb59008042/src/client/services/server-api/index.js#L29-L47), specifically:`getGoInformation` and `getReactomeInformation`:

- log errors 
- input string manipulation tightly coupled to enrichment case ( (i.e. `replace("REAC:...)`)
- response manipulation seems risky (e.g. `res.results[0]...`)

**Comment by CaitlinOCallaghan** [comment]
By 'log errors', do you mean use 'catch' or actually throw an error and log it in the console?

**Comment by jvwong** [comment]
Let's skip the 'logging' - it would be more useful to log IF it was happening on our server.
