### ISSUE TITLE
Don't use "Unknown Entity" title in the interaction node info boxes (or at all)

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/app-ui#961]
It's probably a bad idea to set "Unknown Entity" title in the interaction node info boxes.
It's simply untrue, also misleading, distracting, unhelpful information.
Much better would be to see there a biopax class name alone if no display name there exists.

**Comment by IgorRodchenkov** [comment]
![image](https://user-images.githubusercontent.com/991169/43861635-700634a0-9b25-11e8-9044-53a6540ce17e.png)

**Comment by maxkfranz** [comment]
In short: If no name exists, then put the empty string where the name would go.
