### ISSUE TITLE
Interactions: Consistency in node tooltip 'Links' 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#967]
## Description of new feature

In the interactions app, clicking a node reveals a tooltip with relevant metadata, including 'Links' that derive from external database information.

The user should be presented with Links in a more uniform and consistent fashion. For instance, only display links for particular databases, in a location or way that doesn't seem 'random' .

## Motivation for new feature

This will ease navigating the network and tooltip information by having links to external databases in the same location, order.

#### BRCA2
![image](https://user-images.githubusercontent.com/4706307/43860132-bdbdc96a-9b20-11e8-94a6-8710790dd6c4.png)

and the [sif](http://www.pathwaycommons.org/pc2/graph?cmd=graph&source=BRCA2&pattern=controls-phosphorylation-of&pattern=in-complex-with&pattern=controls-expression-of&pattern=interacts-with&kind=neighborhood&format=txt) data:
```txt
BRCA2	DnaReference;ProteinReference;RnaReference	BRCA2;BRCA2 mRNA;BRCA2 promoter;BRCA2_HUMAN;Peptide Linker;brca2_human_gene	ensembl:ENSG00000139618;hprd:02554;ncbi gene:675;refseq:NP_000050;uniprot knowledgebase:P51587	hgnc symbol:BRCA2;intact:EBI-11664513;omim:600185;uniprot knowledgebase:P51587
```

MAP6K
![image](https://user-images.githubusercontent.com/4706307/43860152-c915405e-9b20-11e8-8ca1-91688008c999.png)

and the sif data: 

```txt
MAPK6	ProteinReference	MK06_HUMAN	uniprot knowledgebase:Q16659	hgnc symbol:MAPK6
```

**Comment by jvwong** [comment]
If exists in SIF put it in for now. Optimize later.

**Comment by q4wen** [comment]
![screen shot 2018-08-09 at 11 19 44 am](https://user-images.githubusercontent.com/16858225/43908527-3ebc99d8-9bc6-11e8-9c50-128b05fa6f70.png)

**Comment by MichaelWrana** [comment]
Should probably close this for now considering tooltips are completely disabled on interactions view

**Comment by jvwong** [comment]
I think it's a valid issue - can we reawaken the tooltips?

**Comment by d2fong** [comment]
Should database links be limited to the same ones as the entity info box (uniprot, ncbi gene, gene cards, hgnc)?

**Comment by jvwong** [comment]
This looks tricky. The SIF `PARTICIPANT_TYPE` will be 0 or more EntityReferences for protein, chemical, dna/rna(region) etc. but which one comes up is anyone's guess.

Maybe just split `UNIFICATION_XREF` field on semicolon and return links for all using (src/client/common/external-service-data.js)
