### ISSUE TITLE
Make tippy css 'a' selector more specific

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#97]
https://github.com/PathwayCommons/app-ui/blob/master/src/styles/features/view/toolTip.css#L71

This causes all a tags to have that colour.  Can you put this under a class selector?

**Comment by maxkfranz** [comment]
Just use the existing `a.plain-link` to get a plain link with a blue underline.  The default `a` is unstyled so you can use it more flexibly.

**Comment by maxkfranz** [comment]
https://github.com/PathwayCommons/app-ui/blob/0ae99afbb2be63292b28089d8ab4b8f9fdce3068/src/styles/base.css#L370-L379
