### ISSUE TITLE
Expand/Collapse button disappearing

### ISSUE THREAD

**Issue by MichaelWrana** [PathwayCommons/app-ui#970]
## Environment info

- Browser version (client) : Safari latest
- Node.js version (server) : N/A

## Current (buggy) behaviour
When hovering over a complex's children, the expand collapse button for that complex disappears.

![demo](https://user-images.githubusercontent.com/25777239/43908474-12bb0662-9bc6-11e8-883e-e18359e2e0d6.gif)

## Desired behaviour

The expand/collapse button should continue to appear for complexes while hovering over the complex's children.

## Minimum steps to reproduce
Open any network with complexes in the pathway view.  Attempt to close a complex by hovering over it, and pathing your mouse over one of it's children.

**Comment by jvwong** [comment]
see #1008
