### ISSUE TITLE
Opening Certain Interactions Causes Error

### ISSUE THREAD

**Issue by MichaelWrana** [PathwayCommons/app-ui#972]
## Environment info

- Browser version (client) : Safari latest
- Node.js version (server) : N/A

## Current (buggy) behaviour
Attempting to load certain networks produces the following error:

![screen shot 2018-08-09 at 1 54 29 pm](https://user-images.githubusercontent.com/25777239/43916530-c3381b46-9bdb-11e8-8e38-3e6d63407012.png)

## Desired behaviour
Shouldn't Break

## Minimum steps to reproduce
Load the following network:
http://localhost:3000/interactions?source=TP53&source=GDF15

**Comment by jvwong** [comment]
This issue originates from changes to src/client/features/interactions/index.js introduced in https://github.com/PathwayCommons/app-ui/pull/966/files:

Basically, we're representing multiple sources as a comma-separated list, which is forwarded to PC web service as is (I think it's OK this way but not explicitly mentioned in docs).

Is there a case where the above format for `sources` exists?

**Comment by MichaelWrana** [comment]
Looks like `sources` has this format in all cases when querying multiple genes:

![screen shot 2018-08-09 at 2 45 08 pm](https://user-images.githubusercontent.com/25777239/43919073-d808b150-9be2-11e8-9f1f-0449c91da39b.png)

hopefully an easy fix by reverting that line back to `concat`

**Comment by jvwong** [comment]
OK let's close as the multiple key case does not happen within the app itself.
