### ISSUE TITLE
Slider no longer works on 'click'

### ISSUE THREAD

**Issue by MichaelWrana** [PathwayCommons/app-ui#974]
## Environment info

- Browser version (client) : Safari Latest
- Node.js version (server) :

## Current (buggy) behaviour

In some circumstances, when attempting to click and change the slider rather than slide it, the nodes all disappear, or do not display correctly.

## Desired behaviour
Slider should behave normally when user clicks on a point vs slides it manually.

## Minimum steps to reproduce
- Open any network in interactions
- Click the slider on the right side near "Less"
- Click the slider back to the left side near "More"
- All nodes wil disappear

**Comment by jvwong** [comment]
I see this but it was a little tricky to reproduce:

![bug](https://user-images.githubusercontent.com/4706307/43918761-022e24ca-9be2-11e8-8ad2-99c06f307c25.gif)

**Comment by jvwong** [comment]
In a variation, this query: http://localhost:3000/interactions?source=TP53,ZNF385A results in the network always disappearing and random parts reappearing when the slider is manipulated back and forth.

**Comment by jvwong** [comment]
Possibly related: Setting the slider and the types then returning to original settings results in different network:

![bug](https://user-images.githubusercontent.com/4706307/43967645-dcaf55fa-9c92-11e8-89d8-ce09149dbe4c.gif)

**Comment by d2fong** [comment]
Related #1000
