### ISSUE TITLE
Hiding and showing interactions sidebar resets slider position

### ISSUE THREAD

**Issue by MichaelWrana** [PathwayCommons/app-ui#975]
## Environment info

- Browser version (client) : Safari latest
- Node.js version (server) :

## Current (buggy) behaviour

Slider position is reset when the interactions sidebar is opened and closed again.

## Desired behaviour

The slider should retain it's previous position after opening and closing the sidebar

## Minimum steps to reproduce
- Open any network in interactions view
- move the slider to a new position
- Close the sidebar and reopen
- Slider will reset position

**Comment by jvwong** [comment]
Also the re-opened slider position is not reflective of the network (vice versa).

**Comment by MichaelWrana** [comment]
Fixed in #1001
