### ISSUE TITLE
Submitting empty query throws TypeError

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#978]
## Environment info

- Browser version (client) : n/a
- Node.js version (server) : n/a

## Current (buggy) behaviour

Throws a TypeError.

## Desired behaviour

Deal with this as a valid case.

## Minimum steps to reproduce

Just click submit upon load.

Console:
![image](https://user-images.githubusercontent.com/4706307/43918012-cf150cea-9bdf-11e8-8b95-15b6a9509f14.png)

 Hints:

>src/client/features/enrichment/token-input.js
```
//call validation service API to retrieve validation result in the form of []
  retrieveValidationAPIResult(){
    let { inputBoxContents } = this.state;
    let { controller } = this.props;

    let tokenList = _.pull(inputBoxContents.split(/\s/g), "");
     ServerAPI.enrichmentAPI({
       genes: tokenList,
       targetDb: "HGNCSYMBOL"
      }, "validation")
    .then( result => {
      const aliases = result.geneInfo.map( value => {
        return value.convertedAlias;
      });

      controller.handleGeneQueryResult( {
        genes: aliases,
        unrecognized: result.unrecognized,
      });
    });
  }
```

**Comment by CaitlinOCallaghan** [comment]
Closed
