### ISSUE TITLE
no visible nodes for smaller networks at default slider value

### ISSUE THREAD

**Issue by CaitlinOCallaghan** [PathwayCommons/app-ui#979]
## Environment info

- interactions app

## Current (buggy) behaviour

- initial network display for smaller networks has no visible nodes with default slider value

Right after loading

![image](https://user-images.githubusercontent.com/38890251/43918375-e2c3b0f6-9be0-11e8-8011-4b619dffb089.png)

After adjusting slider

![image](https://user-images.githubusercontent.com/38890251/43918382-eac170f4-9be0-11e8-88f4-d44bbf28cd12.png)

**Comment by d2fong** [comment]
related #975 

Rough notes:  static default slider value is used (35) instead of generating the default val on a per network basis.  Also related is that there is no state for the slider value so it resets, exhibiting the behaviour seen in #983 975

**Comment by maxkfranz** [comment]
Another way to put it:

If the number of total nodes is less than 25, then the default slider value should show all the nodes.

**Comment by maxkfranz** [comment]
Actual:

![screen shot 2018-08-13 at 4 58 02 pm](https://user-images.githubusercontent.com/989043/44057740-16b6bb42-9f1a-11e8-8f86-e772cd77d459.png)

Expected:

![screen shot 2018-08-13 at 4 58 08 pm](https://user-images.githubusercontent.com/989043/44057742-16fbecf8-9f1a-11e8-8737-f50849694740.png)
