### ISSUE TITLE
for new networks, enrichment slider value does not match position 

### ISSUE THREAD

**Issue by CaitlinOCallaghan** [PathwayCommons/app-ui#984]
## Current (buggy) behaviour

- when loading a new network after the initial network, the slider value does not match its position 

## Minimum steps to reproduce
- search 'XPO1' 
- move slider to left
- search 'TP53'

## Desired behaviour

- close side menu when loading to force a re-render
- also close toolbar for aesthetic visual purposes
- reopen toolbar and side menu when network is loaded

**Comment by d2fong** [comment]
You need to add slider value to the main component state.

**Comment by d2fong** [comment]
also when loading a new network if you compute the initial slider state based off of network information, you will have to upload the slider value state whenever you load a new network.

**Comment by q4wen** [comment]
If we want to show/hide the sidebar menu, should we change [common/components/sidebar.js](https://github.com/PathwayCommons/app-ui/blob/development/src/client/common/components/sidebar.js)? I am worried it will affect other pages.
