### ISSUE TITLE
Glyphs get cutoff upon 'Expand/Collapse all complexes' multiple times in Chrome 68

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#988]
## Environment info

- Browser version (client) : Chrome Version 68.0.3440.84 (Official Build) (64-bit)
- Node.js version (server) : 

## Current (buggy) behaviour

Viewing a pathway (e.g. http://localhost:3000/pathways?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-69895) and clicking the 'expand/collapse' menu button repeatedly leads to glyphs that are cutoff, partially rendered.

## Desired behaviour

Show the entire glyph up expand. 

## Minimum steps to reproduce

NB: Does NOT  arise in Firefox 61.0.1 (64-bit)

![bug](https://user-images.githubusercontent.com/4706307/43922677-6c19a854-9bed-11e8-86da-11cfbef59795.gif)

**Comment by MichaelWrana** [comment]
Doesn't arise in safari (Version 11.1.2 (11605.3.8.1)) either
