### ISSUE TITLE
Attempting to Search crashes enrichment view

### ISSUE THREAD

**Issue by MichaelWrana** [PathwayCommons/app-ui#989]
## Environment info

- Browser version (client) : Safari latest
- Node.js version (server) :

## Current (buggy) behaviour
Searching for a gene when the network is empty produces the following error, and completely crashes the enrichment app:
![screen shot 2018-08-09 at 4 14 17 pm](https://user-images.githubusercontent.com/25777239/43923281-4f0b6386-9bef-11e8-897f-c12d08f8ee6b.png)

This Search bar, not the main one:
![screen shot 2018-08-09 at 4 17 31 pm](https://user-images.githubusercontent.com/25777239/43923426-bbf6e45c-9bef-11e8-9eef-8b8bae17d41b.png)

## Desired behaviour
Searching for an empty network should do nothing, or disable search bar when there is no network

## Minimum steps to reproduce
- Open enrichment view
- submit query for any real gene (ex orc3) in main search bar
- delete query, submit new query for nonexistent gene (ex fff)
- Attempt to type something in the network search bar
- crash

**Comment by jvwong** [comment]
See #992
