### ISSUE TITLE
Enrichment Input Special Characters

### ISSUE THREAD

**Issue by CaitlinOCallaghan** [PathwayCommons/app-ui#991]
## Environment info

- enrichment app

## Current (buggy) behaviour

enrichment service does not properly process all special characters

identified problematic special characters:
- '#' prevents the validation of all following tokens
- '+' is treated like '\s'

## Desired behaviour

- treat all characters as strings and properly handle input
- identify all inputs as valid or invalid

## Minimum steps to reproduce

enter '#', '+' into gene input

![image](https://user-images.githubusercontent.com/38890251/43924342-621934c8-9bf2-11e8-9b73-2de9408c0bc6.png)

## NOTE: 

- gConvert can handle '#' but not '+'

![image](https://user-images.githubusercontent.com/38890251/43924451-ab49f088-9bf2-11e8-93d7-f10551cd22a4.png)

**Comment by jvwong** [comment]
Great catch - so to recap, this appears to be a known behaviour of g:Convert, g:GOSt, although it's unlikely to be documented. In this case, I'm hesitant to start interpreting or modifying user input on behalf of the service.

Let's close and reopen if this comes up concretely - e.g. a gene ID has a '+' surrounded by two valid HGNC symbols?

**Comment by maxkfranz** [comment]
`encodeURIComponent()` may resolve this

**Comment by maxkfranz** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent
