### ISSUE TITLE
Enrichment network 'Fit pathway to screen' non-functional, throws TypeError 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#995]
## Environment info

- Browser version (client) : Chrome Version 68.0.3440.106 (Official Build) (64-bit); Firefox 61.0.2 (64-bit)
- Node.js version (server) : n/a

## Current (buggy) behaviour

Non-functional 'fit pathway to screen' button, throws TypeError:

![image](https://user-images.githubusercontent.com/4706307/43960695-ccc4da00-9c80-11e8-98e4-22e0d4b715b4.png)

Also this button shouldn't be named 'Fit pathway to screen' but rather 'Fit to screen' --> separate issue #996 
 
## Desired behaviour

Fit network to screen. No TypeError.

## Minimum steps to reproduce

- Enter a query
- Zoom out with mouse
- Click menu item 'Fit pathway to screen'

![image](https://user-images.githubusercontent.com/4706307/43960619-925b3d00-9c80-11e8-8d33-5cb8b2948254.png)

**Comment by jvwong** [comment]
While we're at it, the 'Reset pathway arrangement' also throws a TypeError and is non-functional:

![image](https://user-images.githubusercontent.com/4706307/43961459-0ac2fd80-9c83-11e8-8b63-61af2bdf00b8.png)

**Comment by maxkfranz** [comment]
Possibly related to the `cySrv` changes

**Comment by CaitlinOCallaghan** [comment]
It's from the new base network view refactoring.
