### ISSUE TITLE
Infobox behaviour on datasource filter changes

### ISSUE THREAD

**Issue by MichaelWrana** [PathwayCommons/app-ui#997]
## Description of new feature
Infobox behaviour on datasource filter updates
If I do the following:
- new search page
- Start search for any gene (i.e TP53) 
- hide infobox with collapse button in top-right
- change datasource (i.e. Reactome) in drop-down menu

Should the state of the infobox remain the same (closed in this case)?  Currently it re-opens and collapses description every time the datasource filter is modified.

Seems pretty minor and I'm guessing it will be a lot of work to change, might not be worth it.

## Motivation for new feature
 general user experience

**Comment by jvwong** [comment]
The 'filter' in this case generates an entirely new search, rather than filtering the existing results. It would be nice to have the latter, but how do you know if you are getting 'enough' results of that type?

This is kinda related to #296.
