### ISSUE TITLE
enrichment SIF download option not functional 

### ISSUE THREAD

**Issue by CaitlinOCallaghan** [PathwayCommons/app-ui#998]
## Environment
- enrichment app
## Current (buggy) behaviour

- SIF option in side panel not functional

## Desired behaviour

- either remove SIF option or add functionality

## Minimum steps to reproduce

- click on download icon in toolbar to open side panel
- click on 'SIF' from side panel
![image](https://user-images.githubusercontent.com/38890251/43965511-749505aa-9c8d-11e8-88a7-b67912f4cdf9.png)

**Comment by jvwong** [comment]
This is beyond 'MVP' so remove.
